.syntax unified
	.text
	.align 2, 0
	.arm

	.global func_081196B4
	.type func_081196B4, %function
func_081196B4:
.LgUnk_081196B4:
	.incbin "asm/movie_codec.bin", 0x0, 0x60

.LgUnk_08119714:
	.incbin "asm/movie_codec.bin", 0x60, 0x6A4

.LgUnk_08119DB8:
	.incbin "asm/movie_codec.bin", 0x704, 0xB8

.LgUnk_08119E70:
	.incbin "asm/movie_codec.bin", 0x7BC, 0x2B74

.LgUnk_0811C9E4:
	.incbin "asm/movie_codec.bin", 0x3330, 0x400

.LgUnk_0811CDE4:
	.incbin "asm/movie_codec.bin", 0x3730, 0x60

.LgUnk_0811CE44:
	.incbin "asm/movie_codec.bin", 0x3790, 0x2C8

.LgUnk_0811D10C:
	.incbin "asm/movie_codec.bin", 0x3A58, 0x78

.LgUnk_0811D184:
	.incbin "asm/movie_codec.bin", 0x3AD0, 0x20

.LgUnk_0811D1A4:
	.incbin "asm/movie_codec.bin", 0x3AF0, 0xC

.syntax divided
