#ifndef GUARD_GBA_IO_REG_H
#define GUARD_GBA_IO_REG_H

#include "types.h"

#define REG_BASE 0x04000000

#define REG_OFFSET_DISPCNT     0x0
#define REG_OFFSET_DISPSTAT    0x4
#define REG_OFFSET_VCOUNT      0x6
#define REG_OFFSET_BG0CNT      0x8
#define REG_OFFSET_BG1CNT      0xA
#define REG_OFFSET_BG2CNT      0xC
#define REG_OFFSET_BG3CNT      0xE
#define REG_OFFSET_BG0HOFS     0x10
#define REG_OFFSET_BG0VOFS     0x12
#define REG_OFFSET_BG1HOFS     0x14
#define REG_OFFSET_BG1VOFS     0x16
#define REG_OFFSET_BG2HOFS     0x18
#define REG_OFFSET_BG2VOFS     0x1A
#define REG_OFFSET_BG3HOFS     0x1C
#define REG_OFFSET_BG3VOFS     0x1E
#define REG_OFFSET_BG2PA       0x20
#define REG_OFFSET_BG2PB       0x22
#define REG_OFFSET_BG2PC       0x24
#define REG_OFFSET_BG2PD       0x26
#define REG_OFFSET_BG2X        0x28
#define REG_OFFSET_BG2Y        0x2C
#define REG_OFFSET_BG3PA       0x30
#define REG_OFFSET_BG3PB       0x32
#define REG_OFFSET_BG3PC       0x34
#define REG_OFFSET_BG3PD       0x36
#define REG_OFFSET_BG3X        0x38
#define REG_OFFSET_BG3Y        0x3C
#define REG_OFFSET_WIN0H       0x40
#define REG_OFFSET_WIN1H       0x42
#define REG_OFFSET_WIN0V       0x44
#define REG_OFFSET_WIN1V       0x46
#define REG_OFFSET_WININ       0x48
#define REG_OFFSET_WINOUT      0x4A
#define REG_OFFSET_MOSAIC      0x4C
#define REG_OFFSET_BLDCNT      0x50
#define REG_OFFSET_BLDALPHA    0x52
#define REG_OFFSET_BLDY        0x54
#define REG_OFFSET_SOUND1CNT_L 0x60
#define REG_OFFSET_NR10        0x60
#define REG_OFFSET_SOUND1CNT_H 0x62
#define REG_OFFSET_NR11        0x62
#define REG_OFFSET_NR12        0x63
#define REG_OFFSET_SOUND1CNT_X 0x64
#define REG_OFFSET_NR13        0x64
#define REG_OFFSET_NR14        0x65
#define REG_OFFSET_SOUND2CNT_L 0x68
#define REG_OFFSET_NR21        0x68
#define REG_OFFSET_NR22        0x69
#define REG_OFFSET_SOUND2CNT_H 0x6C
#define REG_OFFSET_NR23        0x6C
#define REG_OFFSET_NR24        0x6D
#define REG_OFFSET_SOUND3CNT_L 0x70
#define REG_OFFSET_NR30        0x70
#define REG_OFFSET_SOUND3CNT_H 0x72
#define REG_OFFSET_NR31        0x72
#define REG_OFFSET_NR32        0x73
#define REG_OFFSET_SOUND3CNT_X 0x74
#define REG_OFFSET_NR33        0x74
#define REG_OFFSET_NR34        0x75
#define REG_OFFSET_SOUND4CNT_L 0x78
#define REG_OFFSET_NR41        0x78
#define REG_OFFSET_NR42        0x79
#define REG_OFFSET_SOUND4CNT_H 0x7C
#define REG_OFFSET_NR43        0x7C
#define REG_OFFSET_NR44        0x7D
#define REG_OFFSET_SOUNDCNT_L  0x80
#define REG_OFFSET_NR50        0x80
#define REG_OFFSET_NR51        0x81
#define REG_OFFSET_SOUNDCNT_H  0x82
#define REG_OFFSET_SOUNDCNT_X  0x84
#define REG_OFFSET_NR52        0x84
#define REG_OFFSET_SOUNDBIAS   0x88
#define REG_OFFSET_SOUNDBIAS_L 0x88
#define REG_OFFSET_SOUNDBIAS_H 0x89
#define REG_OFFSET_WAVE_RAM0   0x90
#define REG_OFFSET_WAVE_RAM1   0x94
#define REG_OFFSET_WAVE_RAM2   0x98
#define REG_OFFSET_WAVE_RAM3   0x9C
#define REG_OFFSET_FIFO_A      0xA0
#define REG_OFFSET_FIFO_B      0xA4
#define REG_OFFSET_DMA0        0xB0
#define REG_OFFSET_DMA0SAD     0xB0
#define REG_OFFSET_DMA0DAD     0xB4
#define REG_OFFSET_DMA0CNT     0xB8
#define REG_OFFSET_DMA0CNT_L   0xB8
#define REG_OFFSET_DMA0CNT_H   0xBA
#define REG_OFFSET_DMA1        0xBC
#define REG_OFFSET_DMA1SAD     0xBC
#define REG_OFFSET_DMA1DAD     0xC0
#define REG_OFFSET_DMA1CNT     0xC4
#define REG_OFFSET_DMA1CNT_L   0xC4
#define REG_OFFSET_DMA1CNT_H   0xC6
#define REG_OFFSET_DMA2        0xC8
#define REG_OFFSET_DMA2SAD     0xC8
#define REG_OFFSET_DMA2DAD     0xCC
#define REG_OFFSET_DMA2CNT     0xD0
#define REG_OFFSET_DMA2CNT_L   0xD0
#define REG_OFFSET_DMA2CNT_H   0xD2
#define REG_OFFSET_DMA3        0xD4
#define REG_OFFSET_DMA3SAD     0xD4
#define REG_OFFSET_DMA3DAD     0xD8
#define REG_OFFSET_DMA3CNT     0xDC
#define REG_OFFSET_DMA3CNT_L   0xDC
#define REG_OFFSET_DMA3CNT_H   0xDE
#define REG_OFFSET_TM0CNT      0x100
#define REG_OFFSET_TM0CNT_L    0x100
#define REG_OFFSET_TM0CNT_H    0x102
#define REG_OFFSET_TM1CNT      0x104
#define REG_OFFSET_TM1CNT_L    0x104
#define REG_OFFSET_TM1CNT_H    0x106
#define REG_OFFSET_TM2CNT      0x108
#define REG_OFFSET_TM2CNT_L    0x108
#define REG_OFFSET_TM2CNT_H    0x10A
#define REG_OFFSET_TM3CNT      0x10C
#define REG_OFFSET_TM3CNT_L    0x10C
#define REG_OFFSET_TM3CNT_H    0x10E
#define REG_OFFSET_SIOCNT      0x128
#define REG_OFFSET_SIODATA8    0x12A
#define REG_OFFSET_SIODATA32   0x120
#define REG_OFFSET_SIOMULTI0   0x120
#define REG_OFFSET_SIOMULTI1   0x122
#define REG_OFFSET_SIOMULTI2   0x124
#define REG_OFFSET_SIOMULTI3   0x126
#define REG_OFFSET_SIOMLT_SEND 0x12A
#define REG_OFFSET_SIOMLT_RECV 0x120
#define REG_OFFSET_KEYINPUT    0x130
#define REG_OFFSET_KEYCNT      0x132
#define REG_OFFSET_RCNT        0x134
#define REG_OFFSET_IE          0x200
#define REG_OFFSET_IF          0x202
#define REG_OFFSET_WAITCNT     0x204
#define REG_OFFSET_IME         0x208

#define REG_ADDR_DISPCNT     (REG_BASE + REG_OFFSET_DISPCNT)
#define REG_ADDR_DISPSTAT    (REG_BASE + REG_OFFSET_DISPSTAT)
#define REG_ADDR_VCOUNT      (REG_BASE + REG_OFFSET_VCOUNT)
#define REG_ADDR_BG0CNT      (REG_BASE + REG_OFFSET_BG0CNT)
#define REG_ADDR_BG1CNT      (REG_BASE + REG_OFFSET_BG1CNT)
#define REG_ADDR_BG2CNT      (REG_BASE + REG_OFFSET_BG2CNT)
#define REG_ADDR_BG3CNT      (REG_BASE + REG_OFFSET_BG3CNT)
#define REG_ADDR_BG0HOFS     (REG_BASE + REG_OFFSET_BG0HOFS)
#define REG_ADDR_BG0VOFS     (REG_BASE + REG_OFFSET_BG0VOFS)
#define REG_ADDR_BG1HOFS     (REG_BASE + REG_OFFSET_BG1HOFS)
#define REG_ADDR_BG1VOFS     (REG_BASE + REG_OFFSET_BG1VOFS)
#define REG_ADDR_BG2HOFS     (REG_BASE + REG_OFFSET_BG2HOFS)
#define REG_ADDR_BG2VOFS     (REG_BASE + REG_OFFSET_BG2VOFS)
#define REG_ADDR_BG3HOFS     (REG_BASE + REG_OFFSET_BG3HOFS)
#define REG_ADDR_BG3VOFS     (REG_BASE + REG_OFFSET_BG3VOFS)
#define REG_ADDR_BG2PA       (REG_BASE + REG_OFFSET_BG2PA)
#define REG_ADDR_BG2PB       (REG_BASE + REG_OFFSET_BG2PB)
#define REG_ADDR_BG2PC       (REG_BASE + REG_OFFSET_BG2PC)
#define REG_ADDR_BG2PD       (REG_BASE + REG_OFFSET_BG2PD)
#define REG_ADDR_BG2X        (REG_BASE + REG_OFFSET_BG2X)
#define REG_ADDR_BG2Y        (REG_BASE + REG_OFFSET_BG2Y)
#define REG_ADDR_BG3PA       (REG_BASE + REG_OFFSET_BG3PA)
#define REG_ADDR_BG3PB       (REG_BASE + REG_OFFSET_BG3PB)
#define REG_ADDR_BG3PC       (REG_BASE + REG_OFFSET_BG3PC)
#define REG_ADDR_BG3PD       (REG_BASE + REG_OFFSET_BG3PD)
#define REG_ADDR_BG3X        (REG_BASE + REG_OFFSET_BG3X)
#define REG_ADDR_BG3Y        (REG_BASE + REG_OFFSET_BG3Y)
#define REG_ADDR_WIN0H       (REG_BASE + REG_OFFSET_WIN0H)
#define REG_ADDR_WIN1H       (REG_BASE + REG_OFFSET_WIN1H)
#define REG_ADDR_WIN0V       (REG_BASE + REG_OFFSET_WIN0V)
#define REG_ADDR_WIN1V       (REG_BASE + REG_OFFSET_WIN1V)
#define REG_ADDR_WININ       (REG_BASE + REG_OFFSET_WININ)
#define REG_ADDR_WINOUT      (REG_BASE + REG_OFFSET_WINOUT)
#define REG_ADDR_MOSAIC      (REG_BASE + REG_OFFSET_MOSAIC)
#define REG_ADDR_BLDCNT      (REG_BASE + REG_OFFSET_BLDCNT)
#define REG_ADDR_BLDALPHA    (REG_BASE + REG_OFFSET_BLDALPHA)
#define REG_ADDR_BLDY        (REG_BASE + REG_OFFSET_BLDY)
#define REG_ADDR_SOUND1CNT_L (REG_BASE + REG_OFFSET_SOUND1CNT_L)
#define REG_ADDR_NR10        (REG_BASE + REG_OFFSET_NR10)
#define REG_ADDR_SOUND1CNT_H (REG_BASE + REG_OFFSET_SOUND1CNT_H)
#define REG_ADDR_NR11        (REG_BASE + REG_OFFSET_NR11)
#define REG_ADDR_NR12        (REG_BASE + REG_OFFSET_NR12)
#define REG_ADDR_SOUND1CNT_X (REG_BASE + REG_OFFSET_SOUND1CNT_X)
#define REG_ADDR_NR13        (REG_BASE + REG_OFFSET_NR13)
#define REG_ADDR_NR14        (REG_BASE + REG_OFFSET_NR14)
#define REG_ADDR_SOUND2CNT_L (REG_BASE + REG_OFFSET_SOUND2CNT_L)
#define REG_ADDR_NR21        (REG_BASE + REG_OFFSET_NR21)
#define REG_ADDR_NR22        (REG_BASE + REG_OFFSET_NR22)
#define REG_ADDR_SOUND2CNT_H (REG_BASE + REG_OFFSET_SOUND2CNT_H)
#define REG_ADDR_NR23        (REG_BASE + REG_OFFSET_NR23)
#define REG_ADDR_NR24        (REG_BASE + REG_OFFSET_NR24)
#define REG_ADDR_SOUND3CNT_L (REG_BASE + REG_OFFSET_SOUND3CNT_L)
#define REG_ADDR_NR30        (REG_BASE + REG_OFFSET_NR30)
#define REG_ADDR_SOUND3CNT_H (REG_BASE + REG_OFFSET_SOUND3CNT_H)
#define REG_ADDR_NR31        (REG_BASE + REG_OFFSET_NR31)
#define REG_ADDR_NR32        (REG_BASE + REG_OFFSET_NR32)
#define REG_ADDR_SOUND3CNT_X (REG_BASE + REG_OFFSET_SOUND3CNT_X)
#define REG_ADDR_NR33        (REG_BASE + REG_OFFSET_NR33)
#define REG_ADDR_NR34        (REG_BASE + REG_OFFSET_NR34)
#define REG_ADDR_SOUND4CNT_L (REG_BASE + REG_OFFSET_SOUND4CNT_L)
#define REG_ADDR_NR41        (REG_BASE + REG_OFFSET_NR41)
#define REG_ADDR_NR42        (REG_BASE + REG_OFFSET_NR42)
#define REG_ADDR_SOUND4CNT_H (REG_BASE + REG_OFFSET_SOUND4CNT_H)
#define REG_ADDR_NR43        (REG_BASE + REG_OFFSET_NR43)
#define REG_ADDR_NR44        (REG_BASE + REG_OFFSET_NR44)
#define REG_ADDR_SOUNDCNT_L  (REG_BASE + REG_OFFSET_SOUNDCNT_L)
#define REG_ADDR_NR50        (REG_BASE + REG_OFFSET_NR50)
#define REG_ADDR_NR51        (REG_BASE + REG_OFFSET_NR51)
#define REG_ADDR_SOUNDCNT_H  (REG_BASE + REG_OFFSET_SOUNDCNT_H)
#define REG_ADDR_SOUNDCNT_X  (REG_BASE + REG_OFFSET_SOUNDCNT_X)
#define REG_ADDR_NR52        (REG_BASE + REG_OFFSET_NR52)
#define REG_ADDR_SOUNDBIAS   (REG_BASE + REG_OFFSET_SOUNDBIAS)
#define REG_ADDR_SOUNDBIAS_L (REG_BASE + REG_OFFSET_SOUNDBIAS_L)
#define REG_ADDR_SOUNDBIAS_H (REG_BASE + REG_OFFSET_SOUNDBIAS_H)
#define REG_ADDR_WAVE_RAM0   (REG_BASE + REG_OFFSET_WAVE_RAM0)
#define REG_ADDR_WAVE_RAM1   (REG_BASE + REG_OFFSET_WAVE_RAM1)
#define REG_ADDR_WAVE_RAM2   (REG_BASE + REG_OFFSET_WAVE_RAM2)
#define REG_ADDR_WAVE_RAM3   (REG_BASE + REG_OFFSET_WAVE_RAM3)
#define REG_ADDR_FIFO_A      (REG_BASE + REG_OFFSET_FIFO_A)
#define REG_ADDR_FIFO_B      (REG_BASE + REG_OFFSET_FIFO_B)
#define REG_ADDR_DMA0        (REG_BASE + REG_OFFSET_DMA0)
#define REG_ADDR_DMA0SAD     (REG_BASE + REG_OFFSET_DMA0SAD)
#define REG_ADDR_DMA0DAD     (REG_BASE + REG_OFFSET_DMA0DAD)
#define REG_ADDR_DMA0CNT     (REG_BASE + REG_OFFSET_DMA0CNT)
#define REG_ADDR_DMA0CNT_L   (REG_BASE + REG_OFFSET_DMA0CNT_L)
#define REG_ADDR_DMA0CNT_H   (REG_BASE + REG_OFFSET_DMA0CNT_H)
#define REG_ADDR_DMA1        (REG_BASE + REG_OFFSET_DMA1)
#define REG_ADDR_DMA1SAD     (REG_BASE + REG_OFFSET_DMA1SAD)
#define REG_ADDR_DMA1DAD     (REG_BASE + REG_OFFSET_DMA1DAD)
#define REG_ADDR_DMA1CNT     (REG_BASE + REG_OFFSET_DMA1CNT)
#define REG_ADDR_DMA1CNT_L   (REG_BASE + REG_OFFSET_DMA1CNT_L)
#define REG_ADDR_DMA1CNT_H   (REG_BASE + REG_OFFSET_DMA1CNT_H)
#define REG_ADDR_DMA2        (REG_BASE + REG_OFFSET_DMA2)
#define REG_ADDR_DMA2SAD     (REG_BASE + REG_OFFSET_DMA2SAD)
#define REG_ADDR_DMA2DAD     (REG_BASE + REG_OFFSET_DMA2DAD)
#define REG_ADDR_DMA2CNT     (REG_BASE + REG_OFFSET_DMA2CNT)
#define REG_ADDR_DMA2CNT_L   (REG_BASE + REG_OFFSET_DMA2CNT_L)
#define REG_ADDR_DMA2CNT_H   (REG_BASE + REG_OFFSET_DMA2CNT_H)
#define REG_ADDR_DMA3        (REG_BASE + REG_OFFSET_DMA3)
#define REG_ADDR_DMA3SAD     (REG_BASE + REG_OFFSET_DMA3SAD)
#define REG_ADDR_DMA3DAD     (REG_BASE + REG_OFFSET_DMA3DAD)
#define REG_ADDR_DMA3CNT     (REG_BASE + REG_OFFSET_DMA3CNT)
#define REG_ADDR_DMA3CNT_L   (REG_BASE + REG_OFFSET_DMA3CNT_L)
#define REG_ADDR_DMA3CNT_H   (REG_BASE + REG_OFFSET_DMA3CNT_H)
#define REG_ADDR_TM0CNT      (REG_BASE + REG_OFFSET_TM0CNT)
#define REG_ADDR_TM0CNT_L    (REG_BASE + REG_OFFSET_TM0CNT_L)
#define REG_ADDR_TM0CNT_H    (REG_BASE + REG_OFFSET_TM0CNT_H)
#define REG_ADDR_TM1CNT      (REG_BASE + REG_OFFSET_TM1CNT)
#define REG_ADDR_TM1CNT_L    (REG_BASE + REG_OFFSET_TM1CNT_L)
#define REG_ADDR_TM1CNT_H    (REG_BASE + REG_OFFSET_TM1CNT_H)
#define REG_ADDR_TM2CNT      (REG_BASE + REG_OFFSET_TM2CNT)
#define REG_ADDR_TM2CNT_L    (REG_BASE + REG_OFFSET_TM2CNT_L)
#define REG_ADDR_TM2CNT_H    (REG_BASE + REG_OFFSET_TM2CNT_H)
#define REG_ADDR_TM3CNT      (REG_BASE + REG_OFFSET_TM3CNT)
#define REG_ADDR_TM3CNT_L    (REG_BASE + REG_OFFSET_TM3CNT_L)
#define REG_ADDR_TM3CNT_H    (REG_BASE + REG_OFFSET_TM3CNT_H)
#define REG_ADDR_SIOCNT      (REG_BASE + REG_OFFSET_SIOCNT)
#define REG_ADDR_SIODATA8    (REG_BASE + REG_OFFSET_SIODATA8)
#define REG_ADDR_SIODATA32   (REG_BASE + REG_OFFSET_SIODATA32)
#define REG_ADDR_SIOMULTI0   (REG_BASE + REG_OFFSET_SIOMULTI0)
#define REG_ADDR_SIOMULTI1   (REG_BASE + REG_OFFSET_SIOMULTI1)
#define REG_ADDR_SIOMULTI2   (REG_BASE + REG_OFFSET_SIOMULTI2)
#define REG_ADDR_SIOMULTI3   (REG_BASE + REG_OFFSET_SIOMULTI3)
#define REG_ADDR_SIOMLT_SEND (REG_BASE + REG_OFFSET_SIOMLT_SEND)
#define REG_ADDR_SIOMLT_RECV (REG_BASE + REG_OFFSET_SIOMLT_RECV)
#define REG_ADDR_KEYINPUT    (REG_BASE + REG_OFFSET_KEYINPUT)
#define REG_ADDR_KEYCNT      (REG_BASE + REG_OFFSET_KEYCNT)
#define REG_ADDR_RCNT        (REG_BASE + REG_OFFSET_RCNT)
#define REG_ADDR_IE          (REG_BASE + REG_OFFSET_IE)
#define REG_ADDR_IF          (REG_BASE + REG_OFFSET_IF)
#define REG_ADDR_WAITCNT     (REG_BASE + REG_OFFSET_WAITCNT)
#define REG_ADDR_IME         (REG_BASE + REG_OFFSET_IME)

#define REG_DISPCNT     (*(vu16*)REG_ADDR_DISPCNT)
#define REG_DISPSTAT    (*(vu16*)REG_ADDR_DISPSTAT)
#define REG_VCOUNT      (*(vu16*)REG_ADDR_VCOUNT)
#define REG_BG0CNT      (*(vu16*)REG_ADDR_BG0CNT)
#define REG_BG1CNT      (*(vu16*)REG_ADDR_BG1CNT)
#define REG_BG2CNT      (*(vu16*)REG_ADDR_BG2CNT)
#define REG_BG3CNT      (*(vu16*)REG_ADDR_BG3CNT)
#define REG_BG0HOFS     (*(vu16*)REG_ADDR_BG0HOFS)
#define REG_BG0VOFS     (*(vu16*)REG_ADDR_BG0VOFS)
#define REG_BG1HOFS     (*(vu16*)REG_ADDR_BG1HOFS)
#define REG_BG1VOFS     (*(vu16*)REG_ADDR_BG1VOFS)
#define REG_BG2HOFS     (*(vu16*)REG_ADDR_BG2HOFS)
#define REG_BG2VOFS     (*(vu16*)REG_ADDR_BG2VOFS)
#define REG_BG3HOFS     (*(vu16*)REG_ADDR_BG3HOFS)
#define REG_BG3VOFS     (*(vu16*)REG_ADDR_BG3VOFS)
#define REG_BG2PA       (*(vu16*)REG_ADDR_BG2PA)
#define REG_BG2PB       (*(vu16*)REG_ADDR_BG2PB)
#define REG_BG2PC       (*(vu16*)REG_ADDR_BG2PC)
#define REG_BG2PD       (*(vu16*)REG_ADDR_BG2PD)
#define REG_BG2X        (*(vu32*)REG_ADDR_BG2X)
#define REG_BG2Y        (*(vu32*)REG_ADDR_BG2Y)
#define REG_BG3PA       (*(vu16*)REG_ADDR_BG3PA)
#define REG_BG3PB       (*(vu16*)REG_ADDR_BG3PB)
#define REG_BG3PC       (*(vu16*)REG_ADDR_BG3PC)
#define REG_BG3PD       (*(vu16*)REG_ADDR_BG3PD)
#define REG_BG3X        (*(vu32*)REG_ADDR_BG3X)
#define REG_BG3Y        (*(vu32*)REG_ADDR_BG3Y)
#define REG_WIN0H       (*(vu16*)REG_ADDR_WIN0H)
#define REG_WIN1H       (*(vu16*)REG_ADDR_WIN1H)
#define REG_WIN0V       (*(vu16*)REG_ADDR_WIN0V)
#define REG_WIN1V       (*(vu16*)REG_ADDR_WIN1V)
#define REG_WININ       (*(vu16*)REG_ADDR_WININ)
#define REG_WINOUT      (*(vu16*)REG_ADDR_WINOUT)
#define REG_MOSAIC      (*(vu16*)REG_ADDR_MOSAIC)
#define REG_BLDCNT      (*(vu16*)REG_ADDR_BLDCNT)
#define REG_BLDALPHA    (*(vu16*)REG_ADDR_BLDALPHA)
#define REG_BLDY        (*(vu16*)REG_ADDR_BLDY)
#define REG_SOUND1CNT_L (*(vu16*)REG_ADDR_SOUND1CNT_L)
#define REG_NR10        (*(vu8*)REG_ADDR_NR10)
#define REG_SOUND1CNT_H (*(vu16*)REG_ADDR_SOUND1CNT_H)
#define REG_NR11        (*(vu8*)REG_ADDR_NR11)
#define REG_NR12        (*(vu8*)REG_ADDR_NR12)
#define REG_SOUND1CNT_X (*(vu16*)REG_ADDR_SOUND1CNT_X)
#define REG_NR13        (*(vu8*)REG_ADDR_NR13)
#define REG_NR14        (*(vu8*)REG_ADDR_NR14)
#define REG_SOUND2CNT_L (*(vu16*)REG_ADDR_SOUND2CNT_L)
#define REG_NR21        (*(vu8*)REG_ADDR_NR21)
#define REG_NR22        (*(vu8*)REG_ADDR_NR22)
#define REG_SOUND2CNT_H (*(vu16*)REG_ADDR_SOUND2CNT_H)
#define REG_NR23        (*(vu8*)REG_ADDR_NR23)
#define REG_NR24        (*(vu8*)REG_ADDR_NR24)
#define REG_SOUND3CNT_L (*(vu16*)REG_ADDR_SOUND3CNT_L)
#define REG_NR30        (*(vu8*)REG_ADDR_NR30)
#define REG_SOUND3CNT_H (*(vu16*)REG_ADDR_SOUND3CNT_H)
#define REG_NR31        (*(vu8*)REG_ADDR_NR31)
#define REG_NR32        (*(vu8*)REG_ADDR_NR32)
#define REG_SOUND3CNT_X (*(vu16*)REG_ADDR_SOUND3CNT_X)
#define REG_NR33        (*(vu8*)REG_ADDR_NR33)
#define REG_NR34        (*(vu8*)REG_ADDR_NR34)
#define REG_SOUND4CNT_L (*(vu16*)REG_ADDR_SOUND4CNT_L)
#define REG_NR41        (*(vu8*)REG_ADDR_NR41)
#define REG_NR42        (*(vu8*)REG_ADDR_NR42)
#define REG_SOUND4CNT_H (*(vu16*)REG_ADDR_SOUND4CNT_H)
#define REG_NR43        (*(vu8*)REG_ADDR_NR43)
#define REG_NR44        (*(vu8*)REG_ADDR_NR44)
#define REG_SOUNDCNT_L  (*(vu16*)REG_ADDR_SOUNDCNT_L)
#define REG_NR50        (*(vu8*)REG_ADDR_NR50)
#define REG_NR51        (*(vu8*)REG_ADDR_NR51)
#define REG_SOUNDCNT_H  (*(vu16*)REG_ADDR_SOUNDCNT_H)
#define REG_SOUNDCNT_X  (*(vu16*)REG_ADDR_SOUNDCNT_X)
#define REG_NR52        (*(vu8*)REG_ADDR_NR52)
#define REG_SOUNDBIAS   (*(vu16*)REG_ADDR_SOUNDBIAS)
#define REG_SOUNDBIAS_L (*(vu8*)REG_ADDR_SOUNDBIAS_L)
#define REG_SOUNDBIAS_H (*(vu8*)REG_ADDR_SOUNDBIAS_H)
#define REG_WAVE_RAM0   (*(vu32*)REG_ADDR_WAVE_RAM0)
#define REG_WAVE_RAM1   (*(vu32*)REG_ADDR_WAVE_RAM1)
#define REG_WAVE_RAM2   (*(vu32*)REG_ADDR_WAVE_RAM2)
#define REG_WAVE_RAM3   (*(vu32*)REG_ADDR_WAVE_RAM3)
#define REG_FIFO_A      (*(vu32*)REG_ADDR_FIFO_A)
#define REG_FIFO_B      (*(vu32*)REG_ADDR_FIFO_B)
#define REG_DMA0SAD     (*(vu32*)REG_ADDR_DMA0SAD)
#define REG_DMA0DAD     (*(vu32*)REG_ADDR_DMA0DAD)
#define REG_DMA0CNT     (*(vu32*)REG_ADDR_DMA0CNT)
#define REG_DMA0CNT_L   (*(vu16*)REG_ADDR_DMA0CNT_L)
#define REG_DMA0CNT_H   (*(vu16*)REG_ADDR_DMA0CNT_H)
#define REG_DMA1SAD     (*(vu32*)REG_ADDR_DMA1SAD)
#define REG_DMA1DAD     (*(vu32*)REG_ADDR_DMA1DAD)
#define REG_DMA1CNT     (*(vu32*)REG_ADDR_DMA1CNT)
#define REG_DMA1CNT_L   (*(vu16*)REG_ADDR_DMA1CNT_L)
#define REG_DMA1CNT_H   (*(vu16*)REG_ADDR_DMA1CNT_H)
#define REG_DMA2SAD     (*(vu32*)REG_ADDR_DMA2SAD)
#define REG_DMA2DAD     (*(vu32*)REG_ADDR_DMA2DAD)
#define REG_DMA2CNT     (*(vu32*)REG_ADDR_DMA2CNT)
#define REG_DMA2CNT_L   (*(vu16*)REG_ADDR_DMA2CNT_L)
#define REG_DMA2CNT_H   (*(vu16*)REG_ADDR_DMA2CNT_H)
#define REG_DMA3SAD     (*(vu32*)REG_ADDR_DMA3SAD)
#define REG_DMA3DAD     (*(vu32*)REG_ADDR_DMA3DAD)
#define REG_DMA3CNT     (*(vu32*)REG_ADDR_DMA3CNT)
#define REG_DMA3CNT_L   (*(vu16*)REG_ADDR_DMA3CNT_L)
#define REG_DMA3CNT_H   (*(vu16*)REG_ADDR_DMA3CNT_H)
#define REG_TM0CNT      (*(vu32*)REG_ADDR_TM0CNT)
#define REG_TM0CNT_L    (*(vu16*)REG_ADDR_TM0CNT_L)
#define REG_TM0CNT_H    (*(vu16*)REG_ADDR_TM0CNT_H)
#define REG_TM1CNT      (*(vu32*)REG_ADDR_TM1CNT)
#define REG_TM1CNT_L    (*(vu16*)REG_ADDR_TM1CNT_L)
#define REG_TM1CNT_H    (*(vu16*)REG_ADDR_TM1CNT_H)
#define REG_TM2CNT      (*(vu32*)REG_ADDR_TM2CNT)
#define REG_TM2CNT_L    (*(vu16*)REG_ADDR_TM2CNT_L)
#define REG_TM2CNT_H    (*(vu16*)REG_ADDR_TM2CNT_H)
#define REG_TM3CNT      (*(vu32*)REG_ADDR_TM3CNT)
#define REG_TM3CNT_L    (*(vu16*)REG_ADDR_TM3CNT_L)
#define REG_TM3CNT_H    (*(vu16*)REG_ADDR_TM3CNT_H)
#define REG_SIOCNT      (*(vu16*)REG_ADDR_SIOCNT)
#define REG_SIODATA8    (*(vu16*)REG_ADDR_SIODATA8)
#define REG_SIODATA32   (*(vu32*)REG_ADDR_SIODATA32)
#define REG_SIOMULTI0   (*(vu16*)REG_ADDR_SIOMULTI0)
#define REG_SIOMULTI1   (*(vu16*)REG_ADDR_SIOMULTI1)
#define REG_SIOMULTI2   (*(vu16*)REG_ADDR_SIOMULTI2)
#define REG_SIOMULTI3   (*(vu16*)REG_ADDR_SIOMULTI3)
#define REG_SIOMLT_SEND (*(vu16*)REG_ADDR_SIOMLT_SEND)
#define REG_SIOMLT_RECV (*(vu16*)REG_ADDR_SIOMLT_RECV)
#define REG_KEYINPUT    (*(vu16*)REG_ADDR_KEYINPUT)
#define REG_KEYCNT      (*(vu16*)REG_ADDR_KEYCNT)
#define REG_RCNT        (*(vu16*)REG_ADDR_RCNT)
#define REG_IE          (*(vu16*)REG_ADDR_IE)
#define REG_IF          (*(vu16*)REG_ADDR_IF)
#define REG_WAITCNT     (*(vu16*)REG_ADDR_WAITCNT)
#define REG_IME         (*(vu16*)REG_ADDR_IME)

#define REG_BGHOFS(n) (*(vu16*)(REG_ADDR_BG0HOFS + (n) * 4))

#define DMA_DEST_FIXED    0x0040
#define DMA_REPEAT        0x0200
#define DMA_32BIT         0x0400
#define DMA_START_SPECIAL 0x3000
#define DMA_ENABLE        0x8000

#define TIMER_ENABLE 0x0080

#define SOUND_MASTER_ENABLE   0x0080
#define SOUND_BIAS_RESOLUTION 0x4000

#endif
