# EU inventory for asset_gfx_gap_195 (Policy B). Leaf palettes identical to US.
version: eu
schema_version: 1
mvp_class: asset_gfx_gap_195
policy: B
baserom_code: B8CP
pack:
  id: asset_gfx_gap_195
  class: pack
  unit: asset_gfx_gap_195
  asm: asm/eu/asset_gfx_gap_195.s
  rom: { start: 0x09999B58, end: 0x09A9B9F8, size: 1056416 }
  extract_path: assets/eu/09999B58-09A9B9F8.bin
  sha256: 5207ef458b9091924c8e08f69536b0467d1986e4f0bede8c5c9c35c6d86c2b29
  path_mode_default: slice
leaves:
  - id: gUnk_09A3CC3C
    class: leaf_gfx
    format: palette
    start: 0x09A9A700
    end: 0x09A9A720
    size: 32
    sha1: bf51a0326246b202cd501f21e197bba1c9362018
    confidence: high
  - id: gUnk_09A3CC9C
    class: leaf_gfx
    format: palette
    start: 0x09A9A760
    end: 0x09A9A780
    size: 32
    sha1: 099b710e870ff122d89615001ad4be7a61026b21
    confidence: high
  - id: gUnk_09A3D07C
    class: leaf_gfx
    format: palette
    start: 0x09A9AB40
    end: 0x09A9AB60
    size: 32
    sha1: 48b9c6232707e66a4630e7451788b310a3a580e4
    confidence: high
  - id: gUnk_09A3D09C
    class: leaf_gfx
    format: palette
    start: 0x09A9AB60
    end: 0x09A9AB80
    size: 32
    sha1: 715e9a30cb6280f400388a34dd3ed031bcc3a033
    confidence: high
  - id: gUnk_09A3D0BC
    class: leaf_gfx
    format: palette
    start: 0x09A9AB80
    end: 0x09A9ABA0
    size: 32
    sha1: ac63649ee098c799ad4e03781c54bc1c959d906a
    confidence: high
  - id: gUnk_09A3D2DC
    class: leaf_gfx
    format: palette
    start: 0x09A9ADA0
    end: 0x09A9ADC0
    size: 32
    sha1: dc1c394483e795a1adf63ab5ba27dac00a0db865
    confidence: high
  - id: gUnk_09A3D57C
    class: leaf_gfx
    format: palette
    start: 0x09A9B040
    end: 0x09A9B060
    size: 32
    sha1: 0eeecb1d1e9b234d4623b091fd7f8bce60c6bc46
    confidence: high
  - id: gUnk_09A3D59C
    class: leaf_gfx
    format: palette
    start: 0x09A9B060
    end: 0x09A9B080
    size: 32
    sha1: e6bc11348dc0da8364f7adf8db1aa8253c4f99b2
    confidence: high
  - id: gUnk_09A3D5BC
    class: leaf_gfx
    format: palette
    start: 0x09A9B080
    end: 0x09A9B0A0
    size: 32
    sha1: ac63649ee098c799ad4e03781c54bc1c959d906a
    confidence: high
