version: 1
regions:
  us:
    named_assets:
    - name: gKeyboardTextUs_09035742
      address: '0x9035742'
      size: 32
      encoding: utf16le
    - name: gKeyboardTextUs_09035762
      address: '0x9035762'
      size: 24
      encoding: utf16le
    - name: gKeyboardTextUs_0903577A
      address: '0x903577a'
      size: 32
      encoding: utf16le
    - name: gKeyboardTextUs_0903579A
      address: '0x903579a'
      size: 24
      encoding: utf16le
    - name: gKeyboardTextUs_090357B2
      address: '0x90357b2'
      size: 32
      encoding: utf16le
    - name: gKeyboardTextUs_090357D2
      address: '0x90357d2'
      size: 32
      encoding: utf16le
    - name: gKeyboardTextUs_090357F2
      address: '0x90357f2'
      size: 22
      encoding: utf16le
  jp:
    named_assets:
    - name: gKeyboardTextJp_09008AE0
      address: '0x9008ae0'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008AC0
      address: '0x9008ac0'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008AA0
      address: '0x9008aa0'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008A88
      address: '0x9008a88'
      size: 21
      encoding: shift_jis
    - name: gKeyboardTextJp_09008A68
      address: '0x9008a68'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008A48
      address: '0x9008a48'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008A2C
      address: '0x9008a2c'
      size: 25
      encoding: shift_jis
    - name: gKeyboardTextJp_09008BB4
      address: '0x9008bb4'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B94
      address: '0x9008b94'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B74
      address: '0x9008b74'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B5C
      address: '0x9008b5c'
      size: 21
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B3C
      address: '0x9008b3c'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B1C
      address: '0x9008b1c'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008B00
      address: '0x9008b00'
      size: 25
      encoding: shift_jis
    - name: gKeyboardTextJp_09008C84
      address: '0x9008c84'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008C64
      address: '0x9008c64'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008C44
      address: '0x9008c44'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008C24
      address: '0x9008c24'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008C0C
      address: '0x9008c0c'
      size: 21
      encoding: shift_jis
    - name: gKeyboardTextJp_09008BEC
      address: '0x9008bec'
      size: 31
      encoding: shift_jis
    - name: gKeyboardTextJp_09008BD4
      address: '0x9008bd4'
      size: 21
      encoding: shift_jis
    - name: gUnkJp_090089B0
      address: '0x90089b0'
      size: 9
      encoding: shift_jis
    - name: gUnkJp_090089BC
      address: '0x90089bc'
      size: 9
      encoding: shift_jis
    - name: gUnkJp_090089C8
      address: '0x90089c8'
      size: 9
      encoding: shift_jis
  eu:
    named_assets:
    - name: gKeyboardTextEu_090CEA56
      address: '0x90cea56'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEA66
      address: '0x90cea66'
      size: 12
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEA72
      address: '0x90cea72'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEA82
      address: '0x90cea82'
      size: 12
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEA8E
      address: '0x90cea8e'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEA9E
      address: '0x90cea9e'
      size: 11
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAA9
      address: '0x90ceaa9'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAB9
      address: '0x90ceab9'
      size: 11
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAC4
      address: '0x90ceac4'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAD4
      address: '0x90cead4'
      size: 11
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEADF
      address: '0x90ceadf'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAEF
      address: '0x90ceaef'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEAFF
      address: '0x90ceaff'
      size: 6
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEB05
      address: '0x90ceb05'
      size: 16
      encoding: singlebyte
    - name: gKeyboardTextEu_090CEB15
      address: '0x90ceb15'
      size: 6
      encoding: singlebyte
