version: 1
regions:
  us:
    named_assets:
    - name: gDebugMenuTextUs_0984B648
      address: '0x984b648'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B634
      address: '0x984b634'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B620
      address: '0x984b620'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B60C
      address: '0x984b60c'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B5F8
      address: '0x984b5f8'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B71C
      address: '0x984b71c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B70C
      address: '0x984b70c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6FC
      address: '0x984b6fc'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6EC
      address: '0x984b6ec'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6DC
      address: '0x984b6dc'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6CC
      address: '0x984b6cc'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6BC
      address: '0x984b6bc'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B6AC
      address: '0x984b6ac'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B69C
      address: '0x984b69c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B68C
      address: '0x984b68c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B67C
      address: '0x984b67c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B66C
      address: '0x984b66c'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextUs_0984B65C
      address: '0x984b65c'
      size: 15
      encoding: shift_jis
  jp:
    named_assets:
    - name: gDebugMenuTextJp_0980015C
      address: '0x980015c'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800148
      address: '0x9800148'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800134
      address: '0x9800134'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800120
      address: '0x9800120'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextJp_0980010C
      address: '0x980010c'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800230
      address: '0x9800230'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800220
      address: '0x9800220'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800210
      address: '0x9800210'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800200
      address: '0x9800200'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001F0
      address: '0x98001f0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001E0
      address: '0x98001e0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001D0
      address: '0x98001d0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001C0
      address: '0x98001c0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001B0
      address: '0x98001b0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_098001A0
      address: '0x98001a0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800190
      address: '0x9800190'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800180
      address: '0x9800180'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextJp_09800170
      address: '0x9800170'
      size: 15
      encoding: shift_jis
  eu:
    named_assets:
    - name: gDebugMenuTextEu_0982801C
      address: '0x982801c'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828008
      address: '0x9828008'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextEu_09827FF4
      address: '0x9827ff4'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextEu_09827FE0
      address: '0x9827fe0'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextEu_09827FCC
      address: '0x9827fcc'
      size: 17
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280F0
      address: '0x98280f0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280E0
      address: '0x98280e0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280D0
      address: '0x98280d0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280C0
      address: '0x98280c0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280B0
      address: '0x98280b0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_098280A0
      address: '0x98280a0'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828090
      address: '0x9828090'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828080
      address: '0x9828080'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828070
      address: '0x9828070'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828060
      address: '0x9828060'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828050
      address: '0x9828050'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828040
      address: '0x9828040'
      size: 15
      encoding: shift_jis
    - name: gDebugMenuTextEu_09828030
      address: '0x9828030'
      size: 15
      encoding: shift_jis
