version: 1
regions:
  us:
    named_assets:
    - name: gMapWorldNameTextUs_0815B57A
      address: '0x815b57a'
      size: 44
      encoding: utf16le
  jp:
    named_assets:
    - name: gMapWorldNameTextJp_0814F2E0
      address: '0x814f2e0'
      size: 17
      encoding: shift_jis
