group: jiminy_journal
types:
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: jiminy_journal_tiles.s
    start: 0x08EE4A64
    end: 0x08EEE384
  - name: jiminy_journal_maps.s
    start: 0x08F5E384
    end: 0x08F68384
  - name: jiminy_journal_palettes.s
    start: 0x08F6DD64
    end: 0x08F6E184
  - name: jiminy_journal_frames.s
    start: 0x08C69C04
    end: 0x08C6AF80
  jp:
  - name: jiminy_journal_tiles.s
    start: 0x08ED804C
    end: 0x08EE188C
  - name: jiminy_journal_maps.s
    start: 0x08F5188C
    end: 0x08F5B88C
  - name: jiminy_journal_palettes.s
    start: 0x08F6126C
    end: 0x08F6168C
  - name: jiminy_journal_frames.s
    start: 0x08C5D1EC
    end: 0x08C5E568
  eu:
  - name: jiminy_journal_tiles.s
    start: 0x08EF0F7C
    end: 0x08EFE8DC
  - name: jiminy_journal_maps.s
    start: 0x08F5A8DC
    end: 0x08F648DC
  - name: jiminy_journal_palettes.s
    start: 0x08F6A2BC
    end: 0x08F6A6DC
  - name: jiminy_journal_frames.s
    start: 0x08C99BB4
    end: 0x08C9C97C
entries:
- name: gUnk_08EE4A64
  format: tiles4
  us:
    address: 0x08EE4A64
    size: 11904
  jp:
    address: 0x08ED804C
    size: 11680
  eu:
    address: 0x08EF0F7C
    size: 11904
- name: gUnk_08EE78E4
  format: tiles4
  width: 2
  us:
    address: 0x08EE78E4
    size: 320
  jp:
    address: 0x08EDADEC
    size: 320
  eu:
    address: 0x08EF7E3C
    size: 320
- name: gUnk_08EE7A24
  format: tiles4
  us:
    address: 0x08EE7A24
    size: 5216
  jp:
    address: 0x08EDAF2C
    size: 5216
  eu:
    address: 0x08EF7F7C
    size: 5216
- name: gUnk_08EE8E84
  format: tiles4
  us:
    address: 0x08EE8E84
    size: 3488
  jp:
    address: 0x08EDC38C
    size: 3488
  eu:
    address: 0x08EF93DC
    size: 3488
- name: gUnk_08EE9C24
  format: tiles4
  us:
    address: 0x08EE9C24
    size: 4384
  jp:
    address: 0x08EDD12C
    size: 4384
  eu:
    address: 0x08EFA17C
    size: 4384
- name: gUnk_08EEAD44
  format: tiles4
  width: 8
  us:
    address: 0x08EEAD44
    size: 4864
  jp:
    address: 0x08EDE24C
    size: 4864
  eu:
    address: 0x08EFB29C
    size: 4864
- name: gUnk_08EEC044
  format: tiles4
  us:
    address: 0x08EEC044
    size: 3744
  jp:
    address: 0x08EDF54C
    size: 3744
  eu:
    address: 0x08EFC59C
    size: 3744
- name: gUnk_08EECEE4
  format: tiles4
  us:
    address: 0x08EECEE4
    size: 5280
  jp:
    address: 0x08EE03EC
    size: 5280
  eu:
    address: 0x08EFD43C
    size: 5280
- name: gUnkEu_08EF3DFC
  format: raw
  eu:
    address: 0x08EF3DFC
    size: 224
- name: gUnkEu_08EF3EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF3EDC
    size: 4096
- name: gUnkEu_08EF4EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF4EDC
    size: 4096
- name: gUnkEu_08EF5EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF5EDC
    size: 4096
- name: gUnkEu_08EF6EDC
  format: tiles4
  eu:
    address: 0x08EF6EDC
    size: 3936
- name: gUnk_08F5E384
  format: tilemap
  us:
    address: 0x08F5E384
    size: 2048
  jp:
    address: 0x08F5188C
    size: 2048
  eu:
    address: 0x08F5D8DC
    size: 2048
- name: gUnk_08F5EB84
  format: tilemap
  us:
    address: 0x08F5EB84
    size: 2048
  jp:
    address: 0x08F5208C
    size: 2048
  eu:
    address: 0x08F5E0DC
    size: 2048
- name: gUnk_08F5F384
  format: tilemap
  us:
    address: 0x08F5F384
    size: 2048
  jp:
    address: 0x08F5288C
    size: 2048
  eu:
    address: 0x08F5E8DC
    size: 2048
- name: gUnk_08F5FB84
  format: tilemap
  us:
    address: 0x08F5FB84
    size: 2048
  jp:
    address: 0x08F5308C
    size: 2048
  eu:
    address: 0x08F5F0DC
    size: 2048
- name: gUnk_08F60384
  format: tilemap
  us:
    address: 0x08F60384
    size: 2048
  jp:
    address: 0x08F5388C
    size: 2048
  eu:
    address: 0x08F610DC
    size: 2048
- name: gUnk_08F60B84
  format: tilemap
  us:
    address: 0x08F60B84
    size: 2048
  jp:
    address: 0x08F5408C
    size: 2048
  eu:
    address: 0x08F5B8DC
    size: 2048
- name: gUnk_08F61384
  format: tilemap
  us:
    address: 0x08F61384
    size: 2048
  jp:
    address: 0x08F5488C
    size: 2048
  eu:
    address: 0x08F608DC
    size: 2048
- name: gUnk_08F61B84
  format: tilemap
  us:
    address: 0x08F61B84
    size: 2048
  jp:
    address: 0x08F5508C
    size: 2048
  eu:
    address: 0x08F5C0DC
    size: 2048
- name: gUnk_08F62384
  format: tilemap
  us:
    address: 0x08F62384
    size: 2048
  jp:
    address: 0x08F5588C
    size: 2048
  eu:
    address: 0x08F5C8DC
    size: 2048
- name: gUnk_08F62B84
  format: tilemap
  us:
    address: 0x08F62B84
    size: 2048
  jp:
    address: 0x08F5608C
    size: 2048
  eu:
    address: 0x08F5D0DC
    size: 2048
- name: gUnk_08F63384
  format: tilemap
  us:
    address: 0x08F63384
    size: 2048
  jp:
    address: 0x08F5688C
    size: 2048
  eu:
    address: 0x08F5F8DC
    size: 2048
- name: gUnk_08F63B84
  format: tilemap
  us:
    address: 0x08F63B84
    size: 2048
  jp:
    address: 0x08F5708C
    size: 2048
  eu:
    address: 0x08F600DC
    size: 2048
- name: gUnk_08F64384
  format: tilemap
  us:
    address: 0x08F64384
    size: 2048
  jp:
    address: 0x08F5788C
    size: 2048
  eu:
    address: 0x08F5A8DC
    size: 2048
- name: gUnk_08F64B84
  format: tilemap
  us:
    address: 0x08F64B84
    size: 2048
  jp:
    address: 0x08F5808C
    size: 2048
  eu:
    address: 0x08F5B0DC
    size: 2048
- name: gUnk_08F65384
  format: tilemap
  us:
    address: 0x08F65384
    size: 2048
  jp:
    address: 0x08F5888C
    size: 2048
  eu:
    address: 0x08F618DC
    size: 2048
- name: gUnk_08F65B84
  format: tilemap
  us:
    address: 0x08F65B84
    size: 2048
  jp:
    address: 0x08F5908C
    size: 2048
  eu:
    address: 0x08F620DC
    size: 2048
- name: gUnk_08F66384
  format: tilemap
  us:
    address: 0x08F66384
    size: 2048
  jp:
    address: 0x08F5988C
    size: 2048
  eu:
    address: 0x08F628DC
    size: 2048
- name: gUnk_08F66B84
  format: tilemap
  us:
    address: 0x08F66B84
    size: 2048
  jp:
    address: 0x08F5A08C
    size: 2048
  eu:
    address: 0x08F630DC
    size: 2048
- name: gUnk_08F67384
  format: tilemap
  us:
    address: 0x08F67384
    size: 2048
  jp:
    address: 0x08F5A88C
    size: 2048
  eu:
    address: 0x08F638DC
    size: 2048
- name: gUnk_08F67B84
  format: tilemap
  us:
    address: 0x08F67B84
    size: 2048
  jp:
    address: 0x08F5B08C
    size: 2048
  eu:
    address: 0x08F640DC
    size: 2048
- name: gUnk_08F6DD64
  format: palette
  us:
    address: 0x08F6DD64
    size: 32
  jp:
    address: 0x08F6126C
    size: 32
  eu:
    address: 0x08F6A2BC
    size: 32
- name: gUnk_08F6DD84
  format: palette
  us:
    address: 0x08F6DD84
    size: 32
  jp:
    address: 0x08F6128C
    size: 32
  eu:
    address: 0x08F6A2DC
    size: 32
- name: gUnk_08F6DDA4
  format: palette
  us:
    address: 0x08F6DDA4
    size: 32
  jp:
    address: 0x08F612AC
    size: 32
  eu:
    address: 0x08F6A2FC
    size: 32
- name: gUnk_08F6DDC4
  format: palette
  us:
    address: 0x08F6DDC4
    size: 32
  jp:
    address: 0x08F612CC
    size: 32
  eu:
    address: 0x08F6A31C
    size: 32
- name: gUnk_08F6DDE4
  format: palette
  us:
    address: 0x08F6DDE4
    size: 32
  jp:
    address: 0x08F612EC
    size: 32
  eu:
    address: 0x08F6A33C
    size: 32
- name: gUnk_08F6DE04
  format: palette
  us:
    address: 0x08F6DE04
    size: 32
  jp:
    address: 0x08F6130C
    size: 32
  eu:
    address: 0x08F6A35C
    size: 32
- name: gUnk_08F6DE24
  format: palette
  us:
    address: 0x08F6DE24
    size: 512
  jp:
    address: 0x08F6132C
    size: 512
  eu:
    address: 0x08F6A37C
    size: 512
- name: gUnk_08F6E024
  format: palette
  us:
    address: 0x08F6E024
    size: 32
  jp:
    address: 0x08F6152C
    size: 32
  eu:
    address: 0x08F6A57C
    size: 32
- name: gUnk_08F6E044
  format: palette
  us:
    address: 0x08F6E044
    size: 32
  jp:
    address: 0x08F6154C
    size: 32
  eu:
    address: 0x08F6A59C
    size: 32
- name: gUnk_08F6E064
  format: palette
  us:
    address: 0x08F6E064
    size: 64
  jp:
    address: 0x08F6156C
    size: 64
  eu:
    address: 0x08F6A5BC
    size: 64
- name: gUnk_08F6E0A4
  format: palette
  us:
    address: 0x08F6E0A4
    size: 96
  jp:
    address: 0x08F615AC
    size: 96
  eu:
    address: 0x08F6A5FC
    size: 96
- name: gUnk_08F6E104
  format: palette
  us:
    address: 0x08F6E104
    size: 32
  jp:
    address: 0x08F6160C
    size: 32
  eu:
    address: 0x08F6A65C
    size: 32
- name: gUnk_08F6E124
  format: palette
  us:
    address: 0x08F6E124
    size: 64
  jp:
    address: 0x08F6162C
    size: 64
  eu:
    address: 0x08F6A67C
    size: 64
- name: gUnk_08F6E164
  format: palette
  us:
    address: 0x08F6E164
    size: 32
  jp:
    address: 0x08F6166C
    size: 32
  eu:
    address: 0x08F6A6BC
    size: 32
- name: gUnk_08C69C04
  record: Sprite
  oam:
  - [16384, 32768, 0]
  - [16384, 32800, 8]
  - [16384, 32832, 16]
  - [32768, 96, 24]
  us:
    address: 0x08C69C04
  jp:
    address: 0x08C5D1EC
  eu:
    address: 0x08C99BB4
- name: gUnk_08C69C20
  record: Sprite
  oam:
  - [16384, 16768, 26]
  - [16384, 16800, 26]
  - [16384, 16832, 26]
  - [16384, 16864, 26]
  - [16384, 16384, 26]
  - [16384, 16416, 26]
  - [16384, 16448, 26]
  - [16384, 96, 30]
  us:
    address: 0x08C69C20
  jp:
    address: 0x08C5D208
  eu:
    address: 0x08C99BD0
- name: gUnk_08C69C54
  record: Sprite
  oam:
  - [16384, 16768, 32]
  - [16384, 16800, 36]
  - [16384, 16832, 40]
  - [0, 480, 44]
  - [0, 104, 45]
  us:
    address: 0x08C69C54
  jp:
    address: 0x08C5D23C
  eu:
    address: 0x08C99C04
- name: gUnk_08C69C76
  record: Sprite
  oam:
  - [16384, 32768, 46]
  - [16384, 32800, 54]
  - [0, 16448, 62]
  - [32768, 80, 66]
  us:
    address: 0x08C69C76
  jp:
    address: 0x08C5D25E
  eu:
    address: 0x08C99C26
- name: gUnk_08C69C92
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C69C92
  jp:
    address: 0x08C5D27A
  eu:
    address: 0x08C99C42
- name: gUnk_08C69C9C
  format: tiles4
  width: 4
  us:
    address: 0x08C69C9C
    size: 2176
  jp:
    address: 0x08C5D284
    size: 2176
  eu:
    address: 0x08C99C4C
    size: 2176
- name: gUnkEu_08C9A4CC
  record: Sprite
  oam:
  - [16384, 32768, 0]
  - [16384, 32800, 8]
  - [32768, 64, 16]
  eu:
    address: 0x08C9A4CC
- name: gUnkEu_08C9A4E2
  record: Sprite
  oam:
  - [16384, 16768, 18]
  - [16384, 16800, 18]
  - [16384, 16832, 18]
  - [16384, 16864, 18]
  - [16384, 16384, 18]
  - [16384, 16416, 18]
  - [16384, 16448, 18]
  - [16384, 96, 22]
  eu:
    address: 0x08C9A4E2
- name: gUnkEu_08C9A516
  record: Sprite
  oam:
  - [16384, 16768, 24]
  - [16384, 16800, 28]
  - [16384, 16832, 32]
  - [0, 480, 36]
  - [0, 104, 37]
  eu:
    address: 0x08C9A516
- name: gUnkEu_08C9A538
  record: Sprite
  oam:
  - [16384, 32768, 38]
  - [16384, 32800, 46]
  - [0, 16448, 54]
  - [32768, 80, 58]
  eu:
    address: 0x08C9A538
- name: gUnkEu_08C9A554
  record: Sprite
  oam:
  - [16384, 32768, 60]
  - [16384, 32800, 68]
  eu:
    address: 0x08C9A554
- name: gUnkEu_08C9A564
  record: Sprite
  oam:
  - [16384, 32768, 76]
  - [16384, 32800, 84]
  - [16384, 32832, 92]
  eu:
    address: 0x08C9A564
- name: gUnkEu_08C9A57A
  record: Sprite
  oam:
  - [16384, 32768, 100]
  - [16384, 32800, 108]
  - [0, 16448, 116]
  eu:
    address: 0x08C9A57A
- name: gUnkEu_08C9A590
  record: Sprite
  oam:
  - [16384, 32768, 120]
  - [16384, 32800, 128]
  - [32768, 64, 136]
  eu:
    address: 0x08C9A590
- name: gUnkEu_08C9A5A6
  record: Sprite
  oam:
  - [16384, 32768, 138]
  - [16384, 32800, 146]
  - [16384, 32832, 154]
  - [32768, 96, 162]
  eu:
    address: 0x08C9A5A6
- name: gUnkEu_08C9A5C2
  record: Sprite
  oam:
  - [16384, 32768, 164]
  - [16384, 32800, 172]
  - [16384, 32832, 180]
  eu:
    address: 0x08C9A5C2
- name: gUnkEu_08C9A5D8
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  eu:
    address: 0x08C9A5D8
- name: gUnkEu_08C9A5E2
  format: tiles4
  width: 4
  eu:
    address: 0x08C9A5E2
    size: 6016
- name: gUnk_08C6A51C
  record: Sprite
  oam:
  - [0, 0, 0]
  us:
    address: 0x08C6A51C
  jp:
    address: 0x08C5DB04
  eu:
    address: 0x08C9C100
- name: gUnk_08C6A526
  record: Sprite
  oam:
  - [0, 0, 1]
  us:
    address: 0x08C6A526
  jp:
    address: 0x08C5DB0E
  eu:
    address: 0x08C9C10A
- name: gUnk_08C6A530
  record: Sprite
  oam:
  - [0, 16384, 2]
  us:
    address: 0x08C6A530
  jp:
    address: 0x08C5DB18
  eu:
    address: 0x08C9C114
- name: gUnk_08C6A53A
  record: Sprite
  oam:
  - [0, 16384, 6]
  us:
    address: 0x08C6A53A
  jp:
    address: 0x08C5DB22
  eu:
    address: 0x08C9C11E
- name: gUnk_08C6A544
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C6A544
  jp:
    address: 0x08C5DB2C
  eu:
    address: 0x08C9C128
- name: gUnk_08C6A54E
  format: tiles4
  width: 2
  us:
    address: 0x08C6A54E
    size: 320
  jp:
    address: 0x08C5DB36
    size: 320
  eu:
    address: 0x08C9C132
    size: 320
- name: gUnk_08C6A690
  record: Sprite
  align: 4
  oam:
  - [16384, 33272, 0]
  us:
    address: 0x08C6A690
  jp:
    address: 0x08C5DC78
  eu:
    address: 0x08C9BD64
- name: gUnk_08C6A69A
  record: Sprite
  oam:
  - [0, 16384, 8]
  us:
    address: 0x08C6A69A
  jp:
    address: 0x08C5DC82
  eu:
    address: 0x08C9BD6E
- name: gUnk_08C6A6A4
  record: Sprite
  oam:
  - [16384, 0, 12]
  us:
    address: 0x08C6A6A4
  jp:
    address: 0x08C5DC8C
  eu:
    address: 0x08C9BD78
- name: gUnkEu_08C9BD82
  record: Sprite
  oam:
  - [16384, 16882, 14]
  eu:
    address: 0x08C9BD82
- name: gUnkEu_08C9BD8C
  record: Sprite
  oam:
  - [16384, 506, 18]
  - [0, 10, 20]
  eu:
    address: 0x08C9BD8C
- name: gUnkEu_08C9BD9C
  record: Sprite
  oam:
  - [16384, 506, 21]
  - [0, 10, 23]
  eu:
    address: 0x08C9BD9C
- name: gUnkEu_08C9BDAC
  record: Sprite
  oam:
  - [16384, 0, 24]
  eu:
    address: 0x08C9BDAC
- name: gUnk_08C6A6AE
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C6A6AE
  jp:
    address: 0x08C5DC96
  eu:
    address: 0x08C9BDB6
- name: gUnk_08C6A6B8
  format: tiles4
  width: 2
  us:
    address: 0x08C6A6B8
    size: 448
  jp:
    address: 0x08C5DCA0
    size: 448
  eu:
    address: 0x08C9BDC0
    size: 832
- name: gUnk_08C6A878
  record: Sprite
  align: 4
  oam:
  - [16384, 0, 0]
  us:
    address: 0x08C6A878
  jp:
    address: 0x08C5DE60
  eu:
    address: 0x08C9C274
- name: gUnk_08C6A882
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C6A882
  jp:
    address: 0x08C5DE6A
  eu:
    address: 0x08C9C27E
- name: gUnk_08C6A88C
  format: tiles4
  width: 2
  us:
    address: 0x08C6A88C
    size: 64
  jp:
    address: 0x08C5DE74
    size: 64
  eu:
    address: 0x08C9C288
    size: 64
- name: gUnk_08C6A8CC
  record: Sprite
  oam:
  - [0, 20488, 0]
  - [32768, 4096, 4]
  - [16400, 4097, 6]
  us:
    address: 0x08C6A8CC
  jp:
    address: 0x08C5DEB4
  eu:
    address: 0x08C9C2C8
- name: gUnk_08C6A8E2
  record: Sprite
  oam:
  - [0, 20487, 0]
  - [32768, 4607, 4]
  - [16400, 4096, 6]
  us:
    address: 0x08C6A8E2
  jp:
    address: 0x08C5DECA
  eu:
    address: 0x08C9C2DE
- name: gUnk_08C6A8F8
  record: Sprite
  oam:
  - [0, 20486, 0]
  - [32768, 4606, 4]
  - [16400, 4607, 6]
  us:
    address: 0x08C6A8F8
  jp:
    address: 0x08C5DEE0
  eu:
    address: 0x08C9C2F4
- name: gUnk_08C6A90E
  record: Sprite
  oam:
  - [0, 20485, 0]
  - [32768, 4605, 4]
  - [16400, 4606, 6]
  us:
    address: 0x08C6A90E
  jp:
    address: 0x08C5DEF6
  eu:
    address: 0x08C9C30A
- name: gUnk_08C6A924
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames: []
  declare: false
  us:
    address: 0x08C6A924
  jp:
    address: 0x08C5DF0C
  eu:
    address: 0x08C9C320
- name: gUnk_08C6A92A
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames: []
  declare: false
  us:
    address: 0x08C6A92A
  jp:
    address: 0x08C5DF12
  eu:
    address: 0x08C9C326
- name: gUnk_08C6A930
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  - [1, 3]
  - [2, 3]
  - [3, 4]
  - [2, 3]
  - [1, 3]
  declare: false
  us:
    address: 0x08C6A930
  jp:
    address: 0x08C5DF18
  eu:
    address: 0x08C9C32C
- name: gUnk_08C6A94E
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C6A94E
  jp:
    address: 0x08C5DF36
  eu:
    address: 0x08C9C34A
- name: gUnk_08C6A958
  format: tiles4
  width: 8
  us:
    address: 0x08C6A958
    size: 256
  jp:
    address: 0x08C5DF40
    size: 256
  eu:
    address: 0x08C9C354
    size: 256
- name: gUnk_08C6AA58
  record: Sprite
  oam:
  - [16624, 16864, 0]
  - [238, 32768, 4]
  - [16614, 16384, 20]
  - [248, 33248, 24]
  us:
    address: 0x08C6AA58
  jp:
    address: 0x08C5E040
  eu:
    address: 0x08C9C454
- name: gUnk_08C6AA74
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  us:
    address: 0x08C6AA74
  jp:
    address: 0x08C5E05C
  eu:
    address: 0x08C9C470
- name: gUnk_08C6AA7E
  format: tiles4
  width: 8
  us:
    address: 0x08C6AA7E
    size: 1280
  jp:
    address: 0x08C5E066
    size: 1280
  eu:
    address: 0x08C9C47A
    size: 1280
