group: jiminy_journal
types:
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: jiminy_journal_tiles.s
    start: 0x08EE4A64
    end: 0x08EEE384
  - name: jiminy_journal_maps.s
    start: 0x08F5E384
    end: 0x08F68384
  - name: jiminy_journal_palettes.s
    start: 0x08F6DD64
    end: 0x08F6E184
  - name: jiminy_journal_frames.s
    start: 0x08C69C04
    end: 0x08C6AF80
  jp:
  - name: jiminy_journal_tiles.s
    start: 0x08ED804C
    end: 0x08EE188C
  - name: jiminy_journal_maps.s
    start: 0x08F5188C
    end: 0x08F5B88C
  - name: jiminy_journal_palettes.s
    start: 0x08F6126C
    end: 0x08F6168C
  - name: jiminy_journal_frames.s
    start: 0x08C5D1EC
    end: 0x08C5E568
  eu:
  - name: jiminy_journal_tiles.s
    start: 0x08EF0F7C
    end: 0x08EFE8DC
  - name: jiminy_journal_maps.s
    start: 0x08F5A8DC
    end: 0x08F648DC
  - name: jiminy_journal_palettes.s
    start: 0x08F6A2BC
    end: 0x08F6A6DC
  - name: jiminy_journal_frames.s
    start: 0x08C99BB4
    end: 0x08C9C97C
entries:
- name: gUnk_08EE4A64
  format: tiles4
  us:
    address: 0x08EE4A64
    size: 11904
  jp:
    address: 0x08ED804C
    size: 11680
  eu:
    address: 0x08EF0F7C
    size: 11904
- name: gUnk_08EE78E4
  format: tiles4
  width: 2
  us:
    address: 0x08EE78E4
    size: 320
  jp:
    address: 0x08EDADEC
    size: 320
  eu:
    address: 0x08EF7E3C
    size: 320
- name: gUnk_08EE7A24
  format: tiles4
  us:
    address: 0x08EE7A24
    size: 5216
  jp:
    address: 0x08EDAF2C
    size: 5216
  eu:
    address: 0x08EF7F7C
    size: 5216
- name: gUnk_08EE8E84
  format: tiles4
  us:
    address: 0x08EE8E84
    size: 3488
  jp:
    address: 0x08EDC38C
    size: 3488
  eu:
    address: 0x08EF93DC
    size: 3488
- name: gUnk_08EE9C24
  format: tiles4
  us:
    address: 0x08EE9C24
    size: 4384
  jp:
    address: 0x08EDD12C
    size: 4384
  eu:
    address: 0x08EFA17C
    size: 4384
- name: gUnk_08EEAD44
  format: tiles4
  width: 8
  us:
    address: 0x08EEAD44
    size: 4864
  jp:
    address: 0x08EDE24C
    size: 4864
  eu:
    address: 0x08EFB29C
    size: 4864
- name: gUnk_08EEC044
  format: tiles4
  us:
    address: 0x08EEC044
    size: 3744
  jp:
    address: 0x08EDF54C
    size: 3744
  eu:
    address: 0x08EFC59C
    size: 3744
- name: gUnk_08EECEE4
  format: tiles4
  us:
    address: 0x08EECEE4
    size: 5280
  jp:
    address: 0x08EE03EC
    size: 5280
  eu:
    address: 0x08EFD43C
    size: 5280
- name: gUnkEu_08EF3DFC
  format: raw
  eu:
    address: 0x08EF3DFC
    size: 224
- name: gUnkEu_08EF3EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF3EDC
    size: 4096
- name: gUnkEu_08EF4EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF4EDC
    size: 4096
- name: gUnkEu_08EF5EDC
  format: tiles4
  width: 32
  eu:
    address: 0x08EF5EDC
    size: 4096
- name: gUnkEu_08EF6EDC
  format: tiles4
  eu:
    address: 0x08EF6EDC
    size: 3936
- name: gUnk_08F5E384
  format: tilemap
  us:
    address: 0x08F5E384
    size: 2048
  jp:
    address: 0x08F5188C
    size: 2048
  eu:
    address: 0x08F5D8DC
    size: 2048
- name: gUnk_08F5EB84
  format: tilemap
  us:
    address: 0x08F5EB84
    size: 2048
  jp:
    address: 0x08F5208C
    size: 2048
  eu:
    address: 0x08F5E0DC
    size: 2048
- name: gUnk_08F5F384
  format: tilemap
  us:
    address: 0x08F5F384
    size: 2048
  jp:
    address: 0x08F5288C
    size: 2048
  eu:
    address: 0x08F5E8DC
    size: 2048
- name: gUnk_08F5FB84
  format: tilemap
  us:
    address: 0x08F5FB84
    size: 2048
  jp:
    address: 0x08F5308C
    size: 2048
  eu:
    address: 0x08F5F0DC
    size: 2048
- name: gUnk_08F60384
  format: tilemap
  us:
    address: 0x08F60384
    size: 2048
  jp:
    address: 0x08F5388C
    size: 2048
  eu:
    address: 0x08F610DC
    size: 2048
- name: gUnk_08F60B84
  format: tilemap
  us:
    address: 0x08F60B84
    size: 2048
  jp:
    address: 0x08F5408C
    size: 2048
  eu:
    address: 0x08F5B8DC
    size: 2048
- name: gUnk_08F61384
  format: tilemap
  us:
    address: 0x08F61384
    size: 2048
  jp:
    address: 0x08F5488C
    size: 2048
  eu:
    address: 0x08F608DC
    size: 2048
- name: gUnk_08F61B84
  format: tilemap
  us:
    address: 0x08F61B84
    size: 2048
  jp:
    address: 0x08F5508C
    size: 2048
  eu:
    address: 0x08F5C0DC
    size: 2048
- name: gUnk_08F62384
  format: tilemap
  us:
    address: 0x08F62384
    size: 2048
  jp:
    address: 0x08F5588C
    size: 2048
  eu:
    address: 0x08F5C8DC
    size: 2048
- name: gUnk_08F62B84
  format: tilemap
  us:
    address: 0x08F62B84
    size: 2048
  jp:
    address: 0x08F5608C
    size: 2048
  eu:
    address: 0x08F5D0DC
    size: 2048
- name: gUnk_08F63384
  format: tilemap
  us:
    address: 0x08F63384
    size: 2048
  jp:
    address: 0x08F5688C
    size: 2048
  eu:
    address: 0x08F5F8DC
    size: 2048
- name: gUnk_08F63B84
  format: tilemap
  us:
    address: 0x08F63B84
    size: 2048
  jp:
    address: 0x08F5708C
    size: 2048
  eu:
    address: 0x08F600DC
    size: 2048
- name: gUnk_08F64384
  format: tilemap
  us:
    address: 0x08F64384
    size: 2048
  jp:
    address: 0x08F5788C
    size: 2048
  eu:
    address: 0x08F5A8DC
    size: 2048
- name: gUnk_08F64B84
  format: tilemap
  us:
    address: 0x08F64B84
    size: 2048
  jp:
    address: 0x08F5808C
    size: 2048
  eu:
    address: 0x08F5B0DC
    size: 2048
- name: gUnk_08F65384
  format: tilemap
  us:
    address: 0x08F65384
    size: 2048
  jp:
    address: 0x08F5888C
    size: 2048
  eu:
    address: 0x08F618DC
    size: 2048
- name: gUnk_08F65B84
  format: tilemap
  us:
    address: 0x08F65B84
    size: 2048
  jp:
    address: 0x08F5908C
    size: 2048
  eu:
    address: 0x08F620DC
    size: 2048
- name: gUnk_08F66384
  format: tilemap
  us:
    address: 0x08F66384
    size: 2048
  jp:
    address: 0x08F5988C
    size: 2048
  eu:
    address: 0x08F628DC
    size: 2048
- name: gUnk_08F66B84
  format: tilemap
  us:
    address: 0x08F66B84
    size: 2048
  jp:
    address: 0x08F5A08C
    size: 2048
  eu:
    address: 0x08F630DC
    size: 2048
- name: gUnk_08F67384
  format: tilemap
  us:
    address: 0x08F67384
    size: 2048
  jp:
    address: 0x08F5A88C
    size: 2048
  eu:
    address: 0x08F638DC
    size: 2048
- name: gUnk_08F67B84
  format: tilemap
  us:
    address: 0x08F67B84
    size: 2048
  jp:
    address: 0x08F5B08C
    size: 2048
  eu:
    address: 0x08F640DC
    size: 2048
- name: gUnk_08F6DD64
  format: palette
  us:
    address: 0x08F6DD64
    size: 32
  jp:
    address: 0x08F6126C
    size: 32
  eu:
    address: 0x08F6A2BC
    size: 32
- name: gUnk_08F6DD84
  format: palette
  us:
    address: 0x08F6DD84
    size: 32
  jp:
    address: 0x08F6128C
    size: 32
  eu:
    address: 0x08F6A2DC
    size: 32
- name: gUnk_08F6DDA4
  format: palette
  us:
    address: 0x08F6DDA4
    size: 32
  jp:
    address: 0x08F612AC
    size: 32
  eu:
    address: 0x08F6A2FC
    size: 32
- name: gUnk_08F6DDC4
  format: palette
  us:
    address: 0x08F6DDC4
    size: 32
  jp:
    address: 0x08F612CC
    size: 32
  eu:
    address: 0x08F6A31C
    size: 32
- name: gUnk_08F6DDE4
  format: palette
  us:
    address: 0x08F6DDE4
    size: 32
  jp:
    address: 0x08F612EC
    size: 32
  eu:
    address: 0x08F6A33C
    size: 32
- name: gUnk_08F6DE04
  format: palette
  us:
    address: 0x08F6DE04
    size: 32
  jp:
    address: 0x08F6130C
    size: 32
  eu:
    address: 0x08F6A35C
    size: 32
- name: gUnk_08F6DE24
  format: palette
  us:
    address: 0x08F6DE24
    size: 512
  jp:
    address: 0x08F6132C
    size: 512
  eu:
    address: 0x08F6A37C
    size: 512
- name: gUnk_08F6E024
  format: palette
  us:
    address: 0x08F6E024
    size: 32
  jp:
    address: 0x08F6152C
    size: 32
  eu:
    address: 0x08F6A57C
    size: 32
- name: gUnk_08F6E044
  format: palette
  us:
    address: 0x08F6E044
    size: 32
  jp:
    address: 0x08F6154C
    size: 32
  eu:
    address: 0x08F6A59C
    size: 32
- name: gUnk_08F6E064
  format: palette
  us:
    address: 0x08F6E064
    size: 64
  jp:
    address: 0x08F6156C
    size: 64
  eu:
    address: 0x08F6A5BC
    size: 64
- name: gUnk_08F6E0A4
  format: palette
  us:
    address: 0x08F6E0A4
    size: 96
  jp:
    address: 0x08F615AC
    size: 96
  eu:
    address: 0x08F6A5FC
    size: 96
- name: gUnk_08F6E104
  format: palette
  us:
    address: 0x08F6E104
    size: 32
  jp:
    address: 0x08F6160C
    size: 32
  eu:
    address: 0x08F6A65C
    size: 32
- name: gUnk_08F6E124
  format: palette
  us:
    address: 0x08F6E124
    size: 64
  jp:
    address: 0x08F6162C
    size: 64
  eu:
    address: 0x08F6A67C
    size: 64
- name: gUnk_08F6E164
  format: palette
  us:
    address: 0x08F6E164
    size: 32
  jp:
    address: 0x08F6166C
    size: 32
  eu:
    address: 0x08F6A6BC
    size: 32
- name: gUnk_08C69C9C
  format: sprite_sheet
  cell: [240, 16]
  anchor: [128, 0]
  columns: 4
  frames:
  - symbol: gUnk_08C69C04
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [32x16, 64, 0]
    - [8x16, 96, 0]
  - symbol: gUnk_08C69C20
    pieces:
    - [32x8, -128, 0]
    - [32x8, -96, 0]
    - [32x8, -64, 0]
    - [32x8, -32, 0]
    - [32x8, 0, 0]
    - [32x8, 32, 0]
    - [32x8, 64, 0]
    - [16x8, 96, 0]
  - symbol: gUnk_08C69C54
    pieces:
    - [32x8, -128, 0]
    - [32x8, -96, 0, {fresh: true}]
    - [32x8, -64, 0, {fresh: true}]
    - [8x8, -32, 0]
    - [8x8, 104, 0]
  - symbol: gUnk_08C69C76
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [16x16, 64, 0]
    - [8x16, 80, 0, {fresh: true}]
  animations:
  - symbol: gUnk_08C69C92
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C69C04
    size: 2328
  jp:
    address: 0x08C5D1EC
    size: 2328
  eu:
    address: 0x08C99BB4
    size: 2328
- name: gUnkEu_08C9A5E2
  format: sprite_sheet
  cell: [240, 16]
  anchor: [128, 0]
  columns: 8
  frames:
  - symbol: gUnkEu_08C9A4CC
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [8x16, 64, 0]
  - symbol: gUnkEu_08C9A4E2
    pieces:
    - [32x8, -128, 0]
    - [32x8, -96, 0]
    - [32x8, -64, 0]
    - [32x8, -32, 0]
    - [32x8, 0, 0]
    - [32x8, 32, 0]
    - [32x8, 64, 0]
    - [16x8, 96, 0]
  - symbol: gUnkEu_08C9A516
    pieces:
    - [32x8, -128, 0]
    - [32x8, -96, 0, {fresh: true}]
    - [32x8, -64, 0, {fresh: true}]
    - [8x8, -32, 0]
    - [8x8, 104, 0]
  - symbol: gUnkEu_08C9A538
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [16x16, 64, 0]
    - [8x16, 80, 0]
  - symbol: gUnkEu_08C9A554
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
  - symbol: gUnkEu_08C9A564
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [32x16, 64, 0]
  - symbol: gUnkEu_08C9A57A
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [16x16, 64, 0]
  - symbol: gUnkEu_08C9A590
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [8x16, 64, 0]
  - symbol: gUnkEu_08C9A5A6
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [32x16, 64, 0]
    - [8x16, 96, 0, {fresh: true}]
  - symbol: gUnkEu_08C9A5C2
    pieces:
    - [32x16, 0, 0]
    - [32x16, 32, 0]
    - [32x16, 64, 0]
  animations:
  - symbol: gUnkEu_08C9A5D8
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  eu:
    address: 0x08C9A4CC
    size: 6294
- name: gUnk_08C6A54E
  format: sprite_sheet
  cell: [16, 16]
  anchor: [0, 0]
  columns: 4
  frames:
  - symbol: gUnk_08C6A51C
    pieces:
    - [8x8, 0, 0]
  - symbol: gUnk_08C6A526
    pieces:
    - [8x8, 0, 0]
  - symbol: gUnk_08C6A530
    pieces:
    - [16x16, 0, 0]
  - symbol: gUnk_08C6A53A
    pieces:
    - [16x16, 0, 0]
  animations:
  - symbol: gUnk_08C6A544
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C6A51C
    size: 370
  jp:
    address: 0x08C5DB04
    size: 370
  eu:
    address: 0x08C9C100
    size: 370
- name: gUnk_08C6A6B8
  format: sprite_sheet
  align: 4
  cell: [38, 16]
  anchor: [14, 0]
  columns: 7
  frames:
  - symbol: gUnk_08C6A690
    pieces:
    - [32x16, -8, 0]
  - symbol: gUnk_08C6A69A
    pieces:
    - [16x16, 0, 0]
  - symbol: gUnk_08C6A6A4
    pieces:
    - [16x8, 0, 0]
  animations:
  - symbol: gUnk_08C6A6AE
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C6A690
    size: 488
  jp:
    address: 0x08C5DC78
    size: 488
  eu:
    address: 0x08C9BD64
    size: 924
    frames:
    - symbol: gUnk_08C6A690
      pieces:
      - [32x16, -8, 0]
    - symbol: gUnk_08C6A69A
      pieces:
      - [16x16, 0, 0]
    - symbol: gUnk_08C6A6A4
      pieces:
      - [16x8, 0, 0]
    - symbol: gUnkEu_08C9BD82
      pieces:
      - [32x8, -14, 0]
    - symbol: gUnkEu_08C9BD8C
      pieces:
      - [16x8, -6, 0]
      - [8x8, 10, 0]
    - symbol: gUnkEu_08C9BD9C
      pieces:
      - [16x8, -6, 0]
      - [8x8, 10, 0]
    - symbol: gUnkEu_08C9BDAC
      pieces:
      - [16x8, 0, 0]
- name: gUnk_08C6A88C
  format: sprite_sheet
  align: 4
  cell: [16, 8]
  anchor: [0, 0]
  columns: 1
  frames:
  - symbol: gUnk_08C6A878
    pieces:
    - [16x8, 0, 0]
  animations:
  - symbol: gUnk_08C6A882
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C6A878
    size: 84
  jp:
    address: 0x08C5DE60
    size: 84
  eu:
    address: 0x08C9C274
    size: 84
- name: gUnk_08C6A958
  format: sprite_sheet
  cell: [27, 24]
  anchor: [3, 0]
  columns: 4
  frames:
  - symbol: gUnk_08C6A8CC
    pieces:
    - [16x16, 8, 0, {hflip: true}]
    - [8x16, 0, 0, {hflip: true}]
    - [16x8, 1, 16, {hflip: true}]
  - symbol: gUnk_08C6A8E2
    pieces:
    - [16x16, 7, 0, {hflip: true}]
    - [8x16, -1, 0, {hflip: true}]
    - [16x8, 0, 16, {hflip: true}]
  - symbol: gUnk_08C6A8F8
    pieces:
    - [16x16, 6, 0, {hflip: true}]
    - [8x16, -2, 0, {hflip: true}]
    - [16x8, -1, 16, {hflip: true}]
  - symbol: gUnk_08C6A90E
    pieces:
    - [16x16, 5, 0, {hflip: true}]
    - [8x16, -3, 0, {hflip: true}]
    - [16x8, -2, 16, {hflip: true}]
  animations:
  - symbol: gUnk_08C6A924
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: []
  - symbol: gUnk_08C6A92A
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: []
  - symbol: gUnk_08C6A930
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4], [1, 3], [2, 3], [3, 4], [2, 3], [1, 3]]
  - symbol: gUnk_08C6A94E
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C6A8CC
    size: 396
  jp:
    address: 0x08C5DEB4
    size: 396
  eu:
    address: 0x08C9C2C8
    size: 396
- name: gUnk_08C6AA7E
  format: sprite_sheet
  cell: [64, 50]
  anchor: [32, 26]
  columns: 1
  frames:
  - symbol: gUnk_08C6AA58
    pieces:
    - [32x8, -32, -16]
    - [32x32, 0, -18]
    - [32x8, 0, -26]
    - [32x32, -32, -8]
  animations:
  - symbol: gUnk_08C6AA74
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x08C6AA58
    size: 1318
  jp:
    address: 0x08C5E040
    size: 1318
  eu:
    address: 0x08C9C454
    size: 1318