group: m4a_voicegroups
types: {}
objects:
  us:
  - name: m4a_voicegroups.s
    start: 0x09D6D620
    end: 0x09D6F60C
  jp:
  - name: m4a_voicegroups.s
    start: 0x09D46B2C
    end: 0x09D48B18
  eu:
  - name: m4a_voicegroups.s
    start: 0x09DDD54C
    end: 0x09DDF538
entries:
- name: gVoicegroup0
  format: raw
  us:
    address: 0x09D6D620
    size: 1524
  jp:
    address: 0x09D46B2C
    size: 1524
  eu:
    address: 0x09DDD54C
    size: 1524
- name: gVoicegroup1
  format: raw
  us:
    address: 0x09D6DC14
    size: 336
  jp:
    address: 0x09D47120
    size: 336
  eu:
    address: 0x09DDDB40
    size: 336
- name: gVoicegroup2
  format: raw
  us:
    address: 0x09D6DD64
    size: 1536
  jp:
    address: 0x09D47270
    size: 1536
  eu:
    address: 0x09DDDC90
    size: 1536
- name: gVoicegroup3
  format: raw
  us:
    address: 0x09D6E364
    size: 1248
  jp:
    address: 0x09D47870
    size: 1248
  eu:
    address: 0x09DDE290
    size: 1248
- name: gVoicegroup4
  format: raw
  us:
    address: 0x09D6E844
    size: 852
  jp:
    address: 0x09D47D50
    size: 852
  eu:
    address: 0x09DDE770
    size: 852
- name: gVoicegroup5
  format: raw
  us:
    address: 0x09D6EB98
    size: 240
  jp:
    address: 0x09D480A4
    size: 240
  eu:
    address: 0x09DDEAC4
    size: 240
- name: gVoicegroup0Keysplit12
  format: raw
  us:
    address: 0x09D6EC88
    size: 108
  jp:
    address: 0x09D48194
    size: 108
  eu:
    address: 0x09DDEBB4
    size: 108
- name: gVoicegroup0Keysplit18
  format: raw
  us:
    address: 0x09D6ECF4
    size: 84
  jp:
    address: 0x09D48200
    size: 84
  eu:
    address: 0x09DDEC20
    size: 84
- name: gVoicegroup0Keysplit21
  format: raw
  us:
    address: 0x09D6ED48
    size: 72
  jp:
    address: 0x09D48254
    size: 72
  eu:
    address: 0x09DDEC74
    size: 72
- name: gVoicegroup0Keysplit27
  format: raw
  us:
    address: 0x09D6ED90
    size: 84
  jp:
    address: 0x09D4829C
    size: 84
  eu:
    address: 0x09DDECBC
    size: 84
- name: gVoicegroup0Keysplit35
  format: raw
  us:
    address: 0x09D6EDE4
    size: 84
  jp:
    address: 0x09D482F0
    size: 84
  eu:
    address: 0x09DDED10
    size: 84
- name: gVoicegroup0Keysplit44
  format: raw
  us:
    address: 0x09D6EE38
    size: 84
  jp:
    address: 0x09D48344
    size: 84
  eu:
    address: 0x09DDED64
    size: 84
- name: gVoicegroup0Keysplit50
  format: raw
  us:
    address: 0x09D6EE8C
    size: 84
  jp:
    address: 0x09D48398
    size: 84
  eu:
    address: 0x09DDEDB8
    size: 84
- name: gVoicegroup0Keysplit57
  format: raw
  us:
    address: 0x09D6EEE0
    size: 84
  jp:
    address: 0x09D483EC
    size: 84
  eu:
    address: 0x09DDEE0C
    size: 84
- name: gVoicegroup0Keysplit63
  format: raw
  us:
    address: 0x09D6EF34
    size: 84
  jp:
    address: 0x09D48440
    size: 84
  eu:
    address: 0x09DDEE60
    size: 84
- name: gVoicegroup0Keysplit66
  format: raw
  us:
    address: 0x09D6EF88
    size: 84
  jp:
    address: 0x09D48494
    size: 84
  eu:
    address: 0x09DDEEB4
    size: 84
- name: gVoicegroup0Keysplit69
  format: raw
  us:
    address: 0x09D6EFDC
    size: 84
  jp:
    address: 0x09D484E8
    size: 84
  eu:
    address: 0x09DDEF08
    size: 84
- name: gVoicegroup0Keysplit75
  format: raw
  us:
    address: 0x09D6F030
    size: 84
  jp:
    address: 0x09D4853C
    size: 84
  eu:
    address: 0x09DDEF5C
    size: 84
- name: gVoicegroup0Keysplit79
  format: raw
  us:
    address: 0x09D6F084
    size: 84
  jp:
    address: 0x09D48590
    size: 84
  eu:
    address: 0x09DDEFB0
    size: 84
- name: gVoicegroup0Keysplit89
  format: raw
  us:
    address: 0x09D6F0D8
    size: 84
  jp:
    address: 0x09D485E4
    size: 84
  eu:
    address: 0x09DDF004
    size: 84
- name: gVoicegroup0Keysplit92
  format: raw
  us:
    address: 0x09D6F12C
    size: 84
  jp:
    address: 0x09D48638
    size: 84
  eu:
    address: 0x09DDF058
    size: 84
- name: gVoicegroup0Keysplit101
  format: raw
  us:
    address: 0x09D6F180
    size: 84
  jp:
    address: 0x09D4868C
    size: 84
  eu:
    address: 0x09DDF0AC
    size: 84
- name: gVoicegroup0Keysplit104
  format: raw
  us:
    address: 0x09D6F1D4
    size: 84
  jp:
    address: 0x09D486E0
    size: 84
  eu:
    address: 0x09DDF100
    size: 84
- name: gVoicegroup0Keysplit108
  format: raw
  us:
    address: 0x09D6F228
    size: 84
  jp:
    address: 0x09D48734
    size: 84
  eu:
    address: 0x09DDF154
    size: 84
- name: gVoicegroup0Keysplit111
  format: raw
  us:
    address: 0x09D6F27C
    size: 84
  jp:
    address: 0x09D48788
    size: 84
  eu:
    address: 0x09DDF1A8
    size: 84
- name: gVoicegroup0Keysplit121
  format: raw
  us:
    address: 0x09D6F2D0
    size: 84
  jp:
    address: 0x09D487DC
    size: 84
  eu:
    address: 0x09DDF1FC
    size: 84
- name: gVoicegroup0Keysplit125
  format: raw
  us:
    address: 0x09D6F324
    size: 84
  jp:
    address: 0x09D48830
    size: 84
  eu:
    address: 0x09DDF250
    size: 84
- name: gVoicegroup0Keysplit9
  format: raw
  us:
    address: 0x09D6F378
    size: 84
  jp:
    address: 0x09D48884
    size: 84
  eu:
    address: 0x09DDF2A4
    size: 84
- name: gVoicegroup1Keysplit3
  format: raw
  us:
    address: 0x09D6F3CC
    size: 84
  jp:
    address: 0x09D488D8
    size: 84
  eu:
    address: 0x09DDF2F8
    size: 84
- name: gVoicegroup1Keysplit6
  format: raw
  us:
    address: 0x09D6F420
    size: 84
  jp:
    address: 0x09D4892C
    size: 84
  eu:
    address: 0x09DDF34C
    size: 84
- name: gVoicegroup1Keysplit13
  format: raw
  us:
    address: 0x09D6F474
    size: 84
  jp:
    address: 0x09D48980
    size: 84
  eu:
    address: 0x09DDF3A0
    size: 84
- name: gVoicegroup1Keysplit25
  format: raw
  us:
    address: 0x09D6F4C8
    size: 84
  jp:
    address: 0x09D489D4
    size: 84
  eu:
    address: 0x09DDF3F4
    size: 84
- name: gVoicegroup0Keysplit105
  format: raw
  us:
    address: 0x09D6F51C
    size: 96
  jp:
    address: 0x09D48A28
    size: 96
  eu:
    address: 0x09DDF448
    size: 96
- name: gVoicegroup0Wave58
  format: raw
  us:
    address: 0x09D6F57C
    size: 16
  jp:
    address: 0x09D48A88
    size: 16
  eu:
    address: 0x09DDF4A8
    size: 16
- name: gWave1
  format: raw
  us:
    address: 0x09D6F58C
    size: 16
  jp:
    address: 0x09D48A98
    size: 16
  eu:
    address: 0x09DDF4B8
    size: 16
- name: gVoicegroup2Wave2
  format: raw
  us:
    address: 0x09D6F59C
    size: 16
  jp:
    address: 0x09D48AA8
    size: 16
  eu:
    address: 0x09DDF4C8
    size: 16
- name: gWave3
  format: raw
  us:
    address: 0x09D6F5AC
    size: 16
  jp:
    address: 0x09D48AB8
    size: 16
  eu:
    address: 0x09DDF4D8
    size: 16
- name: gWave4
  format: raw
  us:
    address: 0x09D6F5BC
    size: 16
  jp:
    address: 0x09D48AC8
    size: 16
  eu:
    address: 0x09DDF4E8
    size: 16
- name: gWave5
  format: raw
  us:
    address: 0x09D6F5CC
    size: 16
  jp:
    address: 0x09D48AD8
    size: 16
  eu:
    address: 0x09DDF4F8
    size: 16
- name: gWave6
  format: raw
  us:
    address: 0x09D6F5DC
    size: 16
  jp:
    address: 0x09D48AE8
    size: 16
  eu:
    address: 0x09DDF508
    size: 16
- name: gWave7
  format: raw
  us:
    address: 0x09D6F5EC
    size: 16
  jp:
    address: 0x09D48AF8
    size: 16
  eu:
    address: 0x09DDF518
    size: 16
- name: gWave8
  format: raw
  us:
    address: 0x09D6F5FC
    size: 16
  jp:
    address: 0x09D48B08
    size: 16
  eu:
    address: 0x09DDF528
    size: 16
