group: sprites_continue
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_continue.c
    start: 0x09EEB0C4
    end: 0x09EEB188
  - name: sprites_continue_frames.s
    start: 0x090A6A20
    end: 0x090AA3C4
  - name: sprites_continue_tiles.s
    start: 0x0941A418
    end: 0x0941BEB8
  - name: sprites_continue_maps.s
    start: 0x0951CAB8
    end: 0x0951D2B8
  jp:
  - name: sprites_continue.c
    start: 0x09EC24B0
    end: 0x09EC2574
  - name: sprites_continue_frames.s
    start: 0x09061F48
    end: 0x090658EC
  - name: sprites_continue_tiles.s
    start: 0x093D2754
    end: 0x093D4194
  - name: sprites_continue_maps.s
    start: 0x094D5594
    end: 0x094D5D94
  eu:
  - name: sprites_continue.c
    start: 0x09F77254
    end: 0x09F77318
  - name: sprites_continue_frames.s
    start: 0x0919728C
    end: 0x0919AC30
  - name: sprites_continue_tiles.s
    start: 0x0954C284
    end: 0x0954DD34
  - name: sprites_continue_maps.s
    start: 0x095A3D74
    end: 0x095A3F4C
entries:
- name: gUnk_09EEB0C4
  record: SpriteTable
  items: [gUnk_090A6A20, gUnk_090A6A2A, gUnk_090A6A34, gUnk_090A6A3E, gUnk_090A6A48]
  us:
    address: 0x09EEB0C4
  jp:
    address: 0x09EC24B0
  eu:
    address: 0x09F77254
- name: gUnk_09EEB0D8
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A52]
  us:
    address: 0x09EEB0D8
  jp:
    address: 0x09EC24C4
  eu:
    address: 0x09F77268
- name: gUnk_09EEB0DC
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A5C]
  us:
    address: 0x09EEB0DC
  jp:
    address: 0x09EC24C8
  eu:
    address: 0x09F7726C
- name: gUnk_09EEB0E0
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A66]
  us:
    address: 0x09EEB0E0
  jp:
    address: 0x09EC24CC
  eu:
    address: 0x09F77270
- name: gUnk_09EEB0E4
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A70]
  us:
    address: 0x09EEB0E4
  jp:
    address: 0x09EC24D0
  eu:
    address: 0x09F77274
- name: gUnk_09EEB0E8
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A7A]
  us:
    address: 0x09EEB0E8
  jp:
    address: 0x09EC24D4
  eu:
    address: 0x09F77278
- name: gUnk_09EEB0EC
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A84]
  us:
    address: 0x09EEB0EC
  jp:
    address: 0x09EC24D8
  eu:
    address: 0x09F7727C
- name: gUnk_09EEB0F0
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A8E]
  us:
    address: 0x09EEB0F0
  jp:
    address: 0x09EC24DC
  eu:
    address: 0x09F77280
- name: gUnk_09EEB0F4
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6A98]
  us:
    address: 0x09EEB0F4
  jp:
    address: 0x09EC24E0
  eu:
    address: 0x09F77284
- name: gUnk_09EEB0F8
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6AA2]
  us:
    address: 0x09EEB0F8
  jp:
    address: 0x09EC24E4
  eu:
    address: 0x09F77288
- name: gUnk_09EEB0FC
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6AAC]
  us:
    address: 0x09EEB0FC
  jp:
    address: 0x09EC24E8
  eu:
    address: 0x09F7728C
- name: gUnk_09EEB100
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6AB6]
  us:
    address: 0x09EEB100
  jp:
    address: 0x09EC24EC
  eu:
    address: 0x09F77290
- name: gUnk_09EEB104
  record: SpriteTable
  scalar: true
  items: [gUnk_090A6AC0]
  us:
    address: 0x09EEB104
  jp:
    address: 0x09EC24F0
  eu:
    address: 0x09F77294
- name: gUnk_09EEB108
  record: AnimTable
  items: [gUnk_090A6ACA]
  us:
    address: 0x09EEB108
  jp:
    address: 0x09EC24F4
  eu:
    address: 0x09F77298
- name: gUnk_09EEB10C
  record: AnimTable
  scalar: true
  items: [gUnk_090A6AF0]
  us:
    address: 0x09EEB10C
  jp:
    address: 0x09EC24F8
  eu:
    address: 0x09F7729C
- name: gUnk_09EEB110
  record: SpriteTable
  scalar: true
  items: [gUnk_090A7D28]
  us:
    address: 0x09EEB110
  jp:
    address: 0x09EC24FC
  eu:
    address: 0x09F772A0
- name: gUnk_09EEB114
  record: SpriteTable
  scalar: true
  items: [gUnk_090A7D5C]
  us:
    address: 0x09EEB114
  jp:
    address: 0x09EC2500
  eu:
    address: 0x09F772A4
- name: gUnk_09EEB118
  record: AnimTable
  scalar: true
  items: [gUnk_090A7D90]
  us:
    address: 0x09EEB118
  jp:
    address: 0x09EC2504
  eu:
    address: 0x09F772A8
- name: gUnk_09EEB11C
  record: SpriteTable
  items: [gUnk_090A7E5C, gUnk_090A7E66, gUnk_090A7E70, gUnk_090A7E7A, gUnk_090A7E84, gUnk_090A7E8E, gUnk_090A7E98, gUnk_090A7EA2, gUnk_090A7EAC, gUnk_090A7EB6, gUnk_090A7EC0, gUnk_090A7ECA]
  us:
    address: 0x09EEB11C
  jp:
    address: 0x09EC2508
  eu:
    address: 0x09F772AC
- name: gUnk_09EEB14C
  record: AnimTable
  items: [gUnk_090A7ED4]
  us:
    address: 0x09EEB14C
  jp:
    address: 0x09EC2538
  eu:
    address: 0x09F772DC
- name: gUnk_09EEB150
  record: SpriteTable
  items: [gUnk_090A8F0C, gUnk_090A8F16, gUnk_090A8F20, gUnk_090A8F2A, gUnk_090A8F34, gUnk_090A8F3E, gUnk_090A8F48, gUnk_090A8F52, gUnk_090A8F5C, gUnk_090A8F66, gUnk_090A8F70, gUnk_090A8F7A]
  us:
    address: 0x09EEB150
  jp:
    address: 0x09EC253C
  eu:
    address: 0x09F772E0
- name: gUnk_09EEB180
  record: AnimTable
  items: [gUnk_090A8F84, gUnk_090A8FBA]
  us:
    address: 0x09EEB180
  jp:
    address: 0x09EC256C
  eu:
    address: 0x09F77310
- name: gUnk_090A6A20
  record: Sprite
  align: 4
  oam:
  - [240, 33264, 0]
  us:
    address: 0x090A6A20
  jp:
    address: 0x09061F48
  eu:
    address: 0x0919728C
- name: gUnk_090A6A2A
  record: Sprite
  oam:
  - [240, 33264, 4096]
  us:
    address: 0x090A6A2A
  jp:
    address: 0x09061F52
  eu:
    address: 0x09197296
- name: gUnk_090A6A34
  record: Sprite
  oam:
  - [240, 33264, 8192]
  us:
    address: 0x090A6A34
  jp:
    address: 0x09061F5C
  eu:
    address: 0x091972A0
- name: gUnk_090A6A3E
  record: Sprite
  oam:
  - [240, 33264, 12288]
  us:
    address: 0x090A6A3E
  jp:
    address: 0x09061F66
  eu:
    address: 0x091972AA
- name: gUnk_090A6A48
  record: Sprite
  oam:
  - [240, 33264, 12288]
  us:
    address: 0x090A6A48
  jp:
    address: 0x09061F70
  eu:
    address: 0x091972B4
- name: gUnk_090A6A52
  record: Sprite
  oam:
  - [16628, 49633, 32784]
  us:
    address: 0x090A6A52
  jp:
    address: 0x09061F7A
  eu:
    address: 0x091972BE
- name: gUnk_090A6A5C
  record: Sprite
  oam:
  - [16627, 49633, 32784]
  us:
    address: 0x090A6A5C
  jp:
    address: 0x09061F84
  eu:
    address: 0x091972C8
- name: gUnk_090A6A66
  record: Sprite
  oam:
  - [16626, 49633, 32784]
  us:
    address: 0x090A6A66
  jp:
    address: 0x09061F8E
  eu:
    address: 0x091972D2
- name: gUnk_090A6A70
  record: Sprite
  oam:
  - [16627, 49633, 32816]
  us:
    address: 0x090A6A70
  jp:
    address: 0x09061F98
  eu:
    address: 0x091972DC
- name: gUnk_090A6A7A
  record: Sprite
  oam:
  - [16626, 49633, 32816]
  us:
    address: 0x090A6A7A
  jp:
    address: 0x09061FA2
  eu:
    address: 0x091972E6
- name: gUnk_090A6A84
  record: Sprite
  oam:
  - [16625, 49633, 32816]
  us:
    address: 0x090A6A84
  jp:
    address: 0x09061FAC
  eu:
    address: 0x091972F0
- name: gUnk_090A6A8E
  record: Sprite
  oam:
  - [16616, 49633, 32848]
  us:
    address: 0x090A6A8E
  jp:
    address: 0x09061FB6
  eu:
    address: 0x091972FA
- name: gUnk_090A6A98
  record: Sprite
  oam:
  - [16618, 49633, 32848]
  us:
    address: 0x090A6A98
  jp:
    address: 0x09061FC0
  eu:
    address: 0x09197304
- name: gUnk_090A6AA2
  record: Sprite
  oam:
  - [16619, 49633, 32848]
  us:
    address: 0x090A6AA2
  jp:
    address: 0x09061FCA
  eu:
    address: 0x0919730E
- name: gUnk_090A6AAC
  record: Sprite
  oam:
  - [16626, 49633, 32880]
  us:
    address: 0x090A6AAC
  jp:
    address: 0x09061FD4
  eu:
    address: 0x09197318
- name: gUnk_090A6AB6
  record: Sprite
  oam:
  - [16627, 49633, 32880]
  us:
    address: 0x090A6AB6
  jp:
    address: 0x09061FDE
  eu:
    address: 0x09197322
- name: gUnk_090A6AC0
  record: Sprite
  oam:
  - [16628, 49633, 32880]
  us:
    address: 0x090A6AC0
  jp:
    address: 0x09061FE8
  eu:
    address: 0x0919732C
- name: gUnk_090A6ACA
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 8]
  - [1, 8]
  - [2, 8]
  - [3, 8]
  - [4, 8]
  - [3, 8]
  - [2, 8]
  - [1, 8]
  us:
    address: 0x090A6ACA
  jp:
    address: 0x09061FF2
  eu:
    address: 0x09197336
- name: gUnk_090A6AF0
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [5, 13]
  - [6, 13]
  - [7, 13]
  - [8, 13]
  - [9, 13]
  - [10, 13]
  - [11, 13]
  - [12, 13]
  - [13, 13]
  - [14, 13]
  - [15, 13]
  - [16, 13]
  us:
    address: 0x090A6AF0
  jp:
    address: 0x09062018
  eu:
    address: 0x0919735C
- name: gUnk_090A6B26
  format: tiles4
  width: 4
  us:
    address: 0x090A6B26
    size: 4608
  jp:
    address: 0x0906204E
    size: 4608
  eu:
    address: 0x09197392
    size: 4608
- name: gUnk_090A7D28
  record: Sprite
  align: 4
  oam:
  - [16384, 16768, 0]
  - [16384, 16800, 0]
  - [16384, 16832, 0]
  - [16384, 16864, 0]
  - [16384, 16384, 0]
  - [16384, 16416, 0]
  - [16384, 16448, 0]
  - [16384, 96, 4]
  us:
    address: 0x090A7D28
  jp:
    address: 0x09063250
  eu:
    address: 0x09198594
- name: gUnk_090A7D5C
  record: Sprite
  oam:
  - [16384, 24960, 0]
  - [16384, 24992, 0]
  - [16384, 25024, 0]
  - [16384, 25056, 0]
  - [16384, 24576, 0]
  - [16384, 24608, 0]
  - [16384, 24640, 0]
  - [16384, 8288, 4]
  us:
    address: 0x090A7D5C
  jp:
    address: 0x09063284
  eu:
    address: 0x091985C8
- name: gUnk_090A7D90
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x090A7D90
  jp:
    address: 0x090632B8
  eu:
    address: 0x091985FC
- name: gUnk_090A7D9A
  format: tiles4
  width: 1
  us:
    address: 0x090A7D9A
    size: 192
  jp:
    address: 0x090632C2
    size: 192
  eu:
    address: 0x09198606
    size: 192
- name: gUnk_090A7E5C
  record: Sprite
  align: 4
  oam:
  - [16628, 49633, 0]
  us:
    address: 0x090A7E5C
  jp:
    address: 0x09063384
  eu:
    address: 0x091986C8
- name: gUnk_090A7E66
  record: Sprite
  oam:
  - [16627, 49633, 0]
  us:
    address: 0x090A7E66
  jp:
    address: 0x0906338E
  eu:
    address: 0x091986D2
- name: gUnk_090A7E70
  record: Sprite
  oam:
  - [16626, 49633, 0]
  us:
    address: 0x090A7E70
  jp:
    address: 0x09063398
  eu:
    address: 0x091986DC
- name: gUnk_090A7E7A
  record: Sprite
  oam:
  - [16627, 49633, 32]
  us:
    address: 0x090A7E7A
  jp:
    address: 0x090633A2
  eu:
    address: 0x091986E6
- name: gUnk_090A7E84
  record: Sprite
  oam:
  - [16626, 49633, 32]
  us:
    address: 0x090A7E84
  jp:
    address: 0x090633AC
  eu:
    address: 0x091986F0
- name: gUnk_090A7E8E
  record: Sprite
  oam:
  - [16625, 49633, 32]
  us:
    address: 0x090A7E8E
  jp:
    address: 0x090633B6
  eu:
    address: 0x091986FA
- name: gUnk_090A7E98
  record: Sprite
  oam:
  - [16616, 49633, 64]
  us:
    address: 0x090A7E98
  jp:
    address: 0x090633C0
  eu:
    address: 0x09198704
- name: gUnk_090A7EA2
  record: Sprite
  oam:
  - [16618, 49633, 64]
  us:
    address: 0x090A7EA2
  jp:
    address: 0x090633CA
  eu:
    address: 0x0919870E
- name: gUnk_090A7EAC
  record: Sprite
  oam:
  - [16619, 49633, 64]
  us:
    address: 0x090A7EAC
  jp:
    address: 0x090633D4
  eu:
    address: 0x09198718
- name: gUnk_090A7EB6
  record: Sprite
  oam:
  - [16626, 49633, 96]
  us:
    address: 0x090A7EB6
  jp:
    address: 0x090633DE
  eu:
    address: 0x09198722
- name: gUnk_090A7EC0
  record: Sprite
  oam:
  - [16627, 49633, 96]
  us:
    address: 0x090A7EC0
  jp:
    address: 0x090633E8
  eu:
    address: 0x0919872C
- name: gUnk_090A7ECA
  record: Sprite
  oam:
  - [16628, 49633, 96]
  us:
    address: 0x090A7ECA
  jp:
    address: 0x090633F2
  eu:
    address: 0x09198736
- name: gUnk_090A7ED4
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 13]
  - [1, 13]
  - [2, 13]
  - [3, 13]
  - [4, 13]
  - [5, 13]
  - [6, 13]
  - [7, 13]
  - [8, 13]
  - [9, 13]
  - [10, 13]
  - [11, 13]
  us:
    address: 0x090A7ED4
  jp:
    address: 0x090633FC
  eu:
    address: 0x09198740
- name: gUnk_090A7F0A
  format: tiles4
  width: 8
  palette: sora
  us:
    address: 0x090A7F0A
    size: 4096
  jp:
    address: 0x09063432
    size: 4096
  eu:
    address: 0x09198776
    size: 4096
- name: gUnk_090A8F0C
  record: Sprite
  align: 4
  oam:
  - [16624, 49636, 0]
  us:
    address: 0x090A8F0C
  jp:
    address: 0x09064434
  eu:
    address: 0x09199778
- name: gUnk_090A8F16
  record: Sprite
  oam:
  - [16623, 49636, 0]
  us:
    address: 0x090A8F16
  jp:
    address: 0x0906443E
  eu:
    address: 0x09199782
- name: gUnk_090A8F20
  record: Sprite
  oam:
  - [16622, 49636, 32]
  us:
    address: 0x090A8F20
  jp:
    address: 0x09064448
  eu:
    address: 0x0919978C
- name: gUnk_090A8F2A
  record: Sprite
  oam:
  - [16621, 49636, 32]
  us:
    address: 0x090A8F2A
  jp:
    address: 0x09064452
  eu:
    address: 0x09199796
- name: gUnk_090A8F34
  record: Sprite
  oam:
  - [16620, 49636, 64]
  us:
    address: 0x090A8F34
  jp:
    address: 0x0906445C
  eu:
    address: 0x091997A0
- name: gUnk_090A8F3E
  record: Sprite
  oam:
  - [16619, 49636, 64]
  us:
    address: 0x090A8F3E
  jp:
    address: 0x09064466
  eu:
    address: 0x091997AA
- name: gUnk_090A8F48
  record: Sprite
  oam:
  - [16619, 49636, 96]
  us:
    address: 0x090A8F48
  jp:
    address: 0x09064470
  eu:
    address: 0x091997B4
- name: gUnk_090A8F52
  record: Sprite
  oam:
  - [16620, 49636, 96]
  us:
    address: 0x090A8F52
  jp:
    address: 0x0906447A
  eu:
    address: 0x091997BE
- name: gUnk_090A8F5C
  record: Sprite
  oam:
  - [16621, 49636, 96]
  us:
    address: 0x090A8F5C
  jp:
    address: 0x09064484
  eu:
    address: 0x091997C8
- name: gUnk_090A8F66
  record: Sprite
  oam:
  - [16622, 49636, 128]
  us:
    address: 0x090A8F66
  jp:
    address: 0x0906448E
  eu:
    address: 0x091997D2
- name: gUnk_090A8F70
  record: Sprite
  oam:
  - [16623, 49636, 128]
  us:
    address: 0x090A8F70
  jp:
    address: 0x09064498
  eu:
    address: 0x091997DC
- name: gUnk_090A8F7A
  record: Sprite
  oam:
  - [16624, 49636, 128]
  us:
    address: 0x090A8F7A
  jp:
    address: 0x090644A2
  eu:
    address: 0x091997E6
- name: gUnk_090A8F84
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 13]
  - [1, 13]
  - [2, 13]
  - [3, 13]
  - [4, 13]
  - [5, 13]
  - [6, 13]
  - [7, 13]
  - [8, 13]
  - [9, 13]
  - [10, 13]
  - [11, 13]
  us:
    address: 0x090A8F84
  jp:
    address: 0x090644AC
  eu:
    address: 0x091997F0
- name: gUnk_090A8FBA
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x090A8FBA
  jp:
    address: 0x090644E2
  eu:
    address: 0x09199826
- name: gUnk_090A8FC4
  format: tiles4
  width: 8
  palette: riku
  us:
    address: 0x090A8FC4
    size: 5120
  jp:
    address: 0x090644EC
    size: 5120
  eu:
    address: 0x09199830
    size: 5120
- name: gUnk_0941A418
  format: tiles4
  us:
    address: 0x0941A418
    size: 6816
  jp:
    address: 0x093D2754
    size: 6720
  eu:
    address: 0x0954C284
    size: 1328
    compress: lz77
- name: gUnk_0951CAB8
  format: tilemap
  us:
    address: 0x0951CAB8
    size: 2048
  jp:
    address: 0x094D5594
    size: 2048
  eu:
    address: 0x095A3D74
    size: 472
    compress: lz77
- name: gUnkEu_0954C7B4
  format: tiles4
  eu:
    address: 0x0954C7B4
    size: 1384
    compress: lz77
- name: gUnkEu_0954CD1C
  format: tiles4
  eu:
    address: 0x0954CD1C
    size: 1308
    compress: lz77
- name: gUnkEu_0954D238
  format: tiles4
  eu:
    address: 0x0954D238
    size: 1384
    compress: lz77
- name: gUnkEu_0954D7A0
  format: tiles4
  eu:
    address: 0x0954D7A0
    size: 1428
    compress: lz77
