group: sprites_room
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_room.c
    start: 0x09EF9684
    end: 0x09EF9740
  - name: sprites_room_frames.s
    start: 0x0999389C
    end: 0x09999E0C
  - name: sprites_room_maps.s
    start: 0x09A1E0DC
    end: 0x09A208DC
  - name: sprites_room_palettes.s
    start: 0x09A3C75C
    end: 0x09A3C89C
  jp:
  - name: sprites_room.c
    start: 0x09ED0A70
    end: 0x09ED0B2C
  - name: sprites_room_frames.s
    start: 0x099483B0
    end: 0x0994E920
  - name: sprites_room_maps.s
    start: 0x099D2B64
    end: 0x099D5364
  - name: sprites_room_palettes.s
    start: 0x099F11E4
    end: 0x099F1324
  eu:
  - name: sprites_room.c
    start: 0x09F85100
    end: 0x09F851BC
  - name: sprites_room_frames.s
    start: 0x09999B58
    end: 0x099A00C8
  - name: sprites_room_maps.s
    start: 0x09A6FCA0
    end: 0x09A724A0
  - name: sprites_room_palettes.s
    start: 0x09A9A220
    end: 0x09A9A360
entries:
- name: gUnk_09EF9684
  record: SpriteTable
  items: [gUnk_0999389C, gUnk_099938C4, gUnk_099938EC, gUnk_09993914, gUnk_09993942, gUnk_0999395E, gUnk_09993986, gUnk_099939A2]
  us:
    address: 0x09EF9684
  jp:
    address: 0x09ED0A70
  eu:
    address: 0x09F85100
- name: gUnk_09EF96A4
  record: AnimTable
  items: [gUnk_099939C4, gUnk_099939DA, gUnk_099939F0]
  us:
    address: 0x09EF96A4
  jp:
    address: 0x09ED0A90
  eu:
    address: 0x09F85120
- name: gUnk_09EF96B0
  record: SpriteTable
  items: [gUnk_09995E3C, gUnk_09995E46, gUnk_09995E50, gUnk_09995E5A, gUnk_09995E64, gUnk_09995E6E]
  us:
    address: 0x09EF96B0
  jp:
    address: 0x09ED0A9C
  eu:
    address: 0x09F8512C
- name: gUnk_09EF96C8
  record: AnimTable
  items: [gUnk_09995E78, gUnk_09995E82]
  us:
    address: 0x09EF96C8
  jp:
    address: 0x09ED0AB4
  eu:
    address: 0x09F85144
- name: gUnk_09EF96D0
  record: SpriteTable
  items: [gUnk_09996A9C, gUnk_09996AC4, gUnk_09996AE0, gUnk_09996AF6, gUnk_09996B12, gUnk_09996B28, gUnk_09996B3E]
  us:
    address: 0x09EF96D0
  jp:
    address: 0x09ED0ABC
  eu:
    address: 0x09F8514C
- name: gUnk_09EF96EC
  record: AnimTable
  items: [gUnk_09996B5A, gUnk_09996B64]
  us:
    address: 0x09EF96EC
  jp:
    address: 0x09ED0AD8
  eu:
    address: 0x09F85168
- name: gUnk_09EF96F4
  record: SpriteTable
  items: [gUnk_09997E84, gUnk_09997EA0, gUnk_09997EB6, gUnk_09997ED2, gUnk_09997EEE, gUnk_09997F0A, gUnk_09997F20]
  us:
    address: 0x09EF96F4
  jp:
    address: 0x09ED0AE0
  eu:
    address: 0x09F85170
- name: gUnk_09EF9710
  record: AnimTable
  items: [gUnk_09997F3C, gUnk_09997F46]
  us:
    address: 0x09EF9710
  jp:
    address: 0x09ED0AFC
  eu:
    address: 0x09F8518C
- name: gUnk_09EF9718
  record: SpriteTable
  items: [gUnk_09999224]
  us:
    address: 0x09EF9718
  jp:
    address: 0x09ED0B04
  eu:
    address: 0x09F85194
- name: gUnk_09EF971C
  record: AnimTable
  items: [gUnk_0999923A]
  us:
    address: 0x09EF971C
  jp:
    address: 0x09ED0B08
  eu:
    address: 0x09F85198
- name: gUnk_09EF9720
  record: SpriteTable
  items: [gUnk_099995C4]
  us:
    address: 0x09EF9720
  jp:
    address: 0x09ED0B0C
  eu:
    address: 0x09F8519C
- name: gUnk_09EF9724
  record: AnimTable
  items: [gUnk_099995F2]
  us:
    address: 0x09EF9724
  jp:
    address: 0x09ED0B10
  eu:
    address: 0x09F851A0
- name: gUnk_09EF9728
  record: SpriteTable
  items: [gUnk_0999991C, gUnk_09999938, gUnk_09999954, gUnk_09999970]
  us:
    address: 0x09EF9728
  jp:
    address: 0x09ED0B14
  eu:
    address: 0x09F851A4
- name: gUnk_09EF9738
  record: AnimTable
  items: [gUnk_0999998C, gUnk_099999A2]
  us:
    address: 0x09EF9738
  jp:
    address: 0x09ED0B24
  eu:
    address: 0x09F851B4
- name: gUnk_0999389C
  record: Sprite
  align: 4
  oam:
  - [32986, 49647, 0]
  - [233, 488, 32]
  - [32778, 488, 33]
  - [25, 511, 35]
  - [33018, 32775, 36]
  - [218, 16871, 44]
  us:
    address: 0x0999389C
  jp:
    address: 0x099483B0
  eu:
    address: 0x09999B58
- name: gUnk_099938C4
  record: Sprite
  oam:
  - [32987, 49646, 48]
  - [14, 487, 80]
  - [234, 487, 81]
  - [33019, 16397, 82]
  - [32769, 20, 86]
  - [219, 16870, 88]
  us:
    address: 0x099938C4
  jp:
    address: 0x099483D8
  eu:
    address: 0x09999B80
- name: gUnk_099938EC
  record: Sprite
  oam:
  - [32987, 49649, 92]
  - [32987, 490, 124]
  - [234, 490, 126]
  - [32773, 490, 127]
  - [33023, 16, 129]
  - [14, 16, 131]
  us:
    address: 0x099938EC
  jp:
    address: 0x09948400
  eu:
    address: 0x09999BA8
- name: gUnk_09993914
  record: Sprite
  oam:
  - [32986, 49652, 132]
  - [32987, 493, 164]
  - [234, 493, 166]
  - [32770, 493, 167]
  - [17, 493, 169]
  - [25, 508, 170]
  - [32770, 19, 171]
  us:
    address: 0x09993914
  jp:
    address: 0x09948428
  eu:
    address: 0x09999BD0
- name: gUnk_09993942
  record: Sprite
  oam:
  - [32987, 49647, 173]
  - [32771, 488, 205]
  - [18, 488, 207]
  - [32769, 14, 208]
  us:
    address: 0x09993942
  jp:
    address: 0x09948456
  eu:
    address: 0x09999BFE
- name: gUnk_0999395E
  record: Sprite
  oam:
  - [32772, 489, 210]
  - [32772, 15, 212]
  - [244, 33264, 214]
  - [16606, 33256, 230]
  - [222, 16391, 238]
  - [16621, 16880, 242]
  us:
    address: 0x0999395E
  jp:
    address: 0x09948472
  eu:
    address: 0x09999C1A
- name: gUnk_09993986
  record: Sprite
  oam:
  - [32987, 53745, 173]
  - [32771, 4112, 205]
  - [18, 4112, 207]
  - [32769, 4586, 208]
  us:
    address: 0x09993986
  jp:
    address: 0x0994849A
  eu:
    address: 0x09999C42
- name: gUnk_099939A2
  record: Sprite
  oam:
  - [32990, 49648, 246]
  - [33022, 16873, 278]
  - [33022, 16399, 282]
  - [32990, 489, 286]
  - [32990, 15, 288]
  us:
    address: 0x099939A2
  jp:
    address: 0x099484B6
  eu:
    address: 0x09999C5E
- name: gUnk_099939C4
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 12]
  - [1, 12]
  - [2, 12]
  - [3, 12]
  us:
    address: 0x099939C4
  jp:
    address: 0x099484D8
  eu:
    address: 0x09999C80
- name: gUnk_099939DA
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [4, 5]
  - [5, 5]
  - [6, 5]
  - [7, 5]
  us:
    address: 0x099939DA
  jp:
    address: 0x099484EE
  eu:
    address: 0x09999C96
- name: gUnk_099939F0
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x099939F0
  jp:
    address: 0x09948504
  eu:
    address: 0x09999CAC
- name: gRoomAssetUs_099939FA
  format: tiles4
  width: 1
  us:
    address: 0x099939FA
    size: 9280
  jp:
    address: 0x0994850E
    size: 9280
    symbol: gRoomAssetJp_0994850E
  eu:
    address: 0x09999CB6
    size: 9280
    symbol: gRoomAssetEu_09999CB6
- name: gUnk_09995E3C
  record: Sprite
  align: 4
  oam:
  - [238, 33264, 0]
  us:
    address: 0x09995E3C
  jp:
    address: 0x0994A950
  eu:
    address: 0x0999C0F8
- name: gUnk_09995E46
  record: Sprite
  oam:
  - [238, 33264, 16]
  us:
    address: 0x09995E46
  jp:
    address: 0x0994A95A
  eu:
    address: 0x0999C102
- name: gUnk_09995E50
  record: Sprite
  oam:
  - [238, 33264, 32]
  us:
    address: 0x09995E50
  jp:
    address: 0x0994A964
  eu:
    address: 0x0999C10C
- name: gUnk_09995E5A
  record: Sprite
  oam:
  - [238, 33264, 48]
  us:
    address: 0x09995E5A
  jp:
    address: 0x0994A96E
  eu:
    address: 0x0999C116
- name: gUnk_09995E64
  record: Sprite
  oam:
  - [238, 33264, 64]
  us:
    address: 0x09995E64
  jp:
    address: 0x0994A978
  eu:
    address: 0x0999C120
- name: gUnk_09995E6E
  record: Sprite
  oam:
  - [238, 33264, 80]
  us:
    address: 0x09995E6E
  jp:
    address: 0x0994A982
  eu:
    address: 0x0999C12A
- name: gUnk_09995E78
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x09995E78
  jp:
    address: 0x0994A98C
  eu:
    address: 0x0999C134
- name: gUnk_09995E82
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [1, 6]
  - [2, 6]
  - [3, 6]
  - [4, 6]
  - [5, 6]
  us:
    address: 0x09995E82
  jp:
    address: 0x0994A996
  eu:
    address: 0x0999C13E
- name: gRoomAssetUs_09995E9C
  format: tiles4
  width: 4
  us:
    address: 0x09995E9C
    size: 3072
  jp:
    address: 0x0994A9B0
    size: 3072
    symbol: gRoomAssetJp_0994A9B0
  eu:
    address: 0x0999C158
    size: 3072
    symbol: gRoomAssetEu_0999C158
- name: gUnk_09996A9C
  record: Sprite
  align: 4
  oam:
  - [233, 16390, 0]
  - [249, 33254, 4]
  - [33016, 5, 20]
  - [242, 511, 22]
  - [9, 479, 23]
  - [24, 494, 24]
  us:
    address: 0x09996A9C
  jp:
    address: 0x0994B5B0
  eu:
    address: 0x0999CD58
- name: gUnk_09996AC4
  record: Sprite
  oam:
  - [232, 16895, 25]
  - [247, 33263, 29]
  - [16406, 495, 45]
  - [22, 510, 47]
  us:
    address: 0x09996AC4
  jp:
    address: 0x0994B5D8
  eu:
    address: 0x0999CD80
- name: gUnk_09996AE0
  record: Sprite
  oam:
  - [230, 16882, 48]
  - [245, 33266, 52]
  - [16404, 16882, 68]
  us:
    address: 0x09996AE0
  jp:
    address: 0x0994B5F4
  eu:
    address: 0x0999CD9C
- name: gUnk_09996AF6
  record: Sprite
  oam:
  - [239, 16870, 72]
  - [247, 33269, 76]
  - [240, 501, 92]
  - [33023, 20, 93]
  us:
    address: 0x09996AF6
  jp:
    address: 0x0994B60A
  eu:
    address: 0x0999CDB2
- name: gUnk_09996B12
  record: Sprite
  oam:
  - [33004, 33268, 95]
  - [33004, 16387, 103]
  - [16395, 507, 107]
  us:
    address: 0x09996B12
  jp:
    address: 0x0994B626
  eu:
    address: 0x0999CDCE
- name: gUnk_09996B28
  record: Sprite
  oam:
  - [33007, 10, 109]
  - [239, 33259, 111]
  - [14, 3, 127]
  us:
    address: 0x09996B28
  jp:
    address: 0x0994B63C
  eu:
    address: 0x0999CDE4
- name: gUnk_09996B3E
  record: Sprite
  oam:
  - [233, 16391, 128]
  - [249, 33255, 132]
  - [33016, 6, 148]
  - [16626, 504, 150]
  us:
    address: 0x09996B3E
  jp:
    address: 0x0994B652
  eu:
    address: 0x0999CDFA
- name: gUnk_09996B5A
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x09996B5A
  jp:
    address: 0x0994B66E
  eu:
    address: 0x0999CE16
- name: gUnk_09996B64
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [1, 7]
  - [2, 7]
  - [3, 7]
  - [4, 7]
  - [5, 7]
  - [6, 7]
  us:
    address: 0x09996B64
  jp:
    address: 0x0994B678
  eu:
    address: 0x0999CE20
- name: gRoomAssetUs_09996B82
  format: tiles4
  width: 2
  us:
    address: 0x09996B82
    size: 4864
  jp:
    address: 0x0994B696
    size: 4864
    symbol: gRoomAssetJp_0994B696
  eu:
    address: 0x0999CE3E
    size: 4864
    symbol: gRoomAssetEu_0999CE3E
- name: gUnk_09997E84
  record: Sprite
  align: 4
  oam:
  - [233, 16391, 0]
  - [249, 33256, 4]
  - [33016, 7, 20]
  - [16626, 504, 22]
  us:
    address: 0x09997E84
  jp:
    address: 0x0994C998
  eu:
    address: 0x0999E140
- name: gUnk_09997EA0
  record: Sprite
  oam:
  - [228, 16386, 24]
  - [243, 33266, 28]
  - [16402, 16882, 44]
  us:
    address: 0x09997EA0
  jp:
    address: 0x0994C9B4
  eu:
    address: 0x0999E15C
- name: gUnk_09997EB6
  record: Sprite
  oam:
  - [231, 16881, 48]
  - [246, 33265, 52]
  - [16405, 505, 68]
  - [21, 9, 70]
  us:
    address: 0x09997EB6
  jp:
    address: 0x0994C9CA
  eu:
    address: 0x0999E172
- name: gUnk_09997ED2
  record: Sprite
  oam:
  - [233, 16873, 71]
  - [248, 33273, 75]
  - [16625, 504, 91]
  - [33016, 498, 93]
  us:
    address: 0x09997ED2
  jp:
    address: 0x0994C9E6
  eu:
    address: 0x0999E18E
- name: gUnk_09997EEE
  record: Sprite
  oam:
  - [33008, 494, 95]
  - [240, 33269, 97]
  - [0, 494, 113]
  - [15, 501, 114]
  us:
    address: 0x09997EEE
  jp:
    address: 0x0994CA02
  eu:
    address: 0x0999E1AA
- name: gUnk_09997F0A
  record: Sprite
  oam:
  - [33006, 33269, 115]
  - [33006, 16388, 123]
  - [13, 501, 127]
  us:
    address: 0x09997F0A
  jp:
    address: 0x0994CA1E
  eu:
    address: 0x0999E1C6
- name: gUnk_09997F20
  record: Sprite
  oam:
  - [237, 16395, 128]
  - [245, 33260, 132]
  - [238, 4, 148]
  - [2, 485, 149]
  us:
    address: 0x09997F20
  jp:
    address: 0x0994CA34
  eu:
    address: 0x0999E1DC
- name: gUnk_09997F3C
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x09997F3C
  jp:
    address: 0x0994CA50
  eu:
    address: 0x0999E1F8
- name: gUnk_09997F46
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [1, 7]
  - [2, 7]
  - [3, 7]
  - [4, 7]
  - [5, 7]
  - [6, 7]
  us:
    address: 0x09997F46
  jp:
    address: 0x0994CA5A
  eu:
    address: 0x0999E202
- name: gRoomAssetUs_09997F64
  format: tiles4
  width: 2
  us:
    address: 0x09997F64
    size: 4800
  jp:
    address: 0x0994CA78
    size: 4800
    symbol: gRoomAssetJp_0994CA78
  eu:
    address: 0x0999E220
    size: 4800
    symbol: gRoomAssetEu_0999E220
- name: gUnk_09999224
  record: Sprite
  align: 4
  oam:
  - [228, 33266, 0]
  - [16387, 33266, 16]
  - [16402, 16882, 24]
  us:
    address: 0x09999224
  jp:
    address: 0x0994DD38
  eu:
    address: 0x0999F4E0
- name: gUnk_0999923A
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x0999923A
  jp:
    address: 0x0994DD4E
  eu:
    address: 0x0999F4F6
- name: gRoomAssetUs_09999244
  format: tiles4
  width: 4
  us:
    address: 0x09999244
    size: 896
  jp:
    address: 0x0994DD58
    size: 896
    symbol: gRoomAssetJp_0994DD58
  eu:
    address: 0x0999F500
    size: 896
    symbol: gRoomAssetEu_0999F500
- name: gUnk_099995C4
  record: Sprite
  align: 4
  oam:
  - [16632, 33251, 0]
  - [248, 16386, 8]
  - [16391, 16867, 12]
  - [16391, 2, 16]
  - [233, 16883, 18]
  - [33001, 2, 22]
  - [226, 507, 24]
  us:
    address: 0x099995C4
  jp:
    address: 0x0994E0D8
  eu:
    address: 0x0999F880
- name: gUnk_099995F2
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x099995F2
  jp:
    address: 0x0994E106
  eu:
    address: 0x0999F8AE
- name: gRoomAssetUs_099995FC
  format: tiles4
  width: 1
  us:
    address: 0x099995FC
    size: 800
  jp:
    address: 0x0994E110
    size: 800
    symbol: gRoomAssetJp_0994E110
  eu:
    address: 0x0999F8B8
    size: 800
    symbol: gRoomAssetEu_0999F8B8
- name: gUnk_0999991C
  record: Sprite
  align: 4
  oam:
  - [226, 16895, 0]
  - [219, 7, 4]
  - [234, 504, 5]
  - [16625, 503, 6]
  us:
    address: 0x0999991C
  jp:
    address: 0x0994E430
  eu:
    address: 0x0999FBD8
- name: gUnk_09999938
  record: Sprite
  oam:
  - [227, 16886, 8]
  - [16626, 502, 12]
  - [32988, 5, 14]
  - [235, 5, 16]
  us:
    address: 0x09999938
  jp:
    address: 0x0994E44C
  eu:
    address: 0x0999FBF4
- name: gUnk_09999954
  record: Sprite
  oam:
  - [228, 16888, 17]
  - [16627, 504, 21]
  - [32988, 7, 23]
  - [235, 7, 25]
  us:
    address: 0x09999954
  jp:
    address: 0x0994E468
  eu:
    address: 0x0999FC10
- name: gUnk_09999970
  record: Sprite
  oam:
  - [227, 16891, 26]
  - [16626, 507, 30]
  - [32987, 10, 32]
  - [234, 10, 34]
  us:
    address: 0x09999970
  jp:
    address: 0x0994E484
  eu:
    address: 0x0999FC2C
- name: gUnk_0999998C
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 12]
  - [1, 12]
  - [2, 12]
  - [3, 12]
  us:
    address: 0x0999998C
  jp:
    address: 0x0994E4A0
  eu:
    address: 0x0999FC48
- name: gUnk_099999A2
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x099999A2
  jp:
    address: 0x0994E4B6
  eu:
    address: 0x0999FC5E
- name: gUnk_099999AC
  format: tiles4
  width: 1
  us:
    address: 0x099999AC
    size: 1120
  jp:
    address: 0x0994E4C0
    size: 1120
  eu:
    address: 0x0999FC68
    size: 1120
- name: gRoomAssetUs_09A1E0DC
  format: tilemap
  us:
    address: 0x09A1E0DC
    size: 2048
  jp:
    address: 0x099D2B64
    size: 2048
    symbol: gRoomAssetJp_099D2B64
  eu:
    address: 0x09A6FCA0
    size: 2048
    symbol: gRoomAssetEu_09A6FCA0
- name: gRoomAssetUs_09A1E8DC
  format: tilemap
  us:
    address: 0x09A1E8DC
    size: 2048
  jp:
    address: 0x099D3364
    size: 2048
    symbol: gRoomAssetJp_099D3364
  eu:
    address: 0x09A704A0
    size: 2048
    symbol: gRoomAssetEu_09A704A0
- name: gRoomAssetUs_09A1F0DC
  format: tilemap
  us:
    address: 0x09A1F0DC
    size: 2048
  jp:
    address: 0x099D3B64
    size: 2048
    symbol: gRoomAssetJp_099D3B64
  eu:
    address: 0x09A70CA0
    size: 2048
    symbol: gRoomAssetEu_09A70CA0
- name: gRoomAssetUs_09A1F8DC
  format: tilemap
  us:
    address: 0x09A1F8DC
    size: 4096
  jp:
    address: 0x099D4364
    size: 4096
    symbol: gRoomAssetJp_099D4364
  eu:
    address: 0x09A714A0
    size: 4096
    symbol: gRoomAssetEu_09A714A0
- name: gRoomAssetUs_09A3C75C
  format: palette
  us:
    address: 0x09A3C75C
    size: 320
  jp:
    address: 0x099F11E4
    size: 320
    symbol: gRoomAssetJp_099F11E4
  eu:
    address: 0x09A9A220
    size: 320
    symbol: gRoomAssetEu_09A9A220
