group: sprites_room
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_room.c
    start: 0x09EF9684
    end: 0x09EF9740
  - name: sprites_room_frames.s
    start: 0x0999389C
    end: 0x09999E0C
  - name: sprites_room_maps.s
    start: 0x09A1E0DC
    end: 0x09A208DC
  - name: sprites_room_palettes.s
    start: 0x09A3C75C
    end: 0x09A3C89C
  jp:
  - name: sprites_room.c
    start: 0x09ED0A70
    end: 0x09ED0B2C
  - name: sprites_room_frames.s
    start: 0x099483B0
    end: 0x0994E920
  - name: sprites_room_maps.s
    start: 0x099D2B64
    end: 0x099D5364
  - name: sprites_room_palettes.s
    start: 0x099F11E4
    end: 0x099F1324
  eu:
  - name: sprites_room.c
    start: 0x09F85100
    end: 0x09F851BC
  - name: sprites_room_frames.s
    start: 0x09999B58
    end: 0x099A00C8
  - name: sprites_room_maps.s
    start: 0x09A6FCA0
    end: 0x09A724A0
  - name: sprites_room_palettes.s
    start: 0x09A9A220
    end: 0x09A9A360
entries:
- name: gUnk_09EF9684
  record: SpriteTable
  items: [gUnk_0999389C, gUnk_099938C4, gUnk_099938EC, gUnk_09993914, gUnk_09993942, gUnk_0999395E, gUnk_09993986, gUnk_099939A2]
  us:
    address: 0x09EF9684
  jp:
    address: 0x09ED0A70
  eu:
    address: 0x09F85100
- name: gUnk_09EF96A4
  record: AnimTable
  items: [gUnk_099939C4, gUnk_099939DA, gUnk_099939F0]
  us:
    address: 0x09EF96A4
  jp:
    address: 0x09ED0A90
  eu:
    address: 0x09F85120
- name: gUnk_09EF96B0
  record: SpriteTable
  items: [gUnk_09995E3C, gUnk_09995E46, gUnk_09995E50, gUnk_09995E5A, gUnk_09995E64, gUnk_09995E6E]
  us:
    address: 0x09EF96B0
  jp:
    address: 0x09ED0A9C
  eu:
    address: 0x09F8512C
- name: gUnk_09EF96C8
  record: AnimTable
  items: [gUnk_09995E78, gUnk_09995E82]
  us:
    address: 0x09EF96C8
  jp:
    address: 0x09ED0AB4
  eu:
    address: 0x09F85144
- name: gUnk_09EF96D0
  record: SpriteTable
  items: [gUnk_09996A9C, gUnk_09996AC4, gUnk_09996AE0, gUnk_09996AF6, gUnk_09996B12, gUnk_09996B28, gUnk_09996B3E]
  us:
    address: 0x09EF96D0
  jp:
    address: 0x09ED0ABC
  eu:
    address: 0x09F8514C
- name: gUnk_09EF96EC
  record: AnimTable
  items: [gUnk_09996B5A, gUnk_09996B64]
  us:
    address: 0x09EF96EC
  jp:
    address: 0x09ED0AD8
  eu:
    address: 0x09F85168
- name: gUnk_09EF96F4
  record: SpriteTable
  items: [gUnk_09997E84, gUnk_09997EA0, gUnk_09997EB6, gUnk_09997ED2, gUnk_09997EEE, gUnk_09997F0A, gUnk_09997F20]
  us:
    address: 0x09EF96F4
  jp:
    address: 0x09ED0AE0
  eu:
    address: 0x09F85170
- name: gUnk_09EF9710
  record: AnimTable
  items: [gUnk_09997F3C, gUnk_09997F46]
  us:
    address: 0x09EF9710
  jp:
    address: 0x09ED0AFC
  eu:
    address: 0x09F8518C
- name: gUnk_09EF9718
  record: SpriteTable
  items: [gUnk_09999224]
  us:
    address: 0x09EF9718
  jp:
    address: 0x09ED0B04
  eu:
    address: 0x09F85194
- name: gUnk_09EF971C
  record: AnimTable
  items: [gUnk_0999923A]
  us:
    address: 0x09EF971C
  jp:
    address: 0x09ED0B08
  eu:
    address: 0x09F85198
- name: gUnk_09EF9720
  record: SpriteTable
  items: [gUnk_099995C4]
  us:
    address: 0x09EF9720
  jp:
    address: 0x09ED0B0C
  eu:
    address: 0x09F8519C
- name: gUnk_09EF9724
  record: AnimTable
  items: [gUnk_099995F2]
  us:
    address: 0x09EF9724
  jp:
    address: 0x09ED0B10
  eu:
    address: 0x09F851A0
- name: gUnk_09EF9728
  record: SpriteTable
  items: [gUnk_0999991C, gUnk_09999938, gUnk_09999954, gUnk_09999970]
  us:
    address: 0x09EF9728
  jp:
    address: 0x09ED0B14
  eu:
    address: 0x09F851A4
- name: gUnk_09EF9738
  record: AnimTable
  items: [gUnk_0999998C, gUnk_099999A2]
  us:
    address: 0x09EF9738
  jp:
    address: 0x09ED0B24
  eu:
    address: 0x09F851B4
- name: gRoomAssetUs_099939FA
  format: sprite_sheet
  align: 4
  cell: [54, 71]
  anchor: [26, 38]
  columns: 8
  frames:
  - symbol: gUnk_0999389C
    pieces:
    - [32x64, -17, -38]
    - [8x8, -24, -23, {layer: 1}]
    - [8x16, -24, 10]
    - [8x8, -1, 25]
    - [16x32, 7, -6]
    - [16x16, -25, -38]
  - symbol: gUnk_099938C4
    pieces:
    - [32x64, -18, -37]
    - [8x8, -25, 14]
    - [8x8, -25, -22, {layer: 1}]
    - [8x32, 13, -5]
    - [8x16, 20, 1]
    - [16x16, -26, -37]
  - symbol: gUnk_099938EC
    pieces:
    - [32x64, -15, -37]
    - [8x16, -22, -37]
    - [8x8, -22, -22]
    - [8x16, -22, 5]
    - [8x16, 16, -1]
    - [8x8, 16, 14]
  - symbol: gUnk_09993914
    pieces:
    - [32x64, -12, -38]
    - [8x16, -19, -37]
    - [8x8, -19, -22]
    - [8x16, -19, 2]
    - [8x8, -19, 17]
    - [8x8, -4, 25]
    - [8x16, 19, 2]
  - symbol: gUnk_09993942
    pieces:
    - [32x64, -17, -37]
    - [8x16, -24, 3]
    - [8x8, -24, 18]
    - [8x16, 14, 1, {layer: 1}]
  - symbol: gUnk_0999395E
    pieces:
    - [8x16, -23, 4]
    - [8x16, 15, 4]
    - [32x32, -16, -12]
    - [32x16, -24, -34]
    - [16x16, 7, -34]
    - [32x8, -16, -19]
  - symbol: gUnk_09993986
    pieces:
    - [32x64, -15, -37, {hflip: true}]
    - [8x16, 16, 3, {hflip: true}]
    - [8x8, 16, 18, {hflip: true}]
    - [8x16, -22, 1, {hflip: true, same: [4, 3]}]
  - symbol: gUnk_099939A2
    pieces:
    - [32x64, -16, -34]
    - [8x32, -23, -2]
    - [8x32, 15, -2]
    - [8x16, -23, -34]
    - [8x16, 15, -34]
  animations:
  - symbol: gUnk_099939C4
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 12], [1, 12], [2, 12], [3, 12]]
  - symbol: gUnk_099939DA
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 5], [5, 5], [6, 5], [7, 5]]
  - symbol: gUnk_099939F0
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x0999389C
    size: 9630
  jp:
    address: 0x099483B0
    size: 9630
    symbol: gRoomAssetJp_0994850E
  eu:
    address: 0x09999B58
    size: 9630
    symbol: gRoomAssetEu_09999CB6
- name: gRoomAssetUs_09995E9C
  format: sprite_sheet
  align: 4
  cell: [32, 32]
  anchor: [16, 18]
  columns: 6
  frames:
  - symbol: gUnk_09995E3C
    pieces:
    - [32x32, -16, -18]
  - symbol: gUnk_09995E46
    pieces:
    - [32x32, -16, -18]
  - symbol: gUnk_09995E50
    pieces:
    - [32x32, -16, -18]
  - symbol: gUnk_09995E5A
    pieces:
    - [32x32, -16, -18]
  - symbol: gUnk_09995E64
    pieces:
    - [32x32, -16, -18]
  - symbol: gUnk_09995E6E
    pieces:
    - [32x32, -16, -18]
  animations:
  - symbol: gUnk_09995E78
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  - symbol: gUnk_09995E82
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 6], [2, 6], [3, 6], [4, 6], [5, 6]]
  us:
    address: 0x09995E3C
    size: 3168
  jp:
    address: 0x0994A950
    size: 3168
    symbol: gRoomAssetJp_0994A9B0
  eu:
    address: 0x0999C0F8
    size: 3168
    symbol: gRoomAssetEu_0999C158
- name: gRoomAssetUs_09996B82
  format: sprite_sheet
  align: 4
  cell: [61, 58]
  anchor: [33, 26]
  columns: 7
  frames:
  - symbol: gUnk_09996A9C
    pieces:
    - [16x16, 6, -23]
    - [32x32, -26, -7]
    - [8x16, 5, -8, {layer: 1}]
    - [8x8, -1, -14, {layer: 2}]
    - [8x8, -33, 9]
    - [8x8, -18, 24]
  - symbol: gUnk_09996AC4
    pieces:
    - [16x16, -1, -24]
    - [32x32, -17, -9]
    - [16x8, -17, 22]
    - [8x8, -2, 22]
  - symbol: gUnk_09996AE0
    pieces:
    - [16x16, -14, -26]
    - [32x32, -14, -11]
    - [32x8, -14, 20]
  - symbol: gUnk_09996AF6
    pieces:
    - [16x16, -26, -17]
    - [32x32, -11, -9]
    - [8x8, -11, -16]
    - [8x16, 20, -1]
  - symbol: gUnk_09996B12
    pieces:
    - [16x32, -12, -20]
    - [8x32, 3, -20]
    - [16x8, -5, 11, {layer: 1}]
  - symbol: gUnk_09996B28
    pieces:
    - [8x16, 10, -17]
    - [32x32, -21, -17]
    - [8x8, 3, 14]
  - symbol: gUnk_09996B3E
    pieces:
    - [16x16, 7, -23]
    - [32x32, -25, -7]
    - [8x16, 6, -8]
    - [16x8, -8, -14, {layer: 1}]
  animations:
  - symbol: gUnk_09996B5A
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  - symbol: gUnk_09996B64
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7]]
  us:
    address: 0x09996A9C
    size: 5094
  jp:
    address: 0x0994B5B0
    size: 5094
    symbol: gRoomAssetJp_0994B696
  eu:
    address: 0x0999CD58
    size: 5094
    symbol: gRoomAssetEu_0999CE3E
- name: gRoomAssetUs_09997F64
  format: sprite_sheet
  align: 4
  cell: [54, 57]
  anchor: [27, 28]
  columns: 7
  frames:
  - symbol: gUnk_09997E84
    pieces:
    - [16x16, 7, -23]
    - [32x32, -24, -7]
    - [8x16, 7, -8]
    - [16x8, -8, -14]
  - symbol: gUnk_09997EA0
    pieces:
    - [16x16, 2, -28]
    - [32x32, -14, -13]
    - [32x8, -14, 18]
  - symbol: gUnk_09997EB6
    pieces:
    - [16x16, -15, -25]
    - [32x32, -15, -10]
    - [16x8, -7, 21]
    - [8x8, 9, 21]
  - symbol: gUnk_09997ED2
    pieces:
    - [16x16, -23, -23]
    - [32x32, -7, -8]
    - [16x8, -8, -15]
    - [8x16, -14, -8]
  - symbol: gUnk_09997EEE
    pieces:
    - [8x16, -18, -16]
    - [32x32, -11, -16]
    - [8x8, -18, 0]
    - [8x8, -11, 15]
  - symbol: gUnk_09997F0A
    pieces:
    - [16x32, -11, -18]
    - [8x32, 4, -18]
    - [8x8, -11, 13]
  - symbol: gUnk_09997F20
    pieces:
    - [16x16, 11, -19]
    - [32x32, -20, -11]
    - [8x8, 4, -18]
    - [8x8, -27, 2]
  animations:
  - symbol: gUnk_09997F3C
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  - symbol: gUnk_09997F46
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7]]
  us:
    address: 0x09997E84
    size: 5024
  jp:
    address: 0x0994C998
    size: 5024
    symbol: gRoomAssetJp_0994CA78
  eu:
    address: 0x0999E140
    size: 5024
    symbol: gRoomAssetEu_0999E220
- name: gRoomAssetUs_09999244
  format: sprite_sheet
  align: 4
  cell: [32, 54]
  anchor: [14, 28]
  columns: 1
  frames:
  - symbol: gUnk_09999224
    pieces:
    - [32x32, -14, -28]
    - [32x16, -14, 3]
    - [32x8, -14, 18]
  animations:
  - symbol: gUnk_0999923A
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x09999224
    size: 928
  jp:
    address: 0x0994DD38
    size: 928
    symbol: gRoomAssetJp_0994DD58
  eu:
    address: 0x0999F4E0
    size: 928
    symbol: gRoomAssetEu_0999F500
- name: gRoomAssetUs_099995FC
  format: sprite_sheet
  align: 4
  cell: [47, 45]
  anchor: [29, 30]
  columns: 1
  frames:
  - symbol: gUnk_099995C4
    pieces:
    - [32x16, -29, -8]
    - [16x16, 2, -8]
    - [32x8, -29, 7]
    - [16x8, 2, 7]
    - [16x16, -13, -23]
    - [8x16, 2, -23, {layer: 1}]
    - [8x8, -5, -30]
  animations:
  - symbol: gUnk_099995F2
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x099995C4
    size: 856
  jp:
    address: 0x0994E0D8
    size: 856
    symbol: gRoomAssetJp_0994E110
  eu:
    address: 0x0999F880
    size: 856
    symbol: gRoomAssetEu_0999F8B8
- name: gUnk_099999AC
  format: sprite_sheet
  align: 4
  cell: [28, 32]
  anchor: [10, 37]
  columns: 4
  frames:
  - symbol: gUnk_0999991C
    pieces:
    - [16x16, -1, -30]
    - [8x8, 7, -37]
    - [8x8, -8, -22, {layer: 1}]
    - [16x8, -9, -15, {layer: 2}]
  - symbol: gUnk_09999938
    pieces:
    - [16x16, -10, -29]
    - [16x8, -10, -14]
    - [8x16, 5, -36]
    - [8x8, 5, -21]
  - symbol: gUnk_09999954
    pieces:
    - [16x16, -8, -28]
    - [16x8, -8, -13]
    - [8x16, 7, -36]
    - [8x8, 7, -21]
  - symbol: gUnk_09999970
    pieces:
    - [16x16, -5, -29]
    - [16x8, -5, -14]
    - [8x16, 10, -37]
    - [8x8, 10, -22]
  animations:
  - symbol: gUnk_0999998C
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 12], [1, 12], [2, 12], [3, 12]]
  - symbol: gUnk_099999A2
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x0999991C
    size: 1264
  jp:
    address: 0x0994E430
    size: 1264
  eu:
    address: 0x0999FBD8
    size: 1264
- name: gRoomAssetUs_09A1E0DC
  format: tilemap
  us:
    address: 0x09A1E0DC
    size: 2048
  jp:
    address: 0x099D2B64
    size: 2048
    symbol: gRoomAssetJp_099D2B64
  eu:
    address: 0x09A6FCA0
    size: 2048
    symbol: gRoomAssetEu_09A6FCA0
- name: gRoomAssetUs_09A1E8DC
  format: tilemap
  us:
    address: 0x09A1E8DC
    size: 2048
  jp:
    address: 0x099D3364
    size: 2048
    symbol: gRoomAssetJp_099D3364
  eu:
    address: 0x09A704A0
    size: 2048
    symbol: gRoomAssetEu_09A704A0
- name: gRoomAssetUs_09A1F0DC
  format: tilemap
  us:
    address: 0x09A1F0DC
    size: 2048
  jp:
    address: 0x099D3B64
    size: 2048
    symbol: gRoomAssetJp_099D3B64
  eu:
    address: 0x09A70CA0
    size: 2048
    symbol: gRoomAssetEu_09A70CA0
- name: gRoomAssetUs_09A1F8DC
  format: tilemap
  us:
    address: 0x09A1F8DC
    size: 4096
  jp:
    address: 0x099D4364
    size: 4096
    symbol: gRoomAssetJp_099D4364
  eu:
    address: 0x09A714A0
    size: 4096
    symbol: gRoomAssetEu_09A714A0
- name: gRoomAssetUs_09A3C75C
  format: palette
  us:
    address: 0x09A3C75C
    size: 320
  jp:
    address: 0x099F11E4
    size: 320
    symbol: gRoomAssetJp_099F11E4
  eu:
    address: 0x09A9A220
    size: 320
    symbol: gRoomAssetEu_09A9A220
