group: sprites_language_select
types:
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us: []
  jp: []
  eu:
  - name: sprites_language_select_frames.s
    start: 0x08C9C97C
    end: 0x08C9CBF8
entries:
- name: gUnkEu_08C9C97C
  record: Sprite
  oam:
  - [16622, 496, 0]
  - [33014, 496, 2]
  - [16638, 16888, 4]
  - [254, 49, 8]
  - [16638, 16402, 9]
  eu:
    address: 0x08C9C97C
- name: gUnkEu_08C9C99E
  record: Sprite
  oam:
  - [16622, 494, 0]
  - [33014, 494, 2]
  - [16638, 16886, 4]
  - [254, 50, 8]
  - [16638, 16405, 9]
  eu:
    address: 0x08C9C99E
- name: gUnkEu_08C9C9C0
  record: Sprite
  oam:
  - [16622, 492, 0]
  - [33014, 492, 2]
  - [16638, 16884, 4]
  - [254, 52, 8]
  - [16638, 16404, 9]
  eu:
    address: 0x08C9C9C0
- name: gUnkEu_08C9C9E2
  record: Sprite
  oam:
  - [16622, 495, 0]
  - [33014, 495, 2]
  - [16638, 16887, 4]
  - [254, 49, 8]
  - [16638, 16401, 9]
  eu:
    address: 0x08C9C9E2
- name: gUnkEu_08C9CA04
  record: Sprite
  oam:
  - [16622, 494, 0]
  - [33014, 494, 2]
  - [16638, 16886, 4]
  - [254, 50, 8]
  - [16638, 16402, 9]
  eu:
    address: 0x08C9CA04
- name: gUnkEu_08C9CA26
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  declare: false
  eu:
    address: 0x08C9CA26
- name: gUnkEu_08C9CA30
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [1, 4]
  declare: false
  eu:
    address: 0x08C9CA30
- name: gUnkEu_08C9CA3A
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [2, 4]
  declare: false
  eu:
    address: 0x08C9CA3A
- name: gUnkEu_08C9CA44
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [3, 4]
  declare: false
  eu:
    address: 0x08C9CA44
- name: gUnkEu_08C9CA4E
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [4, 4]
  declare: false
  eu:
    address: 0x08C9CA4E
- name: gUnkEu_08C9CA58
  format: tiles4
  eu:
    address: 0x08C9CA58
    size: 416
