group: sprites_mode_test
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_mode_test_1.c
    start: 0x09EE14D4
    end: 0x09EE1520
  - name: sprites_mode_test_2.c
    start: 0x09EEC660
    end: 0x09EEC670
  - name: sprites_mode_test_frames_1.s
    start: 0x08B24C98
    end: 0x08B2556C
  - name: sprites_mode_test_frames_2.s
    start: 0x090D7C50
    end: 0x090D7E04
  jp:
  - name: sprites_mode_test_1.c
    start: 0x09EB8F50
    end: 0x09EB8F9C
  - name: sprites_mode_test_2.c
    start: 0x09EC3A4C
    end: 0x09EC3A5C
  - name: sprites_mode_test_frames_1.s
    start: 0x08B18280
    end: 0x08B18B54
  - name: sprites_mode_test_frames_2.s
    start: 0x09093178
    end: 0x0909332C
  eu:
  - name: sprites_mode_test.c
    start: 0x09F77844
    end: 0x09F77854
  - name: sprites_mode_test_frames.s
    start: 0x091A72D8
    end: 0x091A748C
entries:
- name: gUnk_09EE14D4
  record: SpriteTable
  items: [gUnk_08B24C98, gUnk_08B24CA2, gUnk_08B24CB2, gUnk_08B24CC2, gUnk_08B24CD2, gUnk_08B24CE2, gUnk_08B24CF8, gUnk_08B24D0E, gUnk_08B24D18, gUnk_08B24D22, gUnk_08B24D2C, gUnk_08B24D42, gUnk_08B24D58, gUnk_08B24D6E]
  us:
    address: 0x09EE14D4
  jp:
    address: 0x09EB8F50
- name: gUnk_09EE150C
  record: AnimTable
  items: [gUnk_08B24D78, gUnk_08B24D82, gUnk_08B24D8C, gUnk_08B24D96, gUnk_08B24DA0]
  us:
    address: 0x09EE150C
  jp:
    address: 0x09EB8F88
- name: gUnk_09EEC660
  record: SpriteTable
  items: [gUnk_090D7C50, gUnk_090D7C5A, gUnk_090D7C64]
  us:
    address: 0x09EEC660
  jp:
    address: 0x09EC3A4C
  eu:
    address: 0x09F77844
- name: gUnk_09EEC66C
  record: AnimTable
  items: [gUnk_090D7C6E]
  us:
    address: 0x09EEC66C
  jp:
    address: 0x09EC3A58
  eu:
    address: 0x09F77850
- name: b_hpgag_e
  format: sprite_sheet
  palette: b_states
  symbol: gUnk_08B24DAA
  align: 4
  cell: [80, 12]
  anchor: [80, 4]
  columns: 8
  frames:
  - symbol: gUnk_08B24C98
    pieces:
    - [32x8, -32, -4]
  - symbol: gUnk_08B24CA2
    pieces:
    - [32x8, -32, 0]
    - [8x8, -40, 0, {hflip: true}]
  - symbol: gUnk_08B24CB2
    pieces:
    - [32x8, -32, 0]
    - [16x8, -48, 0, {hflip: true}]
  - symbol: gUnk_08B24CC2
    pieces:
    - [32x8, -32, 0]
    - [32x8, -56, 0, {hflip: true}]
  - symbol: gUnk_08B24CD2
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0, {hflip: true}]
  - symbol: gUnk_08B24CE2
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0, {hflip: true}]
    - [8x8, -72, 0, {hflip: true}]
  - symbol: gUnk_08B24CF8
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0]
    - [16x8, -80, 0, {hflip: true}]
  - symbol: gUnk_08B24D0E
    pieces:
    - [32x8, -32, -4]
  - symbol: gUnk_08B24D18
    pieces:
    - [32x8, -32, -4]
  - symbol: gUnk_08B24D22
    pieces:
    - [32x8, -32, -4]
  - symbol: gUnk_08B24D2C
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0]
    - [16x8, -80, 0, {hflip: true}]
  - symbol: gUnk_08B24D42
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0]
    - [16x8, -80, 0]
  - symbol: gUnk_08B24D58
    pieces:
    - [32x8, -32, 0]
    - [32x8, -64, 0]
    - [16x8, -80, 0]
  - symbol: gUnk_08B24D6E
    pieces:
    - [8x8, -24, 0]
  animations:
  - symbol: gUnk_08B24D78
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  - symbol: gUnk_08B24D82
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 4]]
  - symbol: gUnk_08B24D8C
    fields: {unk_00: 64, unk_02: 64}
    frames: [[2, 4]]
  - symbol: gUnk_08B24D96
    fields: {unk_00: 64, unk_02: 64}
    frames: [[3, 4]]
  - symbol: gUnk_08B24DA0
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 4]]
  us:
    address: 0x08B24C98
    size: 2258
  jp:
    address: 0x08B18280
    size: 2258
- name: gUnk_090D7C84
  format: sprite_sheet
  align: 4
  cell: [16, 16]
  anchor: [8, 8]
  columns: 3
  frames:
  - symbol: gUnk_090D7C50
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_090D7C5A
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_090D7C64
    pieces:
    - [16x16, -8, -8]
  animations:
  - symbol: gUnk_090D7C6E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 10], [2, 10], [1, 10], [0, 10]]
  us:
    address: 0x090D7C50
    size: 436
  jp:
    address: 0x09093178
    size: 436
  eu:
    address: 0x091A72D8
    size: 436