group: sprites_language_select
types:
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us: []
  jp: []
  eu:
  - name: sprites_language_select_frames.s
    start: 0x08C9C97C
    end: 0x08C9CBF8
  - name: sprites_language_select_palettes.s
    start: 0x08F6A6FC
    end: 0x08F6A73C
  - name: sprites_language_select_tiles.s
    start: 0x08F77180
    end: 0x08F79038
  - name: sprites_language_select_maps.s
    start: 0x08F7EBF8
    end: 0x08F7F15C
entries:
- name: gUnkEu_08C9CA58
  format: sprite_sheet
  cell: [80, 24]
  anchor: [20, 18]
  columns: 5
  frames:
  - symbol: gUnkEu_08C9C97C
    pieces:
    - [16x8, -16, -18]
    - [8x16, -16, -10]
    - [32x8, -8, -2]
    - [8x8, 49, -2]
    - [32x8, 18, -2]
  - symbol: gUnkEu_08C9C99E
    pieces:
    - [16x8, -18, -18]
    - [8x16, -18, -10]
    - [32x8, -10, -2]
    - [8x8, 50, -2]
    - [32x8, 21, -2, {same: [0, 4]}]
  - symbol: gUnkEu_08C9C9C0
    pieces:
    - [16x8, -20, -18]
    - [8x16, -20, -10]
    - [32x8, -12, -2]
    - [8x8, 52, -2]
    - [32x8, 20, -2]
  - symbol: gUnkEu_08C9C9E2
    pieces:
    - [16x8, -17, -18]
    - [8x16, -17, -10]
    - [32x8, -9, -2]
    - [8x8, 49, -2]
    - [32x8, 17, -2]
  - symbol: gUnkEu_08C9CA04
    pieces:
    - [16x8, -18, -18]
    - [8x16, -18, -10]
    - [32x8, -10, -2]
    - [8x8, 50, -2]
    - [32x8, 18, -2]
  animations:
  - symbol: gUnkEu_08C9CA26
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  - symbol: gUnkEu_08C9CA30
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 4]]
  - symbol: gUnkEu_08C9CA3A
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[2, 4]]
  - symbol: gUnkEu_08C9CA44
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[3, 4]]
  - symbol: gUnkEu_08C9CA4E
    declare: false
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 4]]
  eu:
    address: 0x08C9C97C
    size: 636
- name: gUnkEu_08F6A6FC
  format: palette
  eu:
    address: 0x08F6A6FC
    size: 64
- name: gUnkEu_08F77180
  format: tiles4
  width: 2
  eu:
    address: 0x08F77180
    size: 7864
    compress: lz77
- name: gUnkEu_08F7EBF8
  format: tilemap
  eu:
    address: 0x08F7EBF8
    size: 952
    compress: lz77
- name: gUnkEu_08F7EFB0
  format: tilemap
  eu:
    address: 0x08F7EFB0
    size: 428
    compress: lz77
