group: sprites_card
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_card.c
    start: 0x09EEAF4C
    end: 0x09EEAFD4
  - name: sprites_card_frames.s
    start: 0x090A0ACC
    end: 0x090A1F88
  jp:
  - name: sprites_card.c
    start: 0x09EC2340
    end: 0x09EC23C8
  - name: sprites_card_frames.s
    start: 0x0905C33C
    end: 0x0905D7F8
  eu:
  - name: sprites_card.c
    start: 0x09F76FBC
    end: 0x09F77044
  - name: sprites_card_frames.s
    start: 0x09186528
    end: 0x091879E4
entries:
- name: gUnk_09EEAF4C
  record: SpriteTable
  items: [gUnk_090A0ACC, gUnk_090A0ADC, gUnk_090A0AE6, gUnk_090A0AF0, gUnk_090A0AFA, gUnk_090A0B04, gUnk_090A0B0E, gUnk_090A0B18, gUnk_090A0B22, gUnk_090A0B2C, gUnk_090A0B36, gUnk_090A0B40, gUnk_090A0B4A, gUnk_090A0B54, gUnk_090A0B5E, gUnk_090A0B68, gUnk_090A0B72, gUnk_090A0B7C, gUnk_090A0B86, gUnk_090A0B90, gUnk_090A0B9A, gUnk_090A0BA4, gUnk_090A0BAE, gUnk_090A0BB8, gUnk_090A0BC2]
  us:
    address: 0x09EEAF4C
  jp:
    address: 0x09EC2340
  eu:
    address: 0x09F76FBC
- name: gUnk_09EEAFB0
  record: AnimTable
  items: [gUnk_090A0BCC, gUnk_090A0BD6, gUnk_090A0BEC, gUnk_090A0C02, gUnk_090A0C18, gUnk_090A0C2E, gUnk_090A0C44, gUnk_090A0C5A, gUnk_090A0C70]
  us:
    address: 0x09EEAFB0
  jp:
    address: 0x09EC23A4
  eu:
    address: 0x09F77020
- name: gUnk_090A0ACC
  record: Sprite
  align: 4
  oam:
  - [236, 33264, 0]
  - [16395, 16880, 16]
  us:
    address: 0x090A0ACC
  jp:
    address: 0x0905C33C
  eu:
    address: 0x09186528
- name: gUnk_090A0ADC
  record: Sprite
  oam:
  - [224, 33264, 20]
  us:
    address: 0x090A0ADC
  jp:
    address: 0x0905C34C
  eu:
    address: 0x09186538
- name: gUnk_090A0AE6
  record: Sprite
  oam:
  - [224, 33264, 36]
  us:
    address: 0x090A0AE6
  jp:
    address: 0x0905C356
  eu:
    address: 0x09186542
- name: gUnk_090A0AF0
  record: Sprite
  oam:
  - [224, 33264, 52]
  us:
    address: 0x090A0AF0
  jp:
    address: 0x0905C360
  eu:
    address: 0x0918654C
- name: gUnk_090A0AFA
  record: Sprite
  oam:
  - [16624, 16880, 68]
  us:
    address: 0x090A0AFA
  jp:
    address: 0x0905C36A
  eu:
    address: 0x09186556
- name: gUnk_090A0B04
  record: Sprite
  oam:
  - [16624, 16880, 72]
  us:
    address: 0x090A0B04
  jp:
    address: 0x0905C374
  eu:
    address: 0x09186560
- name: gUnk_090A0B0E
  record: Sprite
  oam:
  - [16624, 16880, 76]
  us:
    address: 0x090A0B0E
  jp:
    address: 0x0905C37E
  eu:
    address: 0x0918656A
- name: gUnk_090A0B18
  record: Sprite
  oam:
  - [16624, 16880, 80]
  us:
    address: 0x090A0B18
  jp:
    address: 0x0905C388
  eu:
    address: 0x09186574
- name: gUnk_090A0B22
  record: Sprite
  oam:
  - [16624, 16880, 84]
  us:
    address: 0x090A0B22
  jp:
    address: 0x0905C392
  eu:
    address: 0x0918657E
- name: gUnk_090A0B2C
  record: Sprite
  oam:
  - [16624, 16880, 88]
  us:
    address: 0x090A0B2C
  jp:
    address: 0x0905C39C
  eu:
    address: 0x09186588
- name: gUnk_090A0B36
  record: Sprite
  oam:
  - [16624, 16880, 92]
  us:
    address: 0x090A0B36
  jp:
    address: 0x0905C3A6
  eu:
    address: 0x09186592
- name: gUnk_090A0B40
  record: Sprite
  oam:
  - [16624, 16880, 96]
  us:
    address: 0x090A0B40
  jp:
    address: 0x0905C3B0
  eu:
    address: 0x0918659C
- name: gUnk_090A0B4A
  record: Sprite
  oam:
  - [16624, 16880, 100]
  us:
    address: 0x090A0B4A
  jp:
    address: 0x0905C3BA
  eu:
    address: 0x091865A6
- name: gUnk_090A0B54
  record: Sprite
  oam:
  - [16624, 16880, 104]
  us:
    address: 0x090A0B54
  jp:
    address: 0x0905C3C4
  eu:
    address: 0x091865B0
- name: gUnk_090A0B5E
  record: Sprite
  oam:
  - [16624, 16880, 108]
  us:
    address: 0x090A0B5E
  jp:
    address: 0x0905C3CE
  eu:
    address: 0x091865BA
- name: gUnk_090A0B68
  record: Sprite
  oam:
  - [16624, 16880, 112]
  us:
    address: 0x090A0B68
  jp:
    address: 0x0905C3D8
  eu:
    address: 0x091865C4
- name: gUnk_090A0B72
  record: Sprite
  oam:
  - [16624, 16880, 116]
  us:
    address: 0x090A0B72
  jp:
    address: 0x0905C3E2
  eu:
    address: 0x091865CE
- name: gUnk_090A0B7C
  record: Sprite
  oam:
  - [16624, 16880, 120]
  us:
    address: 0x090A0B7C
  jp:
    address: 0x0905C3EC
  eu:
    address: 0x091865D8
- name: gUnk_090A0B86
  record: Sprite
  oam:
  - [16624, 16880, 124]
  us:
    address: 0x090A0B86
  jp:
    address: 0x0905C3F6
  eu:
    address: 0x091865E2
- name: gUnk_090A0B90
  record: Sprite
  oam:
  - [16624, 16880, 128]
  us:
    address: 0x090A0B90
  jp:
    address: 0x0905C400
  eu:
    address: 0x091865EC
- name: gUnk_090A0B9A
  record: Sprite
  oam:
  - [16624, 16880, 132]
  us:
    address: 0x090A0B9A
  jp:
    address: 0x0905C40A
  eu:
    address: 0x091865F6
- name: gUnk_090A0BA4
  record: Sprite
  oam:
  - [16624, 16880, 136]
  us:
    address: 0x090A0BA4
  jp:
    address: 0x0905C414
  eu:
    address: 0x09186600
- name: gUnk_090A0BAE
  record: Sprite
  oam:
  - [16624, 16880, 140]
  us:
    address: 0x090A0BAE
  jp:
    address: 0x0905C41E
  eu:
    address: 0x0918660A
- name: gUnk_090A0BB8
  record: Sprite
  oam:
  - [16624, 16880, 144]
  us:
    address: 0x090A0BB8
  jp:
    address: 0x0905C428
  eu:
    address: 0x09186614
- name: gUnk_090A0BC2
  record: Sprite
  oam:
  - [16624, 16880, 148]
  us:
    address: 0x090A0BC2
  jp:
    address: 0x0905C432
  eu:
    address: 0x0918661E
- name: gUnk_090A0BCC
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x090A0BCC
  jp:
    address: 0x0905C43C
  eu:
    address: 0x09186628
- name: gUnk_090A0BD6
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [1, 1]
  - [2, 4]
  - [3, 5]
  - [2, 3]
  us:
    address: 0x090A0BD6
  jp:
    address: 0x0905C446
  eu:
    address: 0x09186632
- name: gUnk_090A0BEC
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [4, 1]
  - [5, 4]
  - [6, 5]
  - [5, 3]
  us:
    address: 0x090A0BEC
  jp:
    address: 0x0905C45C
  eu:
    address: 0x09186648
- name: gUnk_090A0C02
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [7, 1]
  - [8, 4]
  - [9, 5]
  - [8, 3]
  us:
    address: 0x090A0C02
  jp:
    address: 0x0905C472
  eu:
    address: 0x0918665E
- name: gUnk_090A0C18
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [10, 1]
  - [11, 4]
  - [12, 5]
  - [11, 3]
  us:
    address: 0x090A0C18
  jp:
    address: 0x0905C488
  eu:
    address: 0x09186674
- name: gUnk_090A0C2E
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [13, 1]
  - [14, 4]
  - [15, 5]
  - [14, 3]
  us:
    address: 0x090A0C2E
  jp:
    address: 0x0905C49E
  eu:
    address: 0x0918668A
- name: gUnk_090A0C44
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [16, 1]
  - [17, 4]
  - [18, 5]
  - [17, 3]
  us:
    address: 0x090A0C44
  jp:
    address: 0x0905C4B4
  eu:
    address: 0x091866A0
- name: gUnk_090A0C5A
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [19, 1]
  - [20, 4]
  - [21, 5]
  - [20, 3]
  us:
    address: 0x090A0C5A
  jp:
    address: 0x0905C4CA
  eu:
    address: 0x091866B6
- name: gUnk_090A0C70
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [22, 1]
  - [23, 4]
  - [24, 5]
  - [23, 3]
  us:
    address: 0x090A0C70
  jp:
    address: 0x0905C4E0
  eu:
    address: 0x091866CC
- name: ri_card_f0_red
  format: tiles4
  width: 4
  palette: card_00
  symbol: gUnk_090A0C86
  us:
    address: 0x090A0C86
    size: 4864
  jp:
    address: 0x0905C4F6
    size: 4864
  eu:
    address: 0x091866E2
    size: 4864
