group: sprites_smn
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_smn.c
    start: 0x09EDE790
    end: 0x09EDE8CC
  - name: sprites_smn_frames.s
    start: 0x088A4A3C
    end: 0x088B629C
  jp:
  - name: sprites_smn.c
    start: 0x09EB620C
    end: 0x09EB6348
  - name: sprites_smn_frames.s
    start: 0x08898024
    end: 0x088A9884
  eu:
  - name: sprites_smn.c
    start: 0x09F593E8
    end: 0x09F59524
  - name: sprites_smn_frames.s
    start: 0x088D0360
    end: 0x088E1BC0
entries:
- name: gUnk_09EDE790
  record: SpriteTable
  items: [gUnk_088A4A3C, gUnk_088A4A52, gUnk_088A4A68, gUnk_088A4A7E, gUnk_088A4A8E, gUnk_088A4A98, gUnk_088A4AA2]
  us:
    address: 0x09EDE790
  jp:
    address: 0x09EB620C
  eu:
    address: 0x09F593E8
- name: gUnk_09EDE7AC
  record: SpriteTable
  scalar: true
  items: [gUnk_088A4AAC]
  us:
    address: 0x09EDE7AC
  jp:
    address: 0x09EB6228
  eu:
    address: 0x09F59404
- name: gUnk_09EDE7B0
  record: AnimTable
  items: [gUnk_088A4ABC]
  us:
    address: 0x09EDE7B0
  jp:
    address: 0x09EB622C
  eu:
    address: 0x09F59408
- name: gUnk_09EDE7B4
  record: SpriteTable
  items: [gUnk_088A5CC0, gUnk_088A5CCA, gUnk_088A5CD4, gUnk_088A5CDE, gUnk_088A5CE8, gUnk_088A5CF2, gUnk_088A5CFC, gUnk_088A5D06, gUnk_088A5D10, gUnk_088A5D1A, gUnk_088A5D24, gUnk_088A5D2E]
  us:
    address: 0x09EDE7B4
  jp:
    address: 0x09EB6230
  eu:
    address: 0x09F5940C
- name: gUnk_09EDE7E4
  record: AnimTable
  items: [gUnk_088A5D38, gUnk_088A5D4E, gUnk_088A5D64]
  us:
    address: 0x09EDE7E4
  jp:
    address: 0x09EB6260
  eu:
    address: 0x09F5943C
- name: gUnk_09EDE7F0
  record: SpriteTable
  items: [gUnk_088A5F7C, gUnk_088A5F8C, gUnk_088A5F9C, gUnk_088A5FAC, gUnk_088A5FBC, gUnk_088A5FCC, gUnk_088A5FDC, gUnk_088A5FEC]
  us:
    address: 0x09EDE7F0
  jp:
    address: 0x09EB626C
  eu:
    address: 0x09F59448
- name: gUnk_09EDE810
  record: AnimTable
  items: [gUnk_088A5FFC]
  us:
    address: 0x09EDE810
  jp:
    address: 0x09EB628C
  eu:
    address: 0x09F59468
- name: gUnk_09EDE814
  record: SpriteTable
  items: [gUnk_088AAA24, gUnk_088AAA3A, gUnk_088AAA50, gUnk_088AAA60, gUnk_088AAA70, gUnk_088AAA7A, gUnk_088AAA8A, gUnk_088AAA9A]
  us:
    address: 0x09EDE814
  jp:
    address: 0x09EB6290
  eu:
    address: 0x09F5946C
- name: gUnk_09EDE834
  record: AnimTable
  items: [gUnk_088AAAA4, gUnk_088AAACE, gUnk_088AAAF8, gUnk_088AAB0A, gUnk_088AAB20]
  us:
    address: 0x09EDE834
  jp:
    address: 0x09EB62B0
  eu:
    address: 0x09F5948C
- name: gUnk_09EDE848
  record: SpriteTable
  items: [gUnk_088ABEF4, gUnk_088ABEFE, gUnk_088ABF08, gUnk_088ABF12, gUnk_088ABF1C, gUnk_088ABF26, gUnk_088ABF30, gUnk_088ABF3A, gUnk_088ABF44]
  us:
    address: 0x09EDE848
  jp:
    address: 0x09EB62C4
  eu:
    address: 0x09F594A0
- name: gUnk_09EDE86C
  record: AnimTable
  items: [gUnk_088ABF4E, gUnk_088ABF5C, gUnk_088ABF7A]
  us:
    address: 0x09EDE86C
  jp:
    address: 0x09EB62E8
  eu:
    address: 0x09F594C4
- name: gUnk_09EDE878
  record: SpriteTable
  items: [gUnk_088B0788, gUnk_088B079E, gUnk_088B07AE, gUnk_088B07BE, gUnk_088B07CE, gUnk_088B07F0, gUnk_088B0812, gUnk_088B082E]
  us:
    address: 0x09EDE878
  jp:
    address: 0x09EB62F4
  eu:
    address: 0x09F594D0
- name: gUnk_09EDE898
  record: AnimTable
  items: [gUnk_088B0850, gUnk_088B085A]
  us:
    address: 0x09EDE898
  jp:
    address: 0x09EB6314
  eu:
    address: 0x09F594F0
- name: gUnk_09EDE8A0
  record: SpriteTable
  items: [gUnk_088B49BC, gUnk_088B49CC, gUnk_088B49DC, gUnk_088B49EC, gUnk_088B49FC, gUnk_088B4A0C, gUnk_088B4A22, gUnk_088B4A38]
  us:
    address: 0x09EDE8A0
  jp:
    address: 0x09EB631C
  eu:
    address: 0x09F594F8
- name: gUnk_09EDE8C0
  record: AnimTable
  items: [gUnk_088B4A4E, gUnk_088B4A74, gUnk_088B4A7E]
  us:
    address: 0x09EDE8C0
  jp:
    address: 0x09EB633C
  eu:
    address: 0x09F59518
- name: banb_00
  format: sprite_sheet
  palette: banb
  symbol: gUnk_088A4ADE
  align: 4
  cell: [41, 57]
  anchor: [22, 52]
  columns: 8
  frames:
  - symbol: gUnk_088A4A3C
    pieces:
    - [32x32, -20, -35]
    - [16x8, -12, -4]
    - [8x16, 11, -35]
  - symbol: gUnk_088A4A52
    pieces:
    - [32x32, -20, -48]
    - [16x16, -22, -17]
    - [8x8, -6, -17]
  - symbol: gUnk_088A4A68
    pieces:
    - [32x32, -20, -52]
    - [8x8, -4, -21]
    - [8x16, -20, -21]
  - symbol: gUnk_088A4A7E
    pieces:
    - [32x32, -22, -46]
    - [8x8, -22, -15]
  - symbol: gUnk_088A4A8E
    pieces:
    - [32x32, -18, -35]
  - symbol: gUnk_088A4A98
    pieces:
    - [32x32, -18, -29]
  - symbol: gUnk_088A4AA2
    pieces:
    - [32x32, -14, -27]
  - symbol: gUnk_088A4AAC
    pieces:
    - [32x32, -16, -35]
    - [16x8, -8, -4]
  animations:
  - symbol: gUnk_088A4ABC
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 5], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5], [6, 5]]
  us:
    address: 0x088A4A3C
    size: 4738
  jp:
    address: 0x08898024
    size: 4738
  eu:
    address: 0x088D0360
    size: 4738
- name: gUnk_088A5D7A
  format: sprite_sheet
  align: 4
  cell: [16, 16]
  anchor: [8, 8]
  columns: 8
  frames:
  - symbol: gUnk_088A5CC0
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_088A5CCA
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_088A5CD4
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_088A5CDE
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_088A5CE8
    pieces:
    - [16x16, -8, -8, {hflip: true}]
  - symbol: gUnk_088A5CF2
    pieces:
    - [16x16, -8, -8, {hflip: true}]
  - symbol: gUnk_088A5CFC
    pieces:
    - [16x16, -8, -8, {hflip: true}]
  - symbol: gUnk_088A5D06
    pieces:
    - [16x16, -8, -8, {hflip: true}]
  - symbol: gUnk_088A5D10
    pieces:
    - [16x16, -8, -8, {vflip: true}]
  - symbol: gUnk_088A5D1A
    pieces:
    - [16x16, -8, -8, {vflip: true}]
  - symbol: gUnk_088A5D24
    pieces:
    - [16x16, -8, -8, {vflip: true}]
  - symbol: gUnk_088A5D2E
    pieces:
    - [16x16, -8, -8, {vflip: true}]
  animations:
  - symbol: gUnk_088A5D38
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 6], [1, 6], [2, 6], [3, 6]]
  - symbol: gUnk_088A5D4E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 6], [5, 6], [6, 6], [7, 6]]
  - symbol: gUnk_088A5D64
    fields: {unk_00: 64, unk_02: 64}
    frames: [[8, 6], [9, 6], [10, 6], [11, 6]]
  us:
    address: 0x088A5CC0
    size: 698
  jp:
    address: 0x088992A8
    size: 698
  eu:
    address: 0x088D15E4
    size: 698
- name: shinba_10
  format: sprite_sheet
  palette: shinba
  symbol: gUnk_088A6022
  align: 4
  cell: [96, 75]
  anchor: [43, 47]
  columns: 8
  frames:
  - symbol: gUnk_088A5F7C
    pieces:
    - [64x64, -37, -44]
    - [32x16, 11, -20]
  - symbol: gUnk_088A5F8C
    pieces:
    - [64x64, -35, -37]
    - [32x32, 21, -29]
  - symbol: gUnk_088A5F9C
    pieces:
    - [64x64, -33, -36]
    - [32x16, 15, -28]
  - symbol: gUnk_088A5FAC
    pieces:
    - [64x64, -32, -40]
    - [16x16, 24, -24]
  - symbol: gUnk_088A5FBC
    pieces:
    - [64x64, -36, -45]
    - [32x16, 12, -21]
  - symbol: gUnk_088A5FCC
    pieces:
    - [64x64, -32, -47]
    - [16x16, 24, -15]
  - symbol: gUnk_088A5FDC
    pieces:
    - [64x64, -38, -43]
    - [32x32, 10, -27]
  - symbol: gUnk_088A5FEC
    pieces:
    - [64x64, -43, -41]
    - [32x32, 13, -25]
  animations:
  - symbol: gUnk_088A5FFC
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 15], [1, 10], [2, 10], [3, 10], [4, 10], [5, 10], [6, 10], [7, 18]]
  us:
    address: 0x088A5F7C
    size: 19110
  jp:
    address: 0x08899564
    size: 19110
  eu:
    address: 0x088D18A0
    size: 19110
- name: mushu_10
  format: sprite_sheet
  palette: mushu
  symbol: gUnk_088AAB32
  align: 4
  cell: [53, 42]
  anchor: [26, 33]
  columns: 8
  frames:
  - symbol: gUnk_088AAA24
    pieces:
    - [32x32, -14, -33]
    - [16x8, 10, -17]
    - [16x16, -6, -9]
  - symbol: gUnk_088AAA3A
    pieces:
    - [32x32, -18, -27]
    - [16x16, 6, -19]
    - [16x16, -26, -27]
  - symbol: gUnk_088AAA50
    pieces:
    - [32x32, -20, -24]
    - [16x16, 4, -16]
  - symbol: gUnk_088AAA60
    pieces:
    - [32x32, -13, -25]
    - [16x16, 11, -9]
  - symbol: gUnk_088AAA70
    pieces:
    - [32x32, -15, -26]
  - symbol: gUnk_088AAA7A
    pieces:
    - [32x32, -26, -23]
    - [16x16, -2, -15]
  - symbol: gUnk_088AAA8A
    pieces:
    - [32x32, -15, -26]
    - [16x16, 9, -18]
  - symbol: gUnk_088AAA9A
    pieces:
    - [32x32, -10, -27]
  animations:
  - symbol: gUnk_088AAAA4
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 13], [1, 9], [2, 9], [3, 11], [4, 9], [5, 20], [6, 9], [7, 10], [0, 10]]
  - symbol: gUnk_088AAACE
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 10], [1, 7], [2, 7], [3, 9], [4, 7], [5, 19], [6, 7], [7, 8], [0, 10]]
  - symbol: gUnk_088AAAF8
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 12], [1, 8], [2, 8]]
  - symbol: gUnk_088AAB0A
    fields: {unk_00: 64, unk_02: 64}
    frames: [[3, 8], [4, 6], [5, 15], [4, 6]]
  - symbol: gUnk_088AAB20
    fields: {unk_00: 64, unk_02: 64}
    frames: [[6, 9], [7, 10], [0, 10]]
  us:
    address: 0x088AAA24
    size: 5326
  jp:
    address: 0x0889E00C
    size: 5326
  eu:
    address: 0x088D6348
    size: 5326
- name: gUnk_088ABF88
  format: sprite_sheet
  align: 4
  cell: [74, 76]
  anchor: [48, 57]
  columns: 8
  frames:
  - symbol: gUnk_088ABEF4
    pieces:
    - [64x64, -45, -45]
  - symbol: gUnk_088ABEFE
    pieces:
    - [64x64, -46, -51]
  - symbol: gUnk_088ABF08
    pieces:
    - [64x64, -48, -49]
  - symbol: gUnk_088ABF12
    pieces:
    - [64x64, -43, -51]
  - symbol: gUnk_088ABF1C
    pieces:
    - [64x64, -38, -54]
  - symbol: gUnk_088ABF26
    pieces:
    - [64x64, -42, -50]
  - symbol: gUnk_088ABF30
    pieces:
    - [64x64, -44, -46]
  - symbol: gUnk_088ABF3A
    pieces:
    - [64x64, -42, -48]
  - symbol: gUnk_088ABF44
    pieces:
    - [64x64, -39, -57]
  animations:
  - symbol: gUnk_088ABF4E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4], [1, 7]]
  - symbol: gUnk_088ABF5C
    fields: {unk_00: 64, unk_02: 64}
    frames: [[2, 8], [3, 8], [4, 8], [5, 8], [6, 8], [7, 8]]
  - symbol: gUnk_088ABF7A
    fields: {unk_00: 64, unk_02: 64}
    frames: [[8, 7], [0, 4]]
  us:
    address: 0x088ABEF4
    size: 18580
  jp:
    address: 0x0889F4DC
    size: 18580
  eu:
    address: 0x088D7818
    size: 18580
- name: genie_00
  format: sprite_sheet
  palette: genie
  symbol: gUnk_088B087C
  align: 4
  cell: [78, 127]
  anchor: [46, 117]
  columns: 8
  frames:
  - symbol: gUnk_088B0788
    pieces:
    - [64x64, -38, -54]
    - [16x16, -14, -69]
    - [8x8, -6, -76]
  - symbol: gUnk_088B079E
    pieces:
    - [64x64, -32, -60]
    - [16x16, -8, -75, {layer: 1}]
  - symbol: gUnk_088B07AE
    pieces:
    - [64x64, -46, -80]
    - [32x32, -14, -24]
  - symbol: gUnk_088B07BE
    pieces:
    - [64x64, -34, -65]
    - [32x32, -26, -96]
  - symbol: gUnk_088B07CE
    pieces:
    - [32x64, -25, -84]
    - [16x32, 6, -60]
    - [16x32, -26, -115]
    - [32x16, -9, -22]
    - [8x16, -9, -99]
  - symbol: gUnk_088B07F0
    pieces:
    - [32x64, -24, -84]
    - [16x32, -24, -115]
    - [8x16, -8, -99]
    - [16x32, 7, -60]
    - [32x16, -7, -23]
  - symbol: gUnk_088B0812
    pieces:
    - [32x64, -23, -82]
    - [16x32, 8, -66]
    - [32x16, -4, -23, {layer: 1}]
    - [16x32, -18, -113]
  - symbol: gUnk_088B082E
    pieces:
    - [32x64, -22, -86]
    - [32x16, -3, -23]
    - [8x8, -10, -23, {layer: 1}]
    - [8x32, 9, -62]
    - [16x32, -20, -117]
  animations:
  - symbol: gUnk_088B0850
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 15]]
  - symbol: gUnk_088B085A
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 8], [2, 8], [3, 8], [4, 8], [5, 8], [6, 8], [7, 15]]
  us:
    address: 0x088B0788
    size: 16948
  jp:
    address: 0x088A3D70
    size: 16948
  eu:
    address: 0x088DC0AC
    size: 16948
- name: mickey_10
  format: sprite_sheet
  palette: mickey
  symbol: gUnk_088B4A9C
  align: 4
  cell: [37, 50]
  anchor: [16, 39]
  columns: 8
  frames:
  - symbol: gUnk_088B49BC
    pieces:
    - [32x32, -11, -34]
    - [32x16, -11, -10]
  - symbol: gUnk_088B49CC
    pieces:
    - [32x32, -15, -39]
    - [16x32, -7, -23]
  - symbol: gUnk_088B49DC
    pieces:
    - [32x32, -16, -27]
    - [16x16, -8, -35]
  - symbol: gUnk_088B49EC
    pieces:
    - [32x32, -16, -25]
    - [16x16, -16, -33]
  - symbol: gUnk_088B49FC
    pieces:
    - [32x32, -14, -27]
    - [16x16, -6, -35]
  - symbol: gUnk_088B4A0C
    pieces:
    - [32x32, -12, -29]
    - [16x16, -4, -37]
    - [16x16, -4, -5]
  - symbol: gUnk_088B4A22
    pieces:
    - [32x32, -13, -30]
    - [16x16, -5, -38]
    - [32x16, -13, -6]
  - symbol: gUnk_088B4A38
    pieces:
    - [32x32, -12, -31]
    - [32x16, -12, -39]
    - [32x16, -12, -7]
  animations:
  - symbol: gUnk_088B4A4E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 7], [1, 14], [2, 7], [3, 15], [4, 11], [5, 5], [6, 5], [7, 15]]
  - symbol: gUnk_088B4A74
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 4]]
  - symbol: gUnk_088B4A7E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[2, 7], [3, 15], [4, 11], [5, 5], [6, 5], [7, 15]]
  us:
    address: 0x088B49BC
    size: 6368
  jp:
    address: 0x088A7FA4
    size: 6368
  eu:
    address: 0x088E02E0
    size: 6368