group: sprites_bos7
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_bos7_1.c
    start: 0x09EFAEF8
    end: 0x09EFAF60
  - name: sprites_bos7_2.c
    start: 0x09EFBEC4
    end: 0x09EFBFDC
  - name: sprites_bos7_frames_1.s
    start: 0x09C5C460
    end: 0x09C5CC04
  - name: sprites_bos7_frames_2.s
    start: 0x09C913F4
    end: 0x09C91E54
  - name: sprites_bos7_tiles.s
    start: 0x09CD0334
    end: 0x09CD1774
  - name: sprites_bos7_maps.s
    start: 0x09D4BA74
    end: 0x09D4DA74
  - name: sprites_bos7_palettes.s
    start: 0x09D694F4
    end: 0x09D69594
  jp:
  - name: sprites_bos7_1.c
    start: 0x09ED2404
    end: 0x09ED246C
  - name: sprites_bos7_2.c
    start: 0x09ED343C
    end: 0x09ED3554
  - name: sprites_bos7_frames_1.s
    start: 0x09C34B84
    end: 0x09C35328
  - name: sprites_bos7_frames_2.s
    start: 0x09C6A900
    end: 0x09C6B360
  - name: sprites_bos7_tiles.s
    start: 0x09CA9840
    end: 0x09CAAC80
  - name: sprites_bos7_maps.s
    start: 0x09D24F80
    end: 0x09D26F80
  - name: sprites_bos7_palettes.s
    start: 0x09D42A00
    end: 0x09D42AA0
  eu:
  - name: sprites_bos7_1.c
    start: 0x09F86C44
    end: 0x09F86CAC
  - name: sprites_bos7_2.c
    start: 0x09F886D8
    end: 0x09F887F0
  - name: sprites_bos7_frames_1.s
    start: 0x09CBA1A8
    end: 0x09CBA94C
  - name: sprites_bos7_frames_2.s
    start: 0x09D01720
    end: 0x09D02180
  - name: sprites_bos7_tiles.s
    start: 0x09D40660
    end: 0x09D41AA0
  - name: sprites_bos7_maps.s
    start: 0x09DB79A0
    end: 0x09DB99A0
  - name: sprites_bos7_palettes.s
    start: 0x09DD9420
    end: 0x09DD94C0
entries:
- name: gUnk_09EFAEF8
  record: SpriteTable
  items: [gUnk_09C5C460, gUnk_09C5C462, gUnk_09C5C46C, gUnk_09C5C476, gUnk_09C5C480, gUnk_09C5C48A, gUnk_09C5C494, gUnk_09C5C49E, gUnk_09C5C4A8]
  us:
    address: 0x09EFAEF8
  jp:
    address: 0x09ED2404
  eu:
    address: 0x09F86C44
- name: gUnk_09EFAF1C
  record: AnimTable
  items: [gUnk_09C5C4B2, gUnk_09C5C4D8]
  us:
    address: 0x09EFAF1C
  jp:
    address: 0x09ED2428
  eu:
    address: 0x09F86C68
- name: gUnk_09EFAF24
  record: SpriteTable
  items: [gUnk_09C5C664, gUnk_09C5C674, gUnk_09C5C676, gUnk_09C5C678, gUnk_09C5C67A, gUnk_09C5C67C, gUnk_09C5C686, gUnk_09C5C690, gUnk_09C5C69A, gUnk_09C5C6A4, gUnk_09C5C6AE]
  us:
    address: 0x09EFAF24
  jp:
    address: 0x09ED2430
  eu:
    address: 0x09F86C70
- name: gUnk_09EFAF50
  record: AnimTable
  items: [gUnk_09C5C6B8, gUnk_09C5C6C2, gUnk_09C5C6CC, gUnk_09C5C6D6]
  us:
    address: 0x09EFAF50
  jp:
    address: 0x09ED245C
  eu:
    address: 0x09F86C9C
- name: gUnk_09EFBEC4
  record: SpriteTable
  items: [gUnk_09C913F4, gUnk_09C913FE, gUnk_09C9140E, gUnk_09C9141E, gUnk_09C9142E, gUnk_09C9143E, gUnk_09C9144E, gUnk_09C91458, gUnk_09C91462, gUnk_09C91464, gUnk_09C9146E, gUnk_09C91478, gUnk_09C91482, gUnk_09C9148C, gUnk_09C91496, gUnk_09C914A0, gUnk_09C914AA, gUnk_09C914B4, gUnk_09C914BE, gUnk_09C914C8, gUnk_09C914D2]
  us:
    address: 0x09EFBEC4
  jp:
    address: 0x09ED343C
  eu:
    address: 0x09F886D8
- name: gUnk_09EFBF18
  record: AnimTable
  items: [gUnk_09C914DC, gUnk_09C914FA, gUnk_09C91504, gUnk_09C9150E, gUnk_09C91518, gUnk_09C91522, gUnk_09C9152C]
  us:
    address: 0x09EFBF18
  jp:
    address: 0x09ED3490
  eu:
    address: 0x09F8872C
- name: gUnk_09EFBF34
  record: AnimTable
  scalar: true
  items: [gUnk_09C9154E]
  us:
    address: 0x09EFBF34
  jp:
    address: 0x09ED34AC
  eu:
    address: 0x09F88748
- name: gUnk_09EFBF38
  record: AnimTable
  scalar: true
  items: [gUnk_09C91558]
  us:
    address: 0x09EFBF38
  jp:
    address: 0x09ED34B0
  eu:
    address: 0x09F8874C
- name: gUnk_09EFBF3C
  record: AnimTable
  scalar: true
  items: [gUnk_09C91562]
  us:
    address: 0x09EFBF3C
  jp:
    address: 0x09ED34B4
  eu:
    address: 0x09F88750
- name: gUnk_09EFBF40
  record: SpriteTable
  items: [gUnk_09C9156C, gUnk_09C9156E, gUnk_09C91578, gUnk_09C91582, gUnk_09C9158C]
  us:
    address: 0x09EFBF40
  jp:
    address: 0x09ED34B8
  eu:
    address: 0x09F88754
- name: gUnk_09EFBF54
  record: AnimTable
  items: [gUnk_09C91596, gUnk_09C915A0]
  us:
    address: 0x09EFBF54
  jp:
    address: 0x09ED34CC
  eu:
    address: 0x09F88768
- name: gUnk_09EFBF5C
  record: SpriteTable
  items: [gUnk_09C915C0]
  us:
    address: 0x09EFBF5C
  jp:
    address: 0x09ED34D4
  eu:
    address: 0x09F88770
- name: gUnk_09EFBF60
  record: AnimTable
  items: [gUnk_09C915D6]
  us:
    address: 0x09EFBF60
  jp:
    address: 0x09ED34D8
  eu:
    address: 0x09F88774
- name: gUnk_09EFBF64
  record: SpriteTable
  items: [gUnk_09C915E0, gUnk_09C915EA, gUnk_09C915F4, gUnk_09C915FE, gUnk_09C91608, gUnk_09C91612, gUnk_09C9161C, gUnk_09C91626, gUnk_09C91630, gUnk_09C9163A, gUnk_09C91644, gUnk_09C9164E, gUnk_09C91658, gUnk_09C91662, gUnk_09C9166C, gUnk_09C91676, gUnk_09C91680, gUnk_09C9168A, gUnk_09C91694, gUnk_09C9169E, gUnk_09C916A8, gUnk_09C916B2, gUnk_09C916BC, gUnk_09C916C6]
  us:
    address: 0x09EFBF64
  jp:
    address: 0x09ED34DC
  eu:
    address: 0x09F88778
- name: gUnk_09EFBFC4
  record: AnimTable
  items: [gUnk_09C916D0, gUnk_09C916E6, gUnk_09C916FC, gUnk_09C91712, gUnk_09C91728, gUnk_09C9173E]
  us:
    address: 0x09EFBFC4
  jp:
    address: 0x09ED353C
  eu:
    address: 0x09F887D8
- name: gUnk_09C5C4E2
  format: sprite_sheet
  align: 4
  cell: [17, 17]
  anchor: [9, 9]
  columns: 8
  frames:
  - symbol: gUnk_09C5C460
    pieces: []
  - symbol: gUnk_09C5C462
    pieces:
    - [16x16, -8, -8, {pal: 1}]
  - symbol: gUnk_09C5C46C
    pieces:
    - [16x16, -8, -8, {pal: 1}]
  - symbol: gUnk_09C5C476
    pieces:
    - [16x16, -8, -8, {pal: 1}]
  - symbol: gUnk_09C5C480
    pieces:
    - [16x16, -8, -9, {vflip: true, pal: 1}]
  - symbol: gUnk_09C5C48A
    pieces:
    - [16x16, -8, -9, {vflip: true, pal: 1}]
  - symbol: gUnk_09C5C494
    pieces:
    - [16x16, -9, -9, {hflip: true, vflip: true, pal: 1}]
  - symbol: gUnk_09C5C49E
    pieces:
    - [16x16, -9, -8, {hflip: true, pal: 1}]
  - symbol: gUnk_09C5C4A8
    pieces:
    - [16x16, -9, -8, {hflip: true, pal: 1}]
  animations:
  - symbol: gUnk_09C5C4B2
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [8, 6]]
  - symbol: gUnk_09C5C4D8
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 4]]
  us:
    address: 0x09C5C460
    size: 514
  jp:
    address: 0x09C34B84
    size: 514
  eu:
    address: 0x09CBA1A8
    size: 514
- name: gUnk_09C5C704
  format: sprite_sheet
  align: 4
  cell: [64, 16]
  anchor: [12, 8]
  columns: 8
  frames:
  - symbol: gUnk_09C5C664
    pieces:
    - [32x16, -12, -8]
    - [32x16, 20, -8]
  - symbol: gUnk_09C5C674
    pieces: []
  - symbol: gUnk_09C5C676
    pieces: []
  - symbol: gUnk_09C5C678
    pieces: []
  - symbol: gUnk_09C5C67A
    pieces: []
  - symbol: gUnk_09C5C67C
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_09C5C686
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_09C5C690
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_09C5C69A
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_09C5C6A4
    pieces:
    - [16x16, -8, -8]
  - symbol: gUnk_09C5C6AE
    pieces:
    - [16x16, -8, -8]
  animations:
  - symbol: gUnk_09C5C6B8
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 60]]
  - symbol: gUnk_09C5C6C2
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 60]]
  - symbol: gUnk_09C5C6CC
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 4]]
  - symbol: gUnk_09C5C6D6
    fields: {unk_00: 64, unk_02: 64}
    frames: [[5, 6], [6, 6], [7, 6], [8, 6], [9, 6], [10, 6], [9, 6], [8, 6], [7, 6], [6, 6]]
  us:
    address: 0x09C5C664
    size: 1440
  jp:
    address: 0x09C34D88
    size: 1440
  eu:
    address: 0x09CBA3AC
    size: 1440
- name: gUnk_09C913F4
  format: sprite_sheet
  tiles: gUnk_09CD0334
  align: 4
  cell: [32, 42]
  anchor: [16, 30]
  columns: 8
  frames:
  - symbol: gUnk_09C913F4
    pieces:
    - [32x32, -16, -20, {tile: 0}]
  - symbol: gUnk_09C913FE
    pieces:
    - [8x8, -3, -25, {tile: 16}]
    - [32x32, -16, -20, {tile: 0}]
  - symbol: gUnk_09C9140E
    pieces:
    - [8x8, -3, -25, {tile: 17}]
    - [32x32, -16, -20, {tile: 0}]
  - symbol: gUnk_09C9141E
    pieces:
    - [16x16, -7, -29, {tile: 18}]
    - [32x32, -16, -20, {tile: 0}]
  - symbol: gUnk_09C9142E
    pieces:
    - [8x16, -3, -30, {tile: 22}]
    - [32x32, -16, -20, {tile: 0}]
  - symbol: gUnk_09C9143E
    pieces:
    - [16x16, -8, -20, {tile: 24}]
    - [16x16, -8, -4, {tile: 24}]
  - symbol: gUnk_09C9144E
    pieces:
    - [16x8, -8, -4, {tile: 24}]
  - symbol: gUnk_09C91458
    pieces:
    - [16x16, -8, -12, {tile: 24}]
  - symbol: gUnk_09C91462
    pieces: []
  - symbol: gUnk_09C91464
    pieces:
    - [8x8, -3, -3, {tile: 16}]
  - symbol: gUnk_09C9146E
    pieces:
    - [8x8, -3, -3, {tile: 17}]
  - symbol: gUnk_09C91478
    pieces:
    - [16x16, -7, -7, {tile: 18}]
  - symbol: gUnk_09C91482
    pieces:
    - [16x32, -8, -20, {tile: 28}]
  - symbol: gUnk_09C9148C
    pieces:
    - [16x32, -8, -20, {tile: 36}]
  - symbol: gUnk_09C91496
    pieces:
    - [16x32, -8, -20, {tile: 44}]
  - symbol: gUnk_09C914A0
    pieces:
    - [16x8, -8, -8, {tile: 52}]
  - symbol: gUnk_09C914AA
    pieces:
    - [16x16, -8, -16, {tile: 54}]
  - symbol: gUnk_09C914B4
    pieces:
    - [16x16, -8, -16, {tile: 58}]
  - symbol: gUnk_09C914BE
    pieces:
    - [16x16, -8, -16, {tile: 62}]
  - symbol: gUnk_09C914C8
    pieces:
    - [16x16, -8, -16, {tile: 66}]
  - symbol: gUnk_09C914D2
    pieces:
    - [16x8, -8, -14, {tile: 70}]
  animations:
  - symbol: gUnk_09C914DC
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 6], [1, 6], [2, 8], [3, 2], [4, 2], [0, 1]]
  - symbol: gUnk_09C914FA
    fields: {unk_00: 64, unk_02: 64}
    frames: [[5, 4]]
  - symbol: gUnk_09C91504
    fields: {unk_00: 64, unk_02: 64}
    frames: [[6, 60]]
  - symbol: gUnk_09C9150E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[7, 60]]
  - symbol: gUnk_09C91518
    fields: {unk_00: 64, unk_02: 64}
    frames: [[8, 60]]
  - symbol: gUnk_09C91522
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 60]]
  - symbol: gUnk_09C9152C
    fields: {unk_00: 64, unk_02: 64}
    frames: [[15, 1], [16, 2], [17, 4], [18, 2], [19, 3], [20, 4], [8, 1]]
  - symbol: gUnk_09C9154E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[12, 4]]
  - symbol: gUnk_09C91558
    fields: {unk_00: 64, unk_02: 64}
    frames: [[13, 4]]
  - symbol: gUnk_09C91562
    fields: {unk_00: 64, unk_02: 64}
    frames: [[14, 4]]
  us:
    address: 0x09C913F4
    size: 376
  jp:
    address: 0x09C6A900
    size: 376
  eu:
    address: 0x09D01720
    size: 376
- name: gUnk_09C9156C
  format: sprite_sheet
  tiles: gUnk_09CD0C34
  align: 4
  cell: [16, 16]
  anchor: [8, 8]
  columns: 5
  frames:
  - symbol: gUnk_09C9156C
    pieces: []
  - symbol: gUnk_09C9156E
    pieces:
    - [16x16, -8, -8, {pal: 1, tile: 0}]
  - symbol: gUnk_09C91578
    pieces:
    - [16x16, -8, -8, {pal: 1, tile: 4}]
  - symbol: gUnk_09C91582
    pieces:
    - [16x16, -8, -8, {pal: 1, tile: 8}]
  - symbol: gUnk_09C9158C
    pieces:
    - [16x16, -8, -8, {pal: 1, tile: 12}]
  animations:
  - symbol: gUnk_09C91596
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 60]]
  - symbol: gUnk_09C915A0
    fields: {unk_00: 64, unk_02: 64}
    frames: [[1, 6], [2, 6], [3, 6], [4, 6], [3, 6], [2, 6]]
  us:
    address: 0x09C9156C
    size: 82
  jp:
    address: 0x09C6AA78
    size: 82
  eu:
    address: 0x09D01898
    size: 82
- name: gUnk_09C915C0
  format: sprite_sheet
  tiles: gUnk_09CD0E34
  align: 4
  cell: [30, 63]
  anchor: [11, 31]
  columns: 1
  frames:
  - symbol: gUnk_09C915C0
    pieces:
    - [8x16, 11, 16, {tile: 16}]
    - [16x32, -11, -31, {tile: 0}]
    - [16x32, -4, 0, {tile: 8}]
  animations:
  - symbol: gUnk_09C915D6
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 8]]
  us:
    address: 0x09C915C0
    size: 32
  jp:
    address: 0x09C6AACC
    size: 32
  eu:
    address: 0x09D018EC
    size: 32
- name: gUnk_09C915E0
  format: sprite_sheet
  tiles: gUnk_09CD1074
  align: 4
  cell: [16, 16]
  anchor: [8, 8]
  columns: 8
  frames:
  - symbol: gUnk_09C915E0
    pieces:
    - [8x8, -4, -4, {tile: 0}]
  - symbol: gUnk_09C915EA
    pieces:
    - [8x8, -4, -4, {tile: 1}]
  - symbol: gUnk_09C915F4
    pieces:
    - [8x8, -4, -4, {tile: 2}]
  - symbol: gUnk_09C915FE
    pieces:
    - [8x8, -4, -4, {tile: 3}]
  - symbol: gUnk_09C91608
    pieces:
    - [8x8, -4, -4, {tile: 4}]
  - symbol: gUnk_09C91612
    pieces:
    - [8x8, -4, -4, {tile: 5}]
  - symbol: gUnk_09C9161C
    pieces:
    - [8x8, -4, -4, {tile: 6}]
  - symbol: gUnk_09C91626
    pieces:
    - [8x8, -4, -4, {tile: 7}]
  - symbol: gUnk_09C91630
    pieces:
    - [16x8, -8, -4, {tile: 8}]
  - symbol: gUnk_09C9163A
    pieces:
    - [16x8, -8, -4, {tile: 10}]
  - symbol: gUnk_09C91644
    pieces:
    - [16x8, -8, -4, {tile: 12}]
  - symbol: gUnk_09C9164E
    pieces:
    - [16x8, -8, -4, {tile: 14}]
  - symbol: gUnk_09C91658
    pieces:
    - [8x16, -4, -8, {tile: 16}]
  - symbol: gUnk_09C91662
    pieces:
    - [8x16, -4, -8, {tile: 18}]
  - symbol: gUnk_09C9166C
    pieces:
    - [8x16, -4, -8, {tile: 20}]
  - symbol: gUnk_09C91676
    pieces:
    - [8x16, -4, -8, {tile: 22}]
  - symbol: gUnk_09C91680
    pieces:
    - [16x16, -8, -8, {tile: 24}]
  - symbol: gUnk_09C9168A
    pieces:
    - [16x16, -8, -8, {tile: 28}]
  - symbol: gUnk_09C91694
    pieces:
    - [16x16, -8, -8, {tile: 32}]
  - symbol: gUnk_09C9169E
    pieces:
    - [16x16, -8, -8, {tile: 36}]
  - symbol: gUnk_09C916A8
    pieces:
    - [16x16, -8, -8, {tile: 40}]
  - symbol: gUnk_09C916B2
    pieces:
    - [16x16, -8, -8, {tile: 44}]
  - symbol: gUnk_09C916BC
    pieces:
    - [16x16, -8, -8, {tile: 48}]
  - symbol: gUnk_09C916C6
    pieces:
    - [16x16, -8, -8, {tile: 52}]
  animations:
  - symbol: gUnk_09C916D0
    fields: {unk_00: 64, unk_02: 64}
    frames: [[0, 7], [1, 7], [2, 7], [3, 7]]
  - symbol: gUnk_09C916E6
    fields: {unk_00: 64, unk_02: 64}
    frames: [[4, 7], [5, 7], [6, 7], [7, 7]]
  - symbol: gUnk_09C916FC
    fields: {unk_00: 64, unk_02: 64}
    frames: [[8, 7], [9, 7], [10, 7], [11, 7]]
  - symbol: gUnk_09C91712
    fields: {unk_00: 64, unk_02: 64}
    frames: [[12, 7], [13, 7], [14, 7], [15, 7]]
  - symbol: gUnk_09C91728
    fields: {unk_00: 64, unk_02: 64}
    frames: [[16, 7], [17, 7], [18, 7], [19, 7]]
  - symbol: gUnk_09C9173E
    fields: {unk_00: 64, unk_02: 64}
    frames: [[20, 7], [21, 7], [22, 7], [23, 7]]
  us:
    address: 0x09C915E0
    size: 372
  jp:
    address: 0x09C6AAEC
    size: 372
  eu:
    address: 0x09D0190C
    size: 372
- name: gUnk_09C91754
  format: tiles4
  width: 8
  us:
    address: 0x09C91754
    size: 1792
  jp:
    address: 0x09C6AC60
    size: 1792
  eu:
    address: 0x09D01A80
    size: 1792
- name: gUnk_09CD0334
  format: tiles4
  width: 8
  us:
    address: 0x09CD0334
    size: 2304
  jp:
    address: 0x09CA9840
    size: 2304
  eu:
    address: 0x09D40660
    size: 2304
- name: gUnk_09CD0C34
  format: tiles4
  width: 16
  us:
    address: 0x09CD0C34
    size: 512
  jp:
    address: 0x09CAA140
    size: 512
  eu:
    address: 0x09D40F60
    size: 512
- name: gUnk_09CD0E34
  format: tiles4
  width: 2
  us:
    address: 0x09CD0E34
    size: 576
  jp:
    address: 0x09CAA340
    size: 576
  eu:
    address: 0x09D41160
    size: 576
- name: gUnk_09CD1074
  format: tiles4
  width: 8
  us:
    address: 0x09CD1074
    size: 1792
  jp:
    address: 0x09CAA580
    size: 1792
  eu:
    address: 0x09D413A0
    size: 1792
- name: gUnk_09D4BA74
  format: tilemap
  us:
    address: 0x09D4BA74
    size: 2048
  jp:
    address: 0x09D24F80
    size: 2048
  eu:
    address: 0x09DB79A0
    size: 2048
- name: gUnk_09D4C274
  format: tilemap
  us:
    address: 0x09D4C274
    size: 2048
  jp:
    address: 0x09D25780
    size: 2048
  eu:
    address: 0x09DB81A0
    size: 2048
- name: gUnk_09D4CA74
  format: tilemap
  us:
    address: 0x09D4CA74
    size: 2048
  jp:
    address: 0x09D25F80
    size: 2048
  eu:
    address: 0x09DB89A0
    size: 2048
- name: gUnk_09D4D274
  format: tilemap
  us:
    address: 0x09D4D274
    size: 2048
  jp:
    address: 0x09D26780
    size: 2048
  eu:
    address: 0x09DB91A0
    size: 2048
- name: gUnk_09D694F4
  format: palette
  us:
    address: 0x09D694F4
    size: 160
  jp:
    address: 0x09D42A00
    size: 160
  eu:
    address: 0x09DD9420
    size: 160
