group: sprites_premire_chance
types:
  SpriteTable:
    kind: table
    type: void*
  AnimTable:
    kind: table
    type: AnimHeader*
    header: anim.h
  Sprite:
    kind: sprite
  AnimHeader:
    kind: anim
    header: anim.h
objects:
  us:
  - name: sprites_premire_chance.c
    start: 0x09EEA16C
    end: 0x09EEA180
  - name: sprites_premire_chance_frames.s
    start: 0x0908BB54
    end: 0x0908C374
  jp:
  - name: sprites_premire_chance.c
    start: 0x09EC1560
    end: 0x09EC1574
  - name: sprites_premire_chance_frames.s
    start: 0x090473C4
    end: 0x09047BE4
  eu:
  - name: sprites_premire_chance.c
    start: 0x09F75F84
    end: 0x09F75F98
  - name: sprites_premire_chance_frames.s
    start: 0x09161E28
    end: 0x09162648
entries:
- name: gUnk_09EEA16C
  record: SpriteTable
  items: [gUnk_0908BB54]
  us:
    address: 0x09EEA16C
  jp:
    address: 0x09EC1560
  eu:
    address: 0x09F75F84
- name: gUnk_09EEA170
  record: AnimTable
  scalar: true
  items: [gUnk_0908BB76]
  us:
    address: 0x09EEA170
  jp:
    address: 0x09EC1564
  eu:
    address: 0x09F75F88
- name: gUnk_09EEA174
  record: SpriteTable
  items: [gUnk_0908BF40, gUnk_0908BF74]
  us:
    address: 0x09EEA174
  jp:
    address: 0x09EC1568
  eu:
    address: 0x09F75F8C
- name: gUnk_09EEA17C
  record: AnimTable
  scalar: true
  items: [gUnk_0908BFA8]
  us:
    address: 0x09EEA17C
  jp:
    address: 0x09EC1570
  eu:
    address: 0x09F75F94
- name: gUnk_0908BB54
  record: Sprite
  align: 4
  oam:
  - [16384, 32768, 0]
  - [16384, 32800, 8]
  - [16384, 32832, 16]
  - [0, 16480, 24]
  - [32768, 112, 28]
  us:
    address: 0x0908BB54
  jp:
    address: 0x090473C4
  eu:
    address: 0x09161E28
- name: gUnk_0908BB76
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x0908BB76
  jp:
    address: 0x090473E6
  eu:
    address: 0x09161E4A
- name: gUnk_0908BB80
  format: tiles4
  width: 1
  us:
    address: 0x0908BB80
    size: 960
  jp:
    address: 0x090473F0
    size: 960
  eu:
    address: 0x09161E54
    size: 960
- name: gUnk_0908BF40
  record: Sprite
  align: 4
  oam:
  - [16384, 16776, 0]
  - [16384, 16808, 4]
  - [16384, 16840, 8]
  - [16384, 16872, 12]
  - [16384, 16392, 16]
  - [16384, 16424, 20]
  - [16384, 16456, 24]
  - [16384, 104, 28]
  us:
    address: 0x0908BF40
  jp:
    address: 0x090477B0
  eu:
    address: 0x09162214
- name: gUnk_0908BF74
  record: Sprite
  oam:
  - [16384, 24968, 0]
  - [16384, 25000, 4]
  - [16384, 25032, 8]
  - [16384, 25064, 12]
  - [16384, 24584, 16]
  - [16384, 24616, 20]
  - [16384, 24648, 24]
  - [16384, 8296, 28]
  us:
    address: 0x0908BF74
  jp:
    address: 0x090477E4
  eu:
    address: 0x09162248
- name: gUnk_0908BFA8
  record: AnimHeader
  fields:
    unk_00: 64
    unk_02: 64
  frames:
  - [0, 4]
  us:
    address: 0x0908BFA8
  jp:
    address: 0x09047818
  eu:
    address: 0x0916227C
- name: gUnk_0908BFB2
  format: tiles4
  width: 1
  us:
    address: 0x0908BFB2
    size: 960
  jp:
    address: 0x09047822
    size: 960
  eu:
    address: 0x09162286
    size: 960
