#ifndef GUARD_EMY_TASKS_H
#define GUARD_EMY_TASKS_H

#include "types.h"

struct Emy03Work;
struct Emy04Work;
struct Emy06Work;
struct Emy07Work;
struct Emy08Work;
struct Emy16Work;
struct Emy16bWork;
struct Emy16pWork;
struct Emy18Work;
struct Emy19Work;
struct Emy21Work;
struct Emy22Work;
struct Emy23Work;
struct Emy28Work;
struct Emy29Work;
struct Emy31Work;
struct Emy37Work;
struct Emy39Work;
struct Emy41Work;
struct Emy81Work;
struct Emy82Work;
struct Emy83Work;
struct Emy83bWork;
struct Emy83sWork;
struct EmySpawn;
struct EmyWork;

void task_emy_00_0(struct EmyWork* work, void* obj);
u8 task_emy_00_1(struct EmyWork* work);
void task_emy_00_2(struct EmyWork* work);
void task_emy_00_3(struct EmyWork* work);
void task_emy_01_0(struct EmyWork* work, void* obj);
u8 task_emy_01_1(struct EmyWork* work);
void task_emy_01_2(struct EmyWork* work);
void task_emy_01_3(struct EmyWork* work);
void task_emy_02_0(struct EmyWork* work, void* obj);
u8 task_emy_02_1(struct EmyWork* work);
void task_emy_02_2(struct EmyWork* work);
void task_emy_02_3(struct EmyWork* work);
void task_emy_03_0(struct EmyWork* work, void* obj);
u8 task_emy_03_1(struct Emy03Work* work);
void task_emy_03_2(struct EmyWork* work);
void task_emy_03_3(struct EmyWork* work);
void task_emy_04_0(struct Emy04Work* work, void* obj);
u8 task_emy_04_1(struct Emy04Work* work);
void task_emy_04_2(struct EmyWork* work);
void task_emy_04_3(struct EmyWork* work);
void task_emy_06_0(struct EmyWork* work, void* obj);
u8 task_emy_06_1(struct Emy06Work* work);
void task_emy_06_2(struct EmyWork* work);
void task_emy_06_3(struct EmyWork* work);
void task_emy_07_0(struct Emy07Work* work, void* obj);
u8 task_emy_07_1(struct Emy07Work* work);
void task_emy_07_2(struct EmyWork* work);
void task_emy_07_3(struct EmyWork* work);
void task_emy_08_0(struct Emy08Work* work, void* obj);
u8 task_emy_08_1(struct Emy08Work* work);
void task_emy_08_2(struct Emy08Work* work);
void task_emy_08_3(struct Emy08Work* work);
void task_emy_14_0(struct EmyWork* work, void* obj);
u8 task_emy_14_1(struct EmyWork* work);
void task_emy_14_2(struct EmyWork* work);
void task_emy_14_3(struct EmyWork* work);
void task_emy_15_0(struct EmyWork* work, void* obj);
u8 task_emy_15_1(struct EmyWork* work);
void task_emy_15_2(struct EmyWork* work);
void task_emy_15_3(struct EmyWork* work);
void task_emy_16_0(struct Emy16Work* work, void* obj);
u8 task_emy_16_1(struct Emy16Work* work);
void task_emy_16_2(struct Emy16Work* work);
void task_emy_16_3(struct Emy16Work* work);
void task_emy_16_b_0(struct Emy16bWork* work, struct EmySpawn* spawn);
u8 task_emy_16_b_1(struct Emy16bWork* work);
void task_emy_16_b_2(struct Emy16bWork* work);
void task_emy_16_b_3(struct Emy16bWork* work);
void task_emy_16_p_0(struct Emy16pWork* work, struct EmySpawn* spawn);
u8 task_emy_16_p_1(struct Emy16pWork* work);
void task_emy_16_p_2(struct Emy16pWork* work);
void task_emy_16_p_3(struct Emy16pWork* work);
void task_emy_18_0(struct EmyWork* work, void* obj);
u8 task_emy_18_1(struct Emy18Work* work);
void task_emy_18_2(struct EmyWork* work);
void task_emy_18_3(struct EmyWork* work);
void task_emy_19_0(struct EmyWork* work, void* obj);
u8 task_emy_19_1(struct Emy19Work* work);
void task_emy_19_2(struct EmyWork* work);
void task_emy_19_3(struct EmyWork* work);
void task_emy_21_0(struct Emy21Work* work, void* obj);
u8 task_emy_21_1(struct Emy21Work* work);
void task_emy_21_2(struct EmyWork* work);
void task_emy_21_3(struct EmyWork* work);
void task_emy_22_0(struct Emy22Work* work, void* obj);
u8 task_emy_22_1(struct Emy22Work* work);
void task_emy_22_2(struct EmyWork* work);
void task_emy_22_3(struct EmyWork* work);
void task_emy_23_0(struct EmyWork* work, void* obj);
u8 task_emy_23_1(struct Emy23Work* work);
void task_emy_23_2(struct EmyWork* work);
void task_emy_23_3(struct EmyWork* work);
void task_emy_25_0(struct EmyWork* work, void* obj);
u8 task_emy_25_1(struct EmyWork* work);
void task_emy_25_2(struct EmyWork* work);
void task_emy_25_3(struct EmyWork* work);
void task_emy_26_0(struct EmyWork* work, void* obj);
u8 task_emy_26_1(struct EmyWork* work);
void task_emy_26_2(struct EmyWork* work);
void task_emy_26_3(struct EmyWork* work);
void task_emy_27_0(struct EmyWork* work, void* obj);
u8 task_emy_27_1(struct EmyWork* work);
void task_emy_27_2(struct EmyWork* work);
void task_emy_27_3(struct EmyWork* work);
void task_emy_28_0(struct EmyWork* work, void* obj);
u8 task_emy_28_1(struct Emy28Work* work);
void task_emy_28_2(struct EmyWork* work);
void task_emy_28_3(struct EmyWork* work);
void task_emy_29_0(struct Emy29Work* work, void* obj);
u8 task_emy_29_1(struct Emy29Work* work);
void task_emy_29_2(struct EmyWork* work);
void task_emy_29_3(struct EmyWork* work);
void task_emy_30_0(struct EmyWork* work, void* obj);
u8 task_emy_30_1(struct EmyWork* work);
void task_emy_30_2(struct EmyWork* work);
void task_emy_30_3(struct EmyWork* work);
void task_emy_31_0(struct EmyWork* work, void* obj);
u8 task_emy_31_1(struct Emy31Work* work);
void task_emy_31_2(struct EmyWork* work);
void task_emy_31_3(struct EmyWork* work);
void task_emy_37_0(struct Emy37Work* work, void* obj);
u8 task_emy_37_1(struct Emy37Work* work);
void task_emy_37_2(struct Emy37Work* work);
void task_emy_37_3(struct EmyWork* work);
void task_emy_38_0(struct EmyWork* work, void* obj);
u8 task_emy_38_1(struct EmyWork* work);
void task_emy_38_2(struct EmyWork* work);
void task_emy_38_3(struct EmyWork* work);
void task_emy_39_0(struct EmyWork* work, void* obj);
u8 task_emy_39_1(struct Emy39Work* work);
void task_emy_39_2(struct EmyWork* work);
void task_emy_39_3(struct EmyWork* work);
void task_emy_41_0(struct EmyWork* work, void* obj);
u8 task_emy_41_1(struct Emy41Work* work);
void task_emy_41_2(struct EmyWork* work);
void task_emy_41_3(struct EmyWork* work);
void task_emy_44_0(struct EmyWork* work, void* obj);
u8 task_emy_44_1(struct EmyWork* work);
void task_emy_44_2(struct EmyWork* work);
void task_emy_44_3(struct EmyWork* work);
void task_emy_81_0(struct EmyWork* work, void* obj);
u8 task_emy_81_1(struct Emy81Work* work);
void task_emy_81_2(struct EmyWork* work);
void task_emy_81_3(struct EmyWork* work);
void task_emy_82_0(struct Emy82Work* work, void* obj);
u8 task_emy_82_1(struct Emy82Work* work);
void task_emy_82_2(struct EmyWork* work);
void task_emy_82_3(struct EmyWork* work);
void task_emy_83_0(struct Emy83Work* work, void* obj);
u8 task_emy_83_1(struct Emy83Work* work);
void task_emy_83_2(struct Emy83Work* work);
void task_emy_83_3(struct Emy83Work* work);
void task_emy_83_b_0(struct Emy83bWork* work, struct EmySpawn* spawn);
u8 task_emy_83_b_1(struct Emy83bWork* work);
void task_emy_83_b_2(struct Emy83bWork* work);
void task_emy_83_b_3(struct Emy83bWork* work);
void task_emy_83_s_0(struct Emy83sWork* work, struct EmySpawn* spawn);
u8 task_emy_83_s_1(struct Emy83sWork* work);
void task_emy_83_s_2(struct Emy83sWork* work);
void task_emy_83_s_3(struct Emy83sWork* work);
void task_emy_trump_h_0(struct EmyWork* work, void* obj);
u8 task_emy_trump_h_1(struct EmyWork* work);
void task_emy_trump_h_2(struct EmyWork* work);
void task_emy_trump_h_3(struct EmyWork* work);
void task_emy_trump_s_0(struct EmyWork* work, void* obj);
u8 task_emy_trump_s_1(struct EmyWork* work);
void task_emy_trump_s_2(struct EmyWork* work);
void task_emy_trump_s_3(struct EmyWork* work);
void task_emy_test_0(struct EmyWork* work, void* obj);
u8 task_emy_test_1(struct EmyWork* work);
void task_emy_test_2(struct EmyWork* work);
void task_emy_test_3(struct EmyWork* work);

#endif
