#ifndef GUARD_HUM_TASKS_H
#define GUARD_HUM_TASKS_H

#include "types.h"

struct AnsemWork;
struct AxcelPtcWork;
struct AxcelWork;
struct CloudWork;
struct HadesWork;
struct HookBombWork;
struct HookMoonWork;
struct HookWork;
struct HumWork;
struct LaxeneKnfWork;
struct LaxeneWork;
struct LeonWork;
struct LexRockWork;
struct LexTmh0Work;
struct LexTmhWork;
struct LexceusWork;
struct MahluxiaFlwWork;
struct MahluxiaWork;
struct RikuWork;
struct RobeWork;
struct VixenFrgWork;
struct VixenFrzWork;
struct VixenIceWork;
struct VixenNdlArgs;
struct VixenNdlWork;
struct VixenSub;
struct VixenWork;

void task_hum_cloud_0(struct CloudWork* work, void* obj);
u8 task_hum_cloud_1(struct CloudWork* work);
void task_hum_cloud_2(struct HumWork* work);
void task_hum_cloud_3(struct HumWork* work);
void task_hum_hook_0(struct HookWork* work, void* arg);
u8 task_hum_hook_1(struct HookWork* work);
void task_hum_hook_2(struct HookWork* work);
void task_hum_hook_3(struct HookWork* work);
void task_hum_hook_moon_0(struct HookMoonWork* work);
u8 task_hum_hook_moon_1(struct HookMoonWork* work);
void task_hum_hook_moon_2(struct HookMoonWork* work);
void task_hum_hook_moon_3(struct HookMoonWork* work);
void task_hum_hook_bomb_0(struct HookBombWork* work, struct VixenNdlArgs* args);
u8 task_hum_hook_bomb_1(struct HookBombWork* work);
void task_hum_hook_bomb_2(struct HookBombWork* work);
void task_hum_hook_bomb_3(struct HookBombWork* work);
void task_hum_ansem_0(struct AnsemWork* work);
u8 task_hum_ansem_1(struct AnsemWork* work);
void task_hum_ansem_2(struct HumWork* work);
void task_hum_ansem_3(struct HumWork* work);
void task_hum_hades_0(struct HadesWork* work);
u8 task_hum_hades_1(struct HadesWork* work);
void task_hum_hades_2(struct HadesWork* work);
void task_hum_hades_3(struct HadesWork* work);
void task_hum_mahluxia_0(struct MahluxiaWork* work);
u8 task_hum_mahluxia_1(struct MahluxiaWork* work);
void task_hum_mahluxia_2(struct MahluxiaWork* work);
void task_hum_mahluxia_3(struct MahluxiaWork* work);
void task_hum_laxene_0(struct LaxeneWork* work);
u8 task_hum_laxene_1(struct LaxeneWork* work);
void task_hum_laxene_2(struct LaxeneWork* work);
void task_hum_laxene_3(struct LaxeneWork* work);
void task_hum_laxene_knf_0(struct LaxeneKnfWork* work, struct VixenNdlArgs* args);
u8 task_hum_laxene_knf_1(struct LaxeneKnfWork* work);
void task_hum_laxene_knf_2(struct LaxeneKnfWork* work);
void task_hum_laxene_knf_3(struct LaxeneKnfWork* work);
void task_hum_axcel_0(struct AxcelWork* work);
u8 task_hum_axcel_1(struct AxcelWork* work);
void task_hum_axcel_2(struct AxcelWork* work);
void task_hum_axcel_3(struct AxcelWork* work);
void task_hum_axcel_ptc_0(struct AxcelPtcWork* work, s32* args);
u8 task_hum_axcel_ptc_1(struct AxcelPtcWork* work);
void task_hum_axcel_ptc_2(struct AxcelPtcWork* work);
void task_hum_axcel_ptc_3(struct AxcelPtcWork* work);
void task_hum_vixen_0(struct VixenWork* work);
u8 task_hum_vixen_1(struct VixenWork* work);
void task_hum_vixen_2(struct VixenWork* work);
void task_hum_vixen_3(struct VixenWork* work);
void task_hum_vixen_ndl_0(struct VixenNdlWork* work, struct VixenNdlArgs* args);
u8 task_hum_vixen_ndl_1(struct VixenNdlWork* work);
void task_hum_vixen_ndl_2(struct VixenNdlWork* work);
void task_hum_vixen_ndl_3(struct VixenNdlWork* work);
void task_hum_vixen_ice_0(struct VixenIceWork* work, struct VixenSub* args);
u8 task_hum_vixen_ice_1(struct VixenIceWork* work);
void task_hum_vixen_ice_2(struct VixenIceWork* work);
void task_hum_vixen_ice_3(struct VixenIceWork* work);
void task_hum_vixen_frz_0(struct VixenFrzWork* work, struct VixenNdlArgs* args);
u8 task_hum_vixen_frz_1(struct VixenFrzWork* work);
void task_hum_vixen_frz_2(struct VixenFrzWork* work);
void task_hum_vixen_frz_3(struct VixenFrzWork* work);
void task_hum_vixen_frg_0(struct VixenFrgWork* work, struct VixenNdlArgs* args);
u8 task_hum_vixen_frg_1(struct VixenFrgWork* work);
void task_hum_vixen_frg_2(struct VixenFrgWork* work);
void task_hum_vixen_frg_3(struct VixenFrgWork* work);
void task_hum_lexceus_0(struct LexceusWork* work);
u8 task_hum_lexceus_1(struct LexceusWork* work);
void task_hum_lexceus_2(struct LexceusWork* work);
void task_hum_lexceus_3(struct LexceusWork* work);
void task_hum_lex_tmh_0(struct LexTmhWork* work, struct VixenNdlArgs* args);
u8 task_hum_lex_tmh_1(struct LexTmhWork* work);
void task_hum_lex_tmh_2(struct LexTmhWork* work);
void task_hum_lex_tmh_3(struct LexTmhWork* work);
void task_hum_lex_tmh0_0(struct LexTmh0Work* work, struct VixenNdlArgs* args);
u8 task_hum_lex_tmh0_1(struct LexTmh0Work* work);
void task_hum_lex_tmh0_2(struct LexTmh0Work* work);
void task_hum_lex_tmh0_3(struct LexTmh0Work* work);
void task_hum_lex_rock_0(struct LexRockWork* work, struct VixenNdlArgs* args);
u8 task_hum_lex_rock_1(struct LexRockWork* work);
void task_hum_lex_rock_2(struct LexRockWork* work);
void task_hum_lex_rock_3(struct LexRockWork* work);
void task_hum_mahluxia_flw_0(struct MahluxiaFlwWork* work, struct VixenNdlArgs* args);
u8 task_hum_mahluxia_flw_1(struct MahluxiaFlwWork* work);
void task_hum_mahluxia_flw_2(struct MahluxiaFlwWork* work);
void task_hum_mahluxia_flw_3(struct MahluxiaFlwWork* work);
void task_hum_riku_0(struct RikuWork* work);
u8 task_hum_riku_1(struct RikuWork* work);
void task_hum_riku_2(struct RikuWork* work);
void task_hum_riku_3(struct HumWork* work);
void task_hum_leon_0(struct LeonWork* work);
u8 task_hum_leon_1(struct LeonWork* work);
void task_hum_leon_2(struct HumWork* work);
void task_hum_leon_3(struct LeonWork* work);
void task_hum_robe_0(struct RobeWork* work);
u8 task_hum_robe_1(struct RobeWork* work);
void task_hum_robe_2(struct HumWork* work);
void task_hum_robe_3(struct HumWork* work);

#endif
