#ifndef GUARD_REGISTRATION_DATA_H
#define GUARD_REGISTRATION_DATA_H

#include "task_descriptors.h"
#include "taskpool.h"
#include "mode.h"

extern Mode gModeJiminy;
extern TaskDesc gTaskDescMonsgage;
extern TaskDesc gTaskDescBtlPopCb;
extern TaskDesc gTaskDescBtlExp;
extern TaskDesc gTaskDescBtlVslockon;
extern TaskDesc gTaskDescBtlHpoth;
extern TaskDesc gTaskDescTutorial;
extern Mode gModeMovie;
extern TaskDesc gTaskDescLockon;
extern Mode gModeContinue;
extern TaskDesc gTaskDescEventSeq;
extern TaskDesc gTaskDescEventChara;
extern TaskDesc gTaskDescMsgwin;
extern TaskDesc gTaskDescMsgface[3];
extern TaskDesc gTaskDescView;
extern Mode gModeEventselect;
extern TaskDesc gTaskDescHanabira;
extern TaskDesc gTaskDescHanabiraC;
extern TaskDesc gTaskDescSmoke;
extern TaskDesc gTaskDescExclamation;
extern TaskDesc gTaskDescBalloon;
extern TaskDesc gTaskDescQuestion;
extern TaskDesc gTaskDescGlowNose;
extern TaskDesc gTaskDescGlowNose2;
extern TaskDesc gTaskDescDown;
extern TaskDesc gTaskDescTinkerbell;
extern TaskDesc gTaskDescEvSound;
extern TaskDesc gTaskDescCardBattleSora;
extern TaskDesc gTaskDescCardBattleRiku;
extern TaskDesc gTaskDescBosscard;
extern TaskDesc gTaskDescMapAnim;
extern TaskDesc gTaskDescMapSelect;
extern TaskDesc gTaskDescMapcard;
extern TaskDesc gTaskDescPrizeCardInit;
extern TaskDesc gTaskDescPrizeCardInitBoss;
extern TaskDesc gTaskDescDispCardname;
extern TaskDesc gTaskDescVersion;
extern TaskDesc gTaskDescSpotLight;
extern TaskDesc gTaskDescSELMAPEVKEY;
extern TaskDesc gTaskDescReloadChildren;
extern TaskDesc gTaskDescREVCOUNT;
extern TaskDesc gTaskDescPrizeBoss;
extern TaskDesc gTaskDescCardEFFECT;
extern TaskDesc gTaskDescScrollbar;
extern TaskDesc gTaskDescHCEffectName;
extern TaskDesc gTaskDescNumberPlus;
extern TaskDesc gTaskDescLevelUp;
extern TaskDesc gTaskDescLVUPEFFECT;
extern TaskDesc gTaskDescLvupLogo;
extern TaskDesc gTaskDescEvMapObj;
extern TaskDesc gTaskDescEVBGEFFECT;
extern TaskDesc gTaskDescWorldSelBefore;
#ifndef VERSION_EU
extern TaskDesc gTaskDescDeckexchange;


#endif
extern Mode gModeRikuBtlTutorial;
extern Mode gModeRikuDeckTutorial;
extern TaskDesc gTaskDescPrint;
extern Mode gModeSioBattle;
extern Mode gModeSioBtlConnect;
extern Mode gModeSioBtlOption;
extern Mode gModeSioBtlCardget;
#ifndef VERSION_EU
extern Mode gModeSioChgConnect;


#endif
#ifndef VERSION_EU
extern Mode gModeSioChgCard;


#endif
extern Mode gModeSioError;
extern Mode gModeWLogo;
extern TaskDesc gTaskDescWLogo;
extern TaskDesc gTaskDescWlogoMons;
extern TaskDesc gTaskDescWlogoHwt;
extern TaskDesc gTaskDescWlogoHwtObj;
extern TaskDesc gTaskDescWlogoWon;
extern TaskDesc gTaskDescWlogoAtl;
extern TaskDesc gTaskDescWlogoNvl;
extern TaskDesc gTaskDescWlogoNvlMov;
extern TaskDesc gTaskDescWlogoNvlObj;
extern TaskDesc gTaskDescWlogoCol;
extern TaskDesc gTaskDescWlogoHlw;
extern TaskDesc gTaskDescWlogoDil;
extern TaskDesc gTaskDescWlogoAgr;
extern TaskDesc gTaskDescWlogoAgrSmoke;
extern TaskDesc gTaskDescWlogoAgrFlash0;
extern TaskDesc gTaskDescWlogoAgrFlash1;
extern TaskDesc gTaskDescWlogoTvt;
extern TaskDesc gTaskDescWlogoPoo;
extern TaskDesc gTaskDescWlogoPooObj;
extern TaskDesc gTaskDescWlogoTt;
extern TaskDesc gTaskDescWlogoTtObj;
extern TaskDesc gTaskDescWlogoTtLine;
extern TaskDesc gTaskDescWlogoBks;
extern TaskDesc gTaskDescWlogoBksObj;
extern TaskDesc gTaskDescBosTm;
extern TaskDesc gTaskDescBosTmBody;
extern TaskDesc gTaskDescBosTmFoot;
extern TaskDesc gTaskDescBosTmClb;
extern TaskDesc gTaskDescBosTmArm;
extern TaskDesc gTaskDescBosTmTbl;
extern TaskDesc gTaskDescBosJf;
extern TaskDesc gTaskDescBosJfMap;
extern TaskDesc gTaskDescBosJfLamp;
extern TaskDesc gTaskDescBosJfMajin;
extern TaskDesc gTaskDescBosDsd;
extern TaskDesc gTaskDescBosDsdMain;
extern TaskDesc gTaskDescBosDsdMap;
extern TaskDesc gTaskDescBosDsdIta;
extern TaskDesc gTaskDescBosDsdRock;
extern TaskDesc gTaskDescBosDsdCircle;
extern TaskDesc gTaskDescBosDsdEnergy1;
extern TaskDesc gTaskDescBosDsdEnergy2;
extern TaskDesc gTaskDescChgCardObj;
extern Mode gModePooh;
extern TaskDesc gTaskDescPooPooh;
extern TaskDesc gTaskDescPooMap;
extern TaskDesc gTaskDescPooSora;
extern TaskDesc gTaskDescPooBalloon;
extern TaskDesc gTaskDescPooShadow;
extern TaskDesc gTaskDescPooShadowdodai;
extern TaskDesc gTaskDescPooShadowscale;
extern TaskDesc gTaskDescPooFreeballoon;
extern TaskDesc gTaskDescPooGauge;
extern TaskDesc gTaskDescPooOwlballoon;
extern TaskDesc gTaskDescPooMapanime;
extern TaskDesc gTaskDescPooPile;
extern TaskDesc gTaskDescPooPiglet;
extern TaskDesc gTaskDescPooEeyore;
extern TaskDesc gTaskDescPooOwl;
extern TaskDesc gTaskDescPooRabbit;
extern TaskDesc gTaskDescPooTigger;
extern TaskDesc gTaskDescPooTiggerroo;
extern TaskDesc gTaskDescPooRoo;
extern TaskDesc gTaskDescPooRooFootmark;
extern TaskDesc gTaskDescPooLeaf;
extern TaskDesc gTaskDescPooTanpopo;
extern TaskDesc gTaskDescPooEeyoretail;
extern TaskDesc gTaskDescPooHoneycomb;
extern TaskDesc gTaskDescPooVegetable;
extern TaskDesc gTaskDescPooWagon;
extern TaskDesc gTaskDescPooWagonwheel;
extern TaskDesc gTaskDescPooSpark;
extern TaskDesc gTaskDescPooBee;
extern TaskDesc gTaskDescPooBeeAfterEvent;
extern TaskDesc gTaskDescPooCabbage;
extern TaskDesc gTaskDescPooCabbageborn;
extern TaskDesc gTaskDescPooMapobjhit;
extern TaskDesc gTaskDescPooPrize;
extern TaskDesc gTaskDescPooZzz;
extern TaskDesc gTaskDescPooButterfly;
extern TaskDesc gTaskDescPooMapbee;
extern TaskDesc gTaskDescPooMapbutterfly;
extern TaskDesc gTaskDescPooRabbitAfterEvent;
extern TaskDesc gTaskDescPooCabbageAfterEvent;
extern Mode gModeAllmap;
extern TaskDesc gTaskDescAllmapRoom;
extern TaskDesc gTaskDescAllmapCursor;
extern TaskDesc gTaskDescAllmapRoomname;
extern TaskDesc gTaskDescAllmapBar;
extern TaskDesc gTaskDescAllmapDoorinfo;
extern TaskDesc gTaskDescAllmapPusha;
extern Mode gModeTitle;
extern TaskDesc gTaskDescTitleLogo;
extern TaskDesc gTaskDescTitleObj;
extern TaskDesc gTaskDescTitleMenu;
extern TaskDesc gTaskDescTitleLumichange;
extern Mode gModeCopyright1;
extern Mode gModeCopyright2;
extern Mode gModeStatus;
extern TaskDesc gTaskDescStatus;
extern TaskDesc gTaskDescStatusBar;
extern TaskDesc gTaskDescStatusTab;
extern TaskDesc gTaskDescStatusSora;
extern TaskDesc gTaskDescStatusDeckname;
extern TaskDesc gTaskDescStatusCursor;
extern TaskDesc gTaskDescStatusStocklist;
extern TaskDesc gTaskDescStatusScrollcursor;
extern TaskDesc gTaskDescStatusMeswindow;
extern TaskDesc gTaskDescStatusMessage;
extern TaskDesc gTaskDescStatusFriend;
extern TaskDesc gTaskDescStockMesDisp;
extern TaskDesc gTaskDescBosBoogie;
extern TaskDesc gTaskDescBosBoogieDice;
extern TaskDesc gTaskDescBosBoogieExplosiondice;
extern TaskDesc gTaskDescBosBoogieSaku;
extern TaskDesc gTaskDescBosBoogieMap;
extern TaskDesc gTaskDescBosBoogieMapanime;
extern TaskDesc gTaskDescBosBoogieDisk;
extern TaskDesc gTaskDescBosBoogieKnife;
extern TaskDesc gTaskDescBosBoogieKnifereader;
extern TaskDesc gTaskDescBosBoogieKaihuku;
extern TaskDesc gTaskDescBosUrsula;
extern TaskDesc gTaskDescBosUrsulaMap;
extern TaskDesc gTaskDescBosUrsulaBorder;
extern TaskDesc gTaskDescBosUrsulaTako;
extern TaskDesc gTaskDescBosUrsulaBacktako;
extern TaskDesc gTaskDescBosUrsulaMapanime;
extern TaskDesc gTaskDescBosUrsulaBubble;
extern TaskDesc gTaskDescBosUrsulaBubbleSingle;
extern TaskDesc gTaskDescBosUrsulaThunder;
extern Mode gModeMapChk;
extern Mode gModeMapDbg;
extern Mode gModeMapFld;
extern Mode gModeMapFix;
extern Mode gModeMenuNew;
extern Mode gModeMenuLoad;
extern Mode gModeMenuMsg;
extern TaskDesc gTaskDescMapRnd;
extern TaskDesc gTaskDescMapFix;
extern TaskDesc gTaskDescMapDoor;
extern TaskDesc gTaskDescMapMenu;
extern TaskDesc gTaskDescMapSave;
extern TaskDesc gTaskDescMapAnm;
extern TaskDesc gTaskDescMapDbg;
extern TaskDesc gTaskDescMapGmkJump;
extern TaskDesc gTaskDescMapGmkEnm;
extern TaskDesc gTaskDescMapGmkDmy;
extern TaskDesc gTaskDescMapGmkTutorial;
extern TaskDesc gTaskDescMapGmkSpider;
extern TaskDesc gTaskDescMapGmk00;
extern TaskDesc gTaskDescMapPrize;
extern TaskDesc gTaskDescMapPrzCard;
extern TaskDesc gTaskDescMapPrzStock;
extern TaskDesc gTaskDescMapMsg;
extern TaskDesc gTaskDescMapSpark;
extern TaskDesc gTaskDescMapTalk;
extern TaskDesc gTaskDescMapDonald;
extern TaskDesc gTaskDescMapGoofy;
extern TaskDesc gTaskDescMapNamine;
extern TaskDesc gTaskDescMapNiseriku;
extern TaskDesc gTaskDescMapMickey;
extern TaskDesc gTaskDescMapTutorial;
extern TaskDesc gTaskDescMapStair;
extern TaskDesc gTaskDescMapDmg;
extern TaskDesc gTaskDescMapFloor;
extern TaskDesc gTaskDescBosGa;
extern TaskDesc gTaskDescBosMd;
extern TaskDesc gTaskDescBosMdMap;
extern TaskDesc gTaskDescBosMdFire;
extern TaskDesc gTaskDescBosMdDai;
extern TaskDesc gTaskDescBosMdHahen;
extern Mode gModeWorldselect;
extern Mode gModeWorldinspect;
extern Mode gModeWorldwarp;
extern Mode gModeMsTop;
extern Mode gModeMsShop;
extern Mode gModeMsCharge;
extern Mode gModeMapinspect;
extern TaskDesc gTaskDescMsShopHosi;
extern Mode gModeBackupstat;
extern TaskDesc gTaskDescBosPc;
extern TaskDesc gTaskDescBosPcFld;
extern TaskDesc gTaskDescBosPcFlt;
extern TaskDesc gTaskDescBosPcAcd;
extern TaskDesc gTaskDescBosLst;
extern TaskDesc gTaskDescBosLstFld;
extern TaskDesc gTaskDescBosLstBit;
extern TaskDesc gTaskDescBosLstLsr;
extern TaskDesc gTaskDescBosLstFal;
extern TaskDesc gTaskDescBosLstCtr;
extern TaskDesc gTaskDescBosLstSnp;
extern Mode gModeStaffRoll;
extern TaskDesc gTaskDescSrollAName;
extern TaskDesc gTaskDescSrollBChar;
extern TaskDesc gTaskDescSrollBLogo;
extern TaskDesc gTaskDescSrollBSecn;
extern TaskDesc gTaskDescSrollBCrtn;
extern TaskDesc gTaskDescSrollCChar;

extern const char gTaskNameLockon[];
extern const char gModeNameContinue[];
extern const char gTaskNameEventSeq[];
extern const char gTaskNameEventChara[];
extern const char gTaskNameMsgwin[];
extern const char gTaskNameMsgface[];
extern const char gTaskNameMsgwait[];
extern const char gTaskNameMsgwaitYesno[];
extern const char gTaskNameView[];
extern const char gModeNameEventselect[];
extern const char gTaskNameHanabira[];
extern const char gTaskNameHanabiraC[];
extern const char gTaskNameSmoke[];
extern const char gTaskNameExclamation[];
extern const char gTaskNameBalloon[];
extern const char gTaskNameQuestion[];
extern const char gTaskNameGlowNose[];
extern const char gTaskNameDown[];
extern const char gTaskNameTinkerbell[];
extern const char gTaskNameEvSound[];
extern const char gTaskNameCardBattleSora[];
extern const char gTaskNameCardBattleRiku[];
extern const char gTaskNameBosscard[];
extern const char gTaskNameMapAnim[];
extern const char gTaskNameMapSelect[];
extern const char gTaskNameMapcard[];
extern const char gTaskNamePrizeCardInit[];
extern const char gTaskNamePrizeCardInitBoss[];
extern const char gTaskNameDispCardname[];
extern const char gTaskNameVersion[];
extern const char gTaskNameSpotLight[];
extern const char gTaskNameSELMAPEVKEY[];
extern const char gTaskNameReloadChildren[];
extern const char gTaskNameREVCOUNT[];
extern const char gTaskNamePrizeBoss[];
extern const char gTaskNameCardEFFECT[];
extern const char gTaskNameScrollbar[];
extern const char gTaskNameHCEffectName[];
extern const char gTaskNameNumberPlus[];
extern const char gTaskNameLevelUp[];
extern const char gTaskNameLVUPEFFECT[];
extern const char gTaskNameLvupLogo[];
extern const char gTaskNameEvMapObj[];
extern const char gTaskNameEVBGEFFECT[];
extern const char gTaskNameWorldSelBefore[];
#ifndef VERSION_EU
extern const char gTaskNameDeckexchange[];


#endif
extern const char gModeNameRikuBtlTutorial[];
extern const char gModeNameRikuDeckTutorial[];
extern const char gTaskNamePrint[];
extern const char gModeNameSioBattle[];
extern const char gModeNameSioBtlConnect[];
extern const char gModeNameSioBtlOption[];
extern const char gModeNameSioBtlCardget[];
#ifndef VERSION_EU
extern const char gModeNameSioChgConnect[];


#endif
#ifndef VERSION_EU
extern const char gModeNameSioChgCard[];


#endif
extern const char gModeNameSioError[];
extern const char gModeNameWLogo[];
extern const char gTaskNameWLogo[];
extern const char gTaskNameWlogoMons[];
extern const char gTaskNameWlogoHwt[];
extern const char gTaskNameWlogoHwtObj[];
extern const char gTaskNameWlogoWon[];
extern const char gTaskNameWlogoAtl[];
extern const char gTaskNameWlogoNvl[];
extern const char gTaskNameWlogoNvlMov[];
extern const char gTaskNameWlogoNvlObj[];
extern const char gTaskNameWlogoCol[];
extern const char gTaskNameWlogoHlw[];
extern const char gTaskNameWlogoDil[];
extern const char gTaskNameWlogoAgr[];
extern const char gTaskNameWlogoAgrSmoke[];
extern const char gTaskNameWlogoAgrFlash0[];
extern const char gTaskNameWlogoAgrFlash1[];
extern const char gTaskNameWlogoTvt[];
extern const char gTaskNameWlogoPoo[];
extern const char gTaskNameWlogoPooObj[];
extern const char gTaskNameWlogoTt[];
extern const char gTaskNameWlogoTtObj[];
extern const char gTaskNameWlogoTtLine[];
extern const char gTaskNameWlogoBks[];
extern const char gTaskNameWlogoBksObj[];
extern const char gTaskNameBosTm[];
extern const char gTaskNameBosTmBody[];
extern const char gTaskNameBosTmFoot[];
extern const char gTaskNameBosTmClb[];
extern const char gTaskNameBosTmArm[];
extern const char gTaskNameBosTmTbl[];
extern const char gTaskNameBosJf[];
extern const char gTaskNameBosJfMap[];
extern const char gTaskNameBosJfLamp[];
extern const char gTaskNameBosJfMajin[];
extern const char gTaskNameBosDsd[];
extern const char gTaskNameBosDsdMain[];
extern const char gTaskNameBosDsdMap[];
extern const char gTaskNameBosDsdIta[];
extern const char gTaskNameBosDsdRock[];
extern const char gTaskNameBosDsdCircle[];
extern const char gTaskNameBosDsdEnergy1[];
extern const char gTaskNameBosDsdEnergy2[];
extern const char gModeNamePooh[];
extern const char gTaskNamePooPooh[];
extern const char gTaskNamePooMap[];
extern const char gTaskNamePooSora[];
extern const char gTaskNamePooBalloon[];
extern const char gTaskNamePooShadow[];
extern const char gTaskNamePooShadowdodai[];
extern const char gTaskNamePooShadowscale[];
extern const char gTaskNamePooFreeballoon[];
extern const char gTaskNamePooGauge[];
extern const char gTaskNamePooOwlballoon[];
extern const char gTaskNamePooMapanime[];
extern const char gTaskNamePooPile[];
extern const char gTaskNamePooPiglet[];
extern const char gTaskNamePooEeyore[];
extern const char gTaskNamePooOwl[];
extern const char gTaskNamePooRabbit[];
extern const char gTaskNamePooTigger[];
extern const char gTaskNamePooTiggerroo[];
extern const char gTaskNamePooRoo[];
extern const char gTaskNamePooRooFootmark[];
extern const char gTaskNamePooLeaf[];
extern const char gTaskNamePooTanpopo[];
extern const char gTaskNamePooEeyoretail[];
extern const char gTaskNamePooHoneycomb[];
extern const char gTaskNamePooVegetable[];
extern const char gTaskNamePooWagon[];
extern const char gTaskNamePooWagonwheel[];
extern const char gTaskNamePooSpark[];
extern const char gTaskNamePooBee[];
extern const char gTaskNamePooBeeAfterEvent[];
extern const char gTaskNamePooCabbage[];
extern const char gTaskNamePooCabbageborn[];
extern const char gTaskNamePooMapobjhit[];
extern const char gTaskNamePooPrize[];
extern const char gTaskNamePooZzz[];
extern const char gTaskNamePooButterfly[];
extern const char gTaskNamePooMapbee[];
extern const char gTaskNamePooMapbutterfly[];
extern const char gTaskNamePooRabbitAfterEvent[];
extern const char gTaskNamePooCabbageAfterEvent[];
extern const char gTaskNameAllmapRoom[];
extern const char gTaskNameAllmapCursor[];
extern const char gTaskNameAllmapRoomname[];
extern const char gTaskNameAllmapBar[];
extern const char gTaskNameAllmapDoorinfo[];
extern const char gTaskNameAllmapPusha[];
extern const char gTaskNameTitleLogo[];
extern const char gTaskNameTitleObj[];
extern const char gTaskNameTitleMenu[];
extern const char gTaskNameTitleLumichange[];
extern const char gTaskNameStatus[];
extern const char gTaskNameStatusBar[];
extern const char gTaskNameStatusTab[];
extern const char gTaskNameStatusSora[];
extern const char gTaskNameStatusDeckname[];
extern const char gTaskNameStatusCursor[];
extern const char gTaskNameStatusStocklist[];
extern const char gTaskNameStatusScrollcursor[];
extern const char gTaskNameStatusMeswindow[];
extern const char gTaskNameStatusMessage[];
extern const char gTaskNameStatusFriend[];
extern const char gTaskNameStockMesDisp[];
extern const char gTaskNameBosBoogie[];
extern const char gTaskNameBosBoogieDice[];
extern const char gTaskNameBosBoogieExplosiondice[];
extern const char gTaskNameBosBoogieSaku[];
extern const char gTaskNameBosBoogieMap[];
extern const char gTaskNameBosBoogieMapanime[];
extern const char gTaskNameBosBoogieDisk[];
extern const char gTaskNameBosBoogieKnife[];
extern const char gTaskNameBosBoogieKnifereader[];
extern const char gTaskNameBosBoogieKaihuku[];
extern const char gTaskNameBosUrsula[];
extern const char gTaskNameBosUrsulaMap[];
extern const char gTaskNameBosUrsulaBorder[];
extern const char gTaskNameBosUrsulaTako[];
extern const char gTaskNameBosUrsulaBacktako[];
extern const char gTaskNameBosUrsulaMapanime[];
extern const char gTaskNameBosUrsulaBubble[];
extern const char gTaskNameBosUrsulaBubbleSingle[];
extern const char gTaskNameBosUrsulaThunder[];
extern const char gModeNameMapChk[];
extern const char gModeNameMapDbg[];
extern const char gModeNameMapFld[];
extern const char gModeNameMapFix[];
extern const char gModeNameMenuNew[];
extern const char gModeNameMenuLoad[];
extern const char gModeNameMenuMsg[];
extern const char gTaskNameMapRnd[];
extern const char gTaskNameMapFix[];
extern const char gTaskNameMapDoor[];
extern const char gTaskNameMapMenu[];
extern const char gTaskNameMapSave[];
extern const char gTaskNameMapAnm[];
extern const char gTaskNameMapDbg[];
extern const char gTaskNameMapGmkJump[];
extern const char gTaskNameMapGmkEnm[];
extern const char gTaskNameMapGmkDmy[];
extern const char gTaskNameMapGmkTutorial[];
extern const char gTaskNameMapGmkSpider[];
extern const char gTaskNameMapGmk00[];
extern const char gTaskNameMapPrize[];
extern const char gTaskNameMapPrzCard[];
extern const char gTaskNameMapPrzStock[];
extern const char gTaskNameMapMsg[];
extern const char gTaskNameMapSpark[];
extern const char gTaskNameMapTalk[];
extern const char gTaskNameMapDonald[];
extern const char gTaskNameMapGoofy[];
extern const char gTaskNameMapNamine[];
extern const char gTaskNameMapNiseriku[];
extern const char gTaskNameMapMickey[];
extern const char gTaskNameMapTutorial[];
extern const char gTaskNameMapStair[];
extern const char gTaskNameMapDmg[];
extern const char gTaskNameMapFloor[];
extern const char gTaskNameBosGa[];
extern const char gTaskNameBosMd[];
extern const char gTaskNameBosMdMap[];
extern const char gTaskNameBosMdFire[];
extern const char gTaskNameBosMdDai[];
extern const char gTaskNameBosMdHahen[];
extern const char gModeNameWorldselect[];
extern const char gModeNameMsTop[];
extern const char gTaskNameBosPc[];
extern const char gTaskNameBosPcFld[];
extern const char gTaskNameBosPcFlt[];
extern const char gTaskNameBosPcAcd[];
extern const char gTaskNameBosLst[];
extern const char gTaskNameBosLstFld[];
extern const char gTaskNameBosLstBit[];
extern const char gTaskNameBosLstLsr[];
extern const char gTaskNameBosLstFal[];
extern const char gTaskNameBosLstCtr[];
extern const char gTaskNameBosLstSnp[];
extern const char gModeNameStaffRoll[];

extern TaskDesc gUnk_09EE2834;
extern TaskDesc gUnk_09EE284C;
extern TaskDesc gUnk_09EE484C;
extern TaskDesc gUnk_09EE48DC;
extern TaskDesc gUnk_09EE496C;
extern TaskDesc gUnk_09EE4984;
extern TaskDesc gUnk_09EE499C;
extern TaskDesc gUnk_09EE49CC;
extern TaskDesc gUnk_09EE49E4;
extern TaskDesc gUnk_09EE49FC;
extern TaskDesc gUnk_09EE4AF4;
extern TaskDesc gUnk_09EE4B28;
extern TaskDesc gUnk_09EE4B40;
extern TaskDesc gUnk_09EE4B58;
extern TaskDesc gUnk_09EE4B70;
extern TaskDesc gUnk_09EE4B88;
extern TaskDesc gUnk_09EE7560;
extern TaskDesc gUnk_09EE75D8;
extern TaskDesc gUnk_09EE7650;
extern TaskDesc gUnk_09EE772C;
extern TaskDesc gUnk_09EE778C;
extern TaskDesc gUnk_09EE77A4;
extern TaskDesc gUnk_09EE77BC;
extern TaskDesc gUnk_09EE77D4;
extern TaskDesc gUnk_09EE77EC;
extern TaskDesc gUnk_09EE7804;
extern TaskDesc gUnk_09EE781C;
extern TaskDesc gUnk_09EE7834;
extern TaskDesc gUnk_09EE784C;
extern TaskDesc gUnk_09EE7864;
extern TaskDesc gUnk_09EE787C;
extern TaskDesc gUnk_09EE7F30;
extern TaskDesc gUnk_09EE7F48;
extern TaskDesc gUnk_09EE7F60;
extern TaskDesc gUnk_09EE7F78;
extern TaskDesc gUnk_09EE7F90;
extern TaskDesc gUnk_09EE7FA8;
extern TaskDesc gUnk_09EE7FC0;
extern TaskDesc gUnk_09EE7FD8;
extern TaskDesc gUnk_09EE7FF0;
extern TaskDesc gUnk_09EE8E18;
extern TaskDesc gUnk_09EE8E30;
extern TaskDesc gUnk_09EE8E48;
extern TaskDesc gUnk_09EE8EF0;
extern TaskDesc gUnk_09EE8F30;
extern const char gTaskName_09EE2834[];
extern const char gTaskName_09EE48DC[];
extern const char gTaskName_09EE496C[];
extern const char gTaskName_09EE4984[];
extern const char gTaskName_09EE499C[];
extern const char gTaskName_09EE49CC[];
extern const char gTaskName_09EE49E4[];
extern const char gTaskName_09EE49FC[];
extern const char gTaskName_09EE4AF4[];
extern const char gTaskName_09EE4B28[];
extern const char gTaskName_09EE4B40[];
extern const char gTaskName_09EE4B58[];
extern const char gTaskName_09EE7560[];
extern const char gTaskName_09EE75D8[];
extern const char gTaskName_09EE7650[];
extern const char gTaskName_09EE772C[];
extern const char gTaskName_09EE778C[];
extern const char gTaskName_09EE77A4[];
extern const char gTaskName_09EE77BC[];
extern const char gTaskName_09EE77D4[];
extern const char gTaskName_09EE7804[];
extern const char gTaskName_09EE781C[];
extern const char gTaskName_09EE7834[];
extern const char gTaskName_09EE784C[];
extern const char gTaskName_09EE7864[];
extern const char gTaskName_09EE7F30[];
extern const char gTaskName_09EE7F48[];
extern const char gTaskName_09EE7F60[];
extern const char gTaskName_09EE7F78[];
extern const char gTaskName_09EE7F90[];
extern const char gTaskName_09EE7FA8[];
extern const char gTaskName_09EE8E18[];
extern const char gTaskName_09EE8E30[];
extern const char gTaskName_09EE8EF0[];
extern const char gTaskName_09EE8F30[];

extern TaskDesc gUnk_09EF2A5C;
extern TaskDesc gUnk_09EF2A74;
extern TaskDesc gUnk_09EF34A8;
extern TaskDesc gUnk_09EF34D8;
extern TaskDesc gUnk_09EF48E0;
extern TaskDesc gUnk_09EF48F8;
extern TaskDesc gUnk_09EF49A0;
extern TaskDesc gUnk_09EF49D0;
extern TaskDesc gUnk_09EF4A18;
extern TaskDesc gUnk_09EF4A30;
extern TaskDesc gUnk_09EF4B38;
extern TaskDesc gUnk_09EF4CF0;
extern TaskDesc gUnk_09EF4D08;
extern TaskDesc gUnk_09EF4D38;
extern TaskDesc gUnk_09EF4D68;
extern TaskDesc gUnk_09EF6B90;
extern TaskDesc gUnk_09EF6BA8;
extern TaskDesc gUnk_09EF6BC0;
extern TaskDesc gUnk_09EF6BD8;
extern TaskDesc gUnk_09EF6BF0;
extern TaskDesc gUnk_09EF6C08;
extern TaskDesc gUnk_09EF6C20;
extern TaskDesc gUnk_09EF6CCC;
extern TaskDesc gUnk_09EF6CE4;
extern TaskDesc gUnk_09EF6CFC;
extern TaskDesc gUnk_09EF6D14;
extern TaskDesc gUnk_09EF6D2C;
extern TaskDesc gUnk_09EF6D44;
extern TaskDesc gUnk_09EF6D5C;
extern TaskDesc gUnk_09EF6D74;
extern TaskDesc gUnk_09EF6D8C;
extern TaskDesc gUnk_09EF6DA4;
extern TaskDesc gUnk_09EF6DD4;
extern TaskDesc gUnk_09EF6DEC;
extern TaskDesc gUnk_09EF6E04;
extern TaskDesc gUnk_09EF6E1C;
extern TaskDesc gUnk_09EF6E34;
extern TaskDesc gUnk_09EF6EAC;
extern TaskDesc gUnk_09EF6F9C;
extern TaskDesc gUnk_09EF70B8;
extern TaskDesc gUnk_09EF9E8C;
extern TaskDesc gUnk_09EF9EF4;
extern TaskDesc gUnk_09EFAA64;

extern const char gTaskName_09EF2A5C[];
extern const char gTaskName_09EF2A74[];
extern const char gTaskName_09EF48E0[];
extern const char gTaskName_09EF48F8[];
extern const char gTaskName_09EF49A0[];
extern const char gTaskName_09EF49D0[];
extern const char gTaskName_09EF4A18[];
extern const char gTaskName_09EF4A30[];
extern const char gTaskName_09EF4B38[];
extern const char gTaskName_09EF4CF0[];
extern const char gTaskName_09EF4D08[];
extern const char gTaskName_09EF4D38[];
extern const char gTaskName_09EF4D68[];
extern const char gTaskName_09EF6B90[];
extern const char gTaskName_09EF6BA8[];
extern const char gTaskName_09EF6BC0[];
extern const char gTaskName_09EF6BD8[];
extern const char gTaskName_09EF6BF0[];
extern const char gTaskName_09EF6C08[];
extern const char gTaskName_09EF6C20[];
extern const char gTaskName_09EF6CCC[];
extern const char gTaskName_09EF6CE4[];
extern const char gTaskName_09EF6CFC[];
extern const char gTaskName_09EF6D14[];
extern const char gTaskName_09EF6D2C[];
extern const char gTaskName_09EF6D44[];
extern const char gTaskName_09EF6D5C[];
extern const char gTaskName_09EF6D74[];
extern const char gTaskName_09EF6D8C[];
extern const char gTaskName_09EF6DA4[];
extern const char gTaskName_09EF6DD4[];
extern const char gTaskName_09EF6DEC[];
extern const char gTaskName_09EF6E04[];
extern const char gTaskName_09EF6E1C[];
extern const char gTaskName_09EF6E34[];
extern const char gTaskName_09EF6EAC[];
extern const char gTaskName_09EF6F9C[];
extern const char gTaskName_09EF9E8C[];
extern const char gTaskName_09EF9EF4[];

extern const char gModeNameEvent[];
extern Mode gUnk_09EE273C;
extern Mode gUnk_09EE274C;

extern Mode gUnk_09EE4BA0;
extern const char gUnk_090359BC[];

extern const char gModeNameSioDbgFlg[];
extern Mode gModeSioDbgFlg;

#ifdef VERSION_EU
extern const char gTaskNameFrdPoohEu[];
extern TaskDesc gTaskDescFrdPoohEu;
#endif

#endif
