#ifndef GUARD_REGISTRATION_DATA_H
#define GUARD_REGISTRATION_DATA_H

#include "task_descriptors.h"
#include "taskpool.h"
#include "mode.h"

extern Mode gModeJiminy;
extern TaskDesc gTaskDescMonsgage;
extern TaskDesc gTaskDescBtlPopCb;
extern TaskDesc gTaskDescBtlExp;
extern TaskDesc gTaskDescBtlVslockon;
extern TaskDesc gTaskDescBtlHpoth;
extern TaskDesc gTaskDescTutorial;
extern Mode gModeMovie;
extern TaskDesc gTaskDescLockon;
extern TaskDesc gTaskDescEventSeq;
extern TaskDesc gTaskDescEventChara;
extern TaskDesc gTaskDescMsgwin;
extern TaskDesc gTaskDescMsgface[3];
extern TaskDesc gTaskDescView;
extern Mode gModeEventselect;
extern TaskDesc gTaskDescHanabira;
extern TaskDesc gTaskDescHanabiraC;
extern TaskDesc gTaskDescSmoke;
extern TaskDesc gTaskDescExclamation;
extern TaskDesc gTaskDescBalloon;
extern TaskDesc gTaskDescQuestion;
extern TaskDesc gTaskDescGlowNose;
extern TaskDesc gTaskDescGlowNose2;
extern TaskDesc gTaskDescDown;
extern TaskDesc gTaskDescTinkerbell;
extern TaskDesc gTaskDescEvSound;
extern TaskDesc gTaskDescCardBattleSora;
extern TaskDesc gTaskDescCardBattleRiku;
extern TaskDesc gTaskDescBosscard;
extern TaskDesc gTaskDescMapAnim;
extern TaskDesc gTaskDescMapSelect;
extern TaskDesc gTaskDescMapcard;
extern TaskDesc gTaskDescPrizeCardInit;
extern TaskDesc gTaskDescPrizeCardInitBoss;
extern TaskDesc gTaskDescDispCardname;
extern TaskDesc gTaskDescVersion;
extern TaskDesc gTaskDescSpotLight;
extern TaskDesc gTaskDescSELMAPEVKEY;
extern TaskDesc gTaskDescReloadChildren;
extern TaskDesc gTaskDescREVCOUNT;
extern TaskDesc gTaskDescPrizeBoss;
extern TaskDesc gTaskDescCardEFFECT;
extern TaskDesc gTaskDescScrollbar;
extern TaskDesc gTaskDescHCEffectName;
extern TaskDesc gTaskDescNumberPlus;
extern TaskDesc gTaskDescLevelUp;
extern TaskDesc gTaskDescLVUPEFFECT;
extern TaskDesc gTaskDescLvupLogo;
extern TaskDesc gTaskDescEvMapObj;
extern TaskDesc gTaskDescEVBGEFFECT;
extern TaskDesc gTaskDescWorldSelBefore;
#ifndef VERSION_EU
extern TaskDesc gTaskDescDeckexchange;


#endif
extern Mode gModeRikuBtlTutorial;
extern Mode gModeRikuDeckTutorial;
extern TaskDesc gTaskDescPrint;
extern Mode gModeSioBattle;
extern Mode gModeSioBtlConnect;
extern Mode gModeSioBtlOption;
extern Mode gModeSioBtlCardget;
#ifndef VERSION_EU
extern Mode gModeSioChgConnect;


#endif
#ifndef VERSION_EU
extern Mode gModeSioChgCard;


#endif
extern Mode gModeSioError;
extern Mode gModeWLogo;
extern TaskDesc gTaskDescWLogo;
extern TaskDesc gTaskDescWlogoMons;
extern TaskDesc gTaskDescWlogoHwt;
extern TaskDesc gTaskDescWlogoHwtObj;
extern TaskDesc gTaskDescWlogoWon;
extern TaskDesc gTaskDescWlogoAtl;
extern TaskDesc gTaskDescWlogoNvl;
extern TaskDesc gTaskDescWlogoNvlMov;
extern TaskDesc gTaskDescWlogoNvlObj;
extern TaskDesc gTaskDescWlogoCol;
extern TaskDesc gTaskDescWlogoHlw;
extern TaskDesc gTaskDescWlogoDil;
extern TaskDesc gTaskDescWlogoAgr;
extern TaskDesc gTaskDescWlogoAgrSmoke;
extern TaskDesc gTaskDescWlogoAgrFlash0;
extern TaskDesc gTaskDescWlogoAgrFlash1;
extern TaskDesc gTaskDescWlogoTvt;
extern TaskDesc gTaskDescWlogoPoo;
extern TaskDesc gTaskDescWlogoPooObj;
extern TaskDesc gTaskDescWlogoTt;
extern TaskDesc gTaskDescWlogoTtObj;
extern TaskDesc gTaskDescWlogoTtLine;
extern TaskDesc gTaskDescWlogoBks;
extern TaskDesc gTaskDescWlogoBksObj;
extern TaskDesc gTaskDescBosTm;
extern TaskDesc gTaskDescBosTmBody;
extern TaskDesc gTaskDescBosTmFoot;
extern TaskDesc gTaskDescBosTmClb;
extern TaskDesc gTaskDescBosTmArm;
extern TaskDesc gTaskDescBosTmTbl;
extern TaskDesc gTaskDescBosJf;
extern TaskDesc gTaskDescBosJfMap;
extern TaskDesc gTaskDescBosJfLamp;
extern TaskDesc gTaskDescBosJfMajin;
extern TaskDesc gTaskDescBosDsd;
extern TaskDesc gTaskDescBosDsdMain;
extern TaskDesc gTaskDescBosDsdMap;
extern TaskDesc gTaskDescBosDsdIta;
extern TaskDesc gTaskDescBosDsdRock;
extern TaskDesc gTaskDescBosDsdCircle;
extern TaskDesc gTaskDescBosDsdEnergy1;
extern TaskDesc gTaskDescBosDsdEnergy2;
extern TaskDesc gTaskDescChgCardObj;
extern Mode gModePooh;
extern TaskDesc gTaskDescPooPooh;
extern TaskDesc gTaskDescPooMap;
extern TaskDesc gTaskDescPooSora;
extern TaskDesc gTaskDescPooBalloon;
extern TaskDesc gTaskDescPooShadow;
extern TaskDesc gTaskDescPooShadowdodai;
extern TaskDesc gTaskDescPooShadowscale;
extern TaskDesc gTaskDescPooFreeballoon;
extern TaskDesc gTaskDescPooGauge;
extern TaskDesc gTaskDescPooOwlballoon;
extern TaskDesc gTaskDescPooMapanime;
extern TaskDesc gTaskDescPooPile;
extern TaskDesc gTaskDescPooPiglet;
extern TaskDesc gTaskDescPooEeyore;
extern TaskDesc gTaskDescPooOwl;
extern TaskDesc gTaskDescPooRabbit;
extern TaskDesc gTaskDescPooTigger;
extern TaskDesc gTaskDescPooTiggerroo;
extern TaskDesc gTaskDescPooRoo;
extern TaskDesc gTaskDescPooRooFootmark;
extern TaskDesc gTaskDescPooLeaf;
extern TaskDesc gTaskDescPooTanpopo;
extern TaskDesc gTaskDescPooEeyoretail;
extern TaskDesc gTaskDescPooHoneycomb;
extern TaskDesc gTaskDescPooVegetable;
extern TaskDesc gTaskDescPooWagon;
extern TaskDesc gTaskDescPooWagonwheel;
extern TaskDesc gTaskDescPooSpark;
extern TaskDesc gTaskDescPooBee;
extern TaskDesc gTaskDescPooBeeAfterEvent;
extern TaskDesc gTaskDescPooCabbage;
extern TaskDesc gTaskDescPooCabbageborn;
extern TaskDesc gTaskDescPooMapobjhit;
extern TaskDesc gTaskDescPooPrize;
extern TaskDesc gTaskDescPooZzz;
extern TaskDesc gTaskDescPooButterfly;
extern TaskDesc gTaskDescPooMapbee;
extern TaskDesc gTaskDescPooMapbutterfly;
extern TaskDesc gTaskDescPooRabbitAfterEvent;
extern TaskDesc gTaskDescPooCabbageAfterEvent;
extern Mode gModeAllmap;
extern TaskDesc gTaskDescAllmapRoom;
extern TaskDesc gTaskDescAllmapCursor;
extern TaskDesc gTaskDescAllmapRoomname;
extern TaskDesc gTaskDescAllmapBar;
extern TaskDesc gTaskDescAllmapDoorinfo;
extern TaskDesc gTaskDescAllmapPusha;
extern Mode gModeTitle;
extern TaskDesc gTaskDescTitleLogo;
extern TaskDesc gTaskDescTitleObj;
extern TaskDesc gTaskDescTitleMenu;
extern TaskDesc gTaskDescTitleLumichange;
extern Mode gModeCopyright1;
extern Mode gModeCopyright2;
extern Mode gModeStatus;
extern TaskDesc gTaskDescStatus;
extern TaskDesc gTaskDescStatusBar;
extern TaskDesc gTaskDescStatusTab;
extern TaskDesc gTaskDescStatusSora;
extern TaskDesc gTaskDescStatusDeckname;
extern TaskDesc gTaskDescStatusCursor;
extern TaskDesc gTaskDescStatusStocklist;
extern TaskDesc gTaskDescStatusScrollcursor;
extern TaskDesc gTaskDescStatusMeswindow;
extern TaskDesc gTaskDescStatusMessage;
extern TaskDesc gTaskDescStatusFriend;
extern TaskDesc gTaskDescStockMesDisp;
extern TaskDesc gTaskDescBosBoogie;
extern TaskDesc gTaskDescBosBoogieDice;
extern TaskDesc gTaskDescBosBoogieExplosiondice;
extern TaskDesc gTaskDescBosBoogieSaku;
extern TaskDesc gTaskDescBosBoogieMap;
extern TaskDesc gTaskDescBosBoogieMapanime;
extern TaskDesc gTaskDescBosBoogieDisk;
extern TaskDesc gTaskDescBosBoogieKnife;
extern TaskDesc gTaskDescBosBoogieKnifereader;
extern TaskDesc gTaskDescBosBoogieKaihuku;
extern TaskDesc gTaskDescBosUrsula;
extern TaskDesc gTaskDescBosUrsulaMap;
extern TaskDesc gTaskDescBosUrsulaBorder;
extern TaskDesc gTaskDescBosUrsulaTako;
extern TaskDesc gTaskDescBosUrsulaBacktako;
extern TaskDesc gTaskDescBosUrsulaMapanime;
extern TaskDesc gTaskDescBosUrsulaBubble;
extern TaskDesc gTaskDescBosUrsulaBubbleSingle;
extern TaskDesc gTaskDescBosUrsulaThunder;
extern Mode gModeMapChk;
extern Mode gModeMapDbg;
extern Mode gModeMapFld;
extern Mode gModeMapFix;
extern Mode gModeMenuNew;
extern Mode gModeMenuLoad;
extern Mode gModeMenuMsg;
extern TaskDesc gTaskDescMapRnd;
extern TaskDesc gTaskDescMapFix;
extern TaskDesc gTaskDescMapDoor;
extern TaskDesc gTaskDescMapMenu;
extern TaskDesc gTaskDescMapSave;
extern TaskDesc gTaskDescMapAnm;
extern TaskDesc gTaskDescMapDbg;
extern TaskDesc gTaskDescMapGmkJump;
extern TaskDesc gTaskDescMapGmkEnm;
extern TaskDesc gTaskDescMapGmkDmy;
extern TaskDesc gTaskDescMapGmkTutorial;
extern TaskDesc gTaskDescMapGmkSpider;
extern TaskDesc gTaskDescMapGmk00;
extern TaskDesc gTaskDescMapPrize;
extern TaskDesc gTaskDescMapPrzCard;
extern TaskDesc gTaskDescMapPrzStock;
extern TaskDesc gTaskDescMapMsg;
extern TaskDesc gTaskDescMapSpark;
extern TaskDesc gTaskDescMapTalk;
extern TaskDesc gTaskDescMapDonald;
extern TaskDesc gTaskDescMapGoofy;
extern TaskDesc gTaskDescMapNamine;
extern TaskDesc gTaskDescMapNiseriku;
extern TaskDesc gTaskDescMapMickey;
extern TaskDesc gTaskDescMapTutorial;
extern TaskDesc gTaskDescMapStair;
extern TaskDesc gTaskDescMapDmg;
extern TaskDesc gTaskDescMapFloor;
extern TaskDesc gTaskDescBosGa;
extern TaskDesc gTaskDescBosMd;
extern TaskDesc gTaskDescBosMdMap;
extern TaskDesc gTaskDescBosMdFire;
extern TaskDesc gTaskDescBosMdDai;
extern TaskDesc gTaskDescBosMdHahen;
extern Mode gModeWorldselect;
extern Mode gModeWorldinspect;
extern Mode gModeWorldwarp;
extern Mode gModeMsTop;
extern Mode gModeMsShop;
extern Mode gModeMsCharge;
extern Mode gModeMapinspect;
extern TaskDesc gTaskDescMsShopHosi;
extern Mode gModeBackupstat;
extern TaskDesc gTaskDescBosPc;
extern TaskDesc gTaskDescBosPcFld;
extern TaskDesc gTaskDescBosPcFlt;
extern TaskDesc gTaskDescBosPcAcd;
extern TaskDesc gTaskDescBosLst;
extern TaskDesc gTaskDescBosLstFld;
extern TaskDesc gTaskDescBosLstBit;
extern TaskDesc gTaskDescBosLstLsr;
extern TaskDesc gTaskDescBosLstFal;
extern TaskDesc gTaskDescBosLstCtr;
extern TaskDesc gTaskDescBosLstSnp;
extern Mode gModeStaffRoll;
extern TaskDesc gTaskDescSrollAName;
extern TaskDesc gTaskDescSrollBChar;
extern TaskDesc gTaskDescSrollBLogo;
extern TaskDesc gTaskDescSrollBSecn;
extern TaskDesc gTaskDescSrollBCrtn;
extern TaskDesc gTaskDescSrollCChar;

extern const char gModeNameSioBattle[];
extern const char gModeNameSioBtlConnect[];
extern const char gTaskNameBosJfLamp[];
extern const char gTaskNameBosJfMajin[];
extern const char gTaskNameBosDsd[];
extern const char gTaskNameBosDsdMain[];
extern const char gTaskNameBosDsdMap[];
extern const char gTaskNameBosDsdIta[];
extern const char gTaskNameBosDsdRock[];
extern const char gTaskNamePooPooh[];
extern const char gTaskNamePooMap[];
extern const char gTaskNamePooPile[];
extern const char gTaskNamePooOwl[];
extern const char gTaskNamePooRabbit[];
extern const char gTaskNamePooSpark[];
extern const char gTaskNamePooBeeAfterEvent[];
extern const char gTaskNamePooCabbageborn[];
extern const char gTaskNameStatus[];
extern const char gTaskNameStatusBar[];
extern const char gTaskNameStatusTab[];
extern const char gTaskNameStatusSora[];
extern const char gTaskNameStatusDeckname[];
extern const char gTaskNameStatusCursor[];
extern const char gTaskNameStatusStocklist[];
extern const char gTaskNameStatusScrollcursor[];
extern const char gTaskNameStatusMeswindow[];
extern const char gTaskNameStatusMessage[];
extern const char gTaskNameStatusFriend[];
extern const char gModeNameMapDbg[];
extern const char gModeNameMapFld[];
extern const char gModeNameMapFix[];
extern const char gModeNameMenuNew[];
extern const char gModeNameMenuLoad[];
extern const char gModeNameMenuMsg[];
extern const char gTaskNameMapRnd[];
extern const char gTaskNameMapFix[];

extern TaskDesc gUnk_09EE484C;
extern TaskDesc gTaskDescEventDebug;
extern TaskDesc gUnk_09EE496C;
extern TaskDesc gTaskDescCardNotHave;
extern TaskDesc gTaskDescCardReload;
extern TaskDesc gUnk_09EE49CC;
extern TaskDesc gTaskDescNOCard;
extern TaskDesc gTaskDescReloadCard;
extern TaskDesc gUnk_09EE4AF4;
extern TaskDesc gTaskDescDeckCard2;
extern TaskDesc gTaskDescCardEnemy;
extern TaskDesc gUnk_09EE4B58;
extern TaskDesc gUnk_09EE4B70;
extern TaskDesc gUnk_09EE4B88;
extern TaskDesc gTaskDescReloadGage;
extern TaskDesc gUnk_09EE75D8;
extern TaskDesc gUnk_09EE7650;
extern TaskDesc gTaskDescRELOAD;
extern TaskDesc gTaskDescFriendCard;
extern TaskDesc gTaskDescHeartlessCard;
extern TaskDesc gTaskDescGimmickCard;
extern TaskDesc gUnk_09EE77D4;
extern TaskDesc gUnk_09EE77EC;
extern TaskDesc gUnk_09EE7804;
extern TaskDesc gUnk_09EE781C;
extern TaskDesc gTaskDescCardName;
extern TaskDesc gUnk_09EE784C;
extern TaskDesc gTaskDescPremireEFFECT2;
extern TaskDesc gUnk_09EE787C;
extern TaskDesc gTaskDescStockInfo;
extern TaskDesc gTaskDescLvupMsg;
extern TaskDesc gTaskDescDeckEquip;
extern TaskDesc gTaskDescDeckYesNo;
extern TaskDesc gTaskDescDeckClear;
extern TaskDesc gUnk_09EE7FA8;
extern TaskDesc gUnk_09EE7FC0;
extern TaskDesc gUnk_09EE7FD8;
extern TaskDesc gUnk_09EE7FF0;
extern TaskDesc gUnk_09EE8E18;
extern TaskDesc gUnk_09EE8E30;
extern TaskDesc gUnk_09EE8E48;
extern TaskDesc gUnk_09EE8EF0;
extern TaskDesc gTaskDescDarkPoint;

extern TaskDesc gTaskDescBosJfRock;
extern TaskDesc gTaskDescBosJfBorderline;
extern TaskDesc gTaskDescCharaMaskFade;
extern TaskDesc gTaskDescBosJfShadow;
extern TaskDesc gTaskDescPooTrap;
extern TaskDesc gTaskDescPooPitAndButterfly;
extern TaskDesc gTaskDescPooTrapballoon;
extern TaskDesc gTaskDescPooHoney;
extern TaskDesc gTaskDescPooTigerstump;
extern TaskDesc gTaskDescPooPoohstump;
extern TaskDesc gTaskDescPooTiBoard;
extern TaskDesc gTaskDescPooButterflyRight;
extern TaskDesc gTaskDescPooButterflyLeft;
extern TaskDesc gTaskDescPooMapbeeborn;
extern TaskDesc gTaskDescPooMapbutterflyborn;
extern TaskDesc gTaskDescMapEnm00;
extern TaskDesc gTaskDescMapEnm01;
extern TaskDesc gTaskDescMapEnm02;
extern TaskDesc gTaskDescMapEnm03;
extern TaskDesc gTaskDescMapEnm04;
extern TaskDesc gTaskDescMapEnm05;
extern TaskDesc gTaskDescMapEnm06;
extern TaskDesc gTaskDescMapGmkGP00;
extern TaskDesc gTaskDescMapGmkGP01;
extern TaskDesc gTaskDescMapGmkGP02;
extern TaskDesc gTaskDescMapGmkGP03;
extern TaskDesc gTaskDescMapGmkGP04;
extern TaskDesc gTaskDescMapGmkGP05;
extern TaskDesc gTaskDescMapGmkGP06;
extern TaskDesc gTaskDescMapGmkGP07;
extern TaskDesc gTaskDescMapGmkGP08;
extern TaskDesc gTaskDescMapGmkGP09;
extern TaskDesc gTaskDescMapGmk01;
extern TaskDesc gTaskDescMapGmkBarrel;
extern TaskDesc gTaskDescMapGmk04;
extern TaskDesc gTaskDescMapGmk05;
extern TaskDesc gTaskDescMapGmk06;
extern TaskDesc gTaskDescMapMsg2;
extern TaskDesc gTaskDescMapFaint;
extern TaskDesc gTaskDescRoomName;
extern TaskDesc gTaskDescBosLstEdg;
extern TaskDesc gTaskDescBosLstPtl;
extern TaskDesc gTaskDescSrollTmr;

extern const char gTaskNameBosJfRock[];
extern const char gTaskNameBosJfBorderline[];
extern const char gTaskNamePooHoney[];
extern const char gTaskNamePooPoohstump[];

extern Mode gModeWORLDSELECT;
extern const char gUnk_090359BC[];

extern Mode gModeSioDbgFlg;

#ifdef VERSION_EU
extern TaskDesc gTaskDescFrdPoohEu;
#endif

#endif
