#!/usr/bin/env python3
"""Assign functions to translation-unit modules for luvdis.

Takes a luvdis config (all discovered functions, named where known) and
produces one with a module column, grouping by the subsystem token of the
debug names (task_btl_* -> btl.s, mode_title_* -> mode_title.s, ...).

Unnamed functions inherit the module of the preceding named run; if an
unnamed stretch starts more than GAP_THRESHOLD bytes after the last named
function, it becomes its own unk_<addr>.s module (likely one or more
unidentified TUs rather than trailing helpers).

Also writes the ordered unit list consumed by configure.py.
"""

import argparse
import re
from pathlib import Path

GAP_THRESHOLD = 0x2000
CODE_START = 0x080000C0

CFG_RE = re.compile(r"(thumb_func|arm_func)?\s*(0x[0-9A-Fa-f]+)(?:\s+(\S+\.s))?\s*(\S+)?")


def token(name):
    parts = name.split("_")
    if parts[0] == "task":
        return parts[1]
    return f"{parts[0]}_{parts[1]}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("config", help="luvdis config of discovered functions")
    parser.add_argument("-o", "--output", required=True)
    parser.add_argument("--units", help="write ordered unit list here")
    parser.add_argument("--first-module", default="main.s")
    parser.add_argument("--last-module", default="lib.s",
                        help="module for functions after the last named run")
    args = parser.parse_args()

    funcs = []
    for line in open(args.config):
        line = line.split("#")[0].strip()
        if not line:
            continue
        m = CFG_RE.match(line)
        if not m:
            continue
        kind, addr, _module, name = m.groups()
        funcs.append((int(addr, 16), kind or "thumb_func", name))
    funcs.sort()

    assigned = []
    seen_counts = {}
    current = args.first_module
    last_named_addr = CODE_START
    last_named_token = None
    for addr, kind, name in funcs:
        if name:
            tok = token(name)
            if tok != last_named_token:
                seen_counts[tok] = seen_counts.get(tok, 0) + 1
                n = seen_counts[tok]
                current = f"{tok}.s" if n == 1 else f"{tok}{n}.s"
                last_named_token = tok
            last_named_addr = addr
        else:
            if (addr - last_named_addr > GAP_THRESHOLD
                    and not current.startswith("unk_")):
                current = f"unk_{addr:08x}.s"
                last_named_token = None
        assigned.append((addr, kind, name, current))

    last_named_i = max(i for i, f in enumerate(assigned) if f[2])
    for i in range(last_named_i + 1, len(assigned)):
        addr, kind, name, cur = assigned[i]
        if cur.startswith("unk_"):
            assigned[i] = (addr, kind, name, args.last_module)

    modules = []
    with open(args.output, "w") as f:
        f.write("# generated by tools/assign_modules.py -- do not edit\n")
        for addr, kind, name, module in assigned:
            if module not in modules:
                modules.append(module)
            parts = [kind, f"0x{addr:08X}", module,
                     name or f"func_{addr:08X}"]
            f.write(" ".join(parts) + "\n")

    if args.units:
        with open(args.units, "w") as f:
            f.write("# link order -- generated by tools/assign_modules.py\n")
            f.write("header.s\n")
            for m in modules:
                f.write(m + "\n")
            f.write("data.s\n")
    print(f"{len(funcs)} functions -> {len(modules)} modules")


if __name__ == "__main__":
    main()
