#include "graphics_state.h"

u16 gUnk_030074CC __attribute__((aligned(4)));
u8 gBgPaletteBank[4] __attribute__((aligned(4)));
struct BgEntry* gBgEntries __attribute__((aligned(4)));
u16 gBackdropColor __attribute__((aligned(4)));
u16 gBg2Cnt __attribute__((aligned(4)));
u16 gBg3PB __attribute__((aligned(4)));
u16 gBg3VOfs __attribute__((aligned(4)));
u16 gBg3PA __attribute__((aligned(4)));
u16 gWin1V __attribute__((aligned(4)));
u16 gWin1H __attribute__((aligned(4)));
u32 gBg2Y __attribute__((aligned(4)));
u16 gBg2PB __attribute__((aligned(4)));
u16 gBg0VOfs __attribute__((aligned(4)));
u16 gDispCnt __attribute__((aligned(4)));
u16 gBg3PC __attribute__((aligned(4)));
u16 gBg1Cnt __attribute__((aligned(4)));
u16 gBg0Cnt __attribute__((aligned(4)));
u16 gBg2PA __attribute__((aligned(4)));
u16 gBg2PC __attribute__((aligned(4)));
u16 gWin0V __attribute__((aligned(4)));
u16 gBldY __attribute__((aligned(4)));
u16 gBg2HOfs __attribute__((aligned(4)));
u32 gBg3X __attribute__((aligned(4)));
vu16 gMosaic __attribute__((aligned(4)));
u32 gBg2X __attribute__((aligned(4)));
u16 gWin0H __attribute__((aligned(4)));
u16 gBg2VOfs __attribute__((aligned(4)));
u16 gBg1HOfs __attribute__((aligned(4)));
u16 gBg3Cnt __attribute__((aligned(4)));
u16 gBg3PD __attribute__((aligned(4)));
u16 gBg0HOfs __attribute__((aligned(4)));
u16 gWinOut __attribute__((aligned(4)));
u16 gBg2PD __attribute__((aligned(4)));
u16 gWinIn __attribute__((aligned(4)));
u16 gBldCnt __attribute__((aligned(4)));
u16 gBg1VOfs __attribute__((aligned(4)));
u16 gBg3HOfs __attribute__((aligned(4)));
u32 gBg3Y __attribute__((aligned(4)));
u16 gBldAlpha __attribute__((aligned(4)));
struct FadeWork* gFadeWork __attribute__((aligned(4)));
