name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    container:
      image: ghcr.io/pheenoh/khcom-build:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [us, jp, eu]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Prepare toolchain and base ROMs
        run: |
          mkdir -p tools roms
          cp -a /agbcc/tools/agbcc tools/
          cp -a /orig/. roms/
          sha1sum -c --status <<'SUMS'
          10729bd884f8fdca7a310b6d606c52e46657aa48  roms/B8CE.gba
          59ec0a0a4ccd1e6acb3bbd7bfb21d63988958cfa  roms/B8CJ.gba
          8db73586cdb11b3795907edebf43228dbcd3e6b2  roms/B8CP.gba
          SUMS

      - name: Build and verify
        run: |
          python3 configure.py --version ${{ matrix.version }}
          ninja

      - name: Generate progress report
        if: matrix.version != 'eu'
        run: python3 -m mapfile_parser objdiff_report report.json --version ${{ matrix.version }}

      - name: Upload progress report artifact
        if: matrix.version != 'eu'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.version }}_report
          path: report.json
          if-no-files-found: error
